import { surfaceFrameTokenContract } from "../../../../layers/02-token/surface-frame/contract.mjs";

export const tokenTypeTemplate = {
  schema: "kanbien.designSystem.tokenTypeTemplate.v1",
  tokenType: "surface-frame",
  previewKind: "surface-card",
  variantSchema: {
    valueFields: [
      "surfaceRole",
      "backgroundValue",
      "foregroundValue",
      "borderValue",
      "borderWidthValue",
      "radiusValue",
      "shadowValue",
      "layoutContext",
    ],
    metadataFields: ["surfaceRole", "layoutContext", "theme", "accessibility"],
    useCaseInstructionFields: ["allowedUse", "forbiddenUse", "compositionRule"],
  },
};

const variantsInput = [
  {
    id: "surface-frame-panel",
    tokenName: "--surface-frame-panel",
    surfaceRole: "panel surface",
    backgroundValue: "#fffdf8",
    foregroundValue: "#1f2933",
    borderValue: "rgba(40, 56, 71, 0.16)",
    borderWidthValue: "0.0625rem",
    radiusValue: "0.5rem",
    shadowValue: "none",
    layoutContext: "plain brochure panels and evidence sections",
    label: "Panel surface",
    sample: "Panel",
  },
  {
    id: "surface-frame-elevated-panel",
    tokenName: "--surface-frame-elevated-panel",
    surfaceRole: "elevated panel",
    backgroundValue: "#fffdf8",
    foregroundValue: "#1f2933",
    borderValue: "rgba(40, 56, 71, 0.16)",
    borderWidthValue: "0.0625rem",
    radiusValue: "0.5rem",
    shadowValue: "0 1.25rem 3rem rgba(23, 38, 47, 0.12)",
    layoutContext: "public-site cards, article panels, and timeline sections that need elevation from the page foundation",
    label: "Elevated panel",
    sample: "Elevated",
  },
  {
    id: "surface-frame-navigation",
    tokenName: "--surface-frame-navigation",
    surfaceRole: "navigation surface",
    backgroundValue: "rgba(255, 253, 248, 0.88)",
    foregroundValue: "#1f2933",
    borderValue: "rgba(40, 56, 71, 0.16)",
    borderWidthValue: "0.0625rem",
    radiusValue: "0",
    shadowValue: "none",
    layoutContext: "top navigation surface over the brochure page foundation",
    label: "Navigation",
    sample: "Top nav",
  },
  {
    id: "surface-frame-subnav",
    tokenName: "--surface-frame-subnav",
    surfaceRole: "navigation surface",
    backgroundValue: "rgba(255, 253, 248, 0.74)",
    foregroundValue: "#1f2933",
    borderValue: "rgba(40, 56, 71, 0.16)",
    borderWidthValue: "0.0625rem",
    radiusValue: "0",
    shadowValue: "none",
    layoutContext: "breadcrumb and sub-navigation surface",
    label: "Subnav",
    sample: "Breadcrumb",
  },
  {
    id: "surface-frame-showcase",
    tokenName: "--surface-frame-showcase",
    surfaceRole: "showcase surface",
    backgroundValue: "linear-gradient(135deg, rgba(31, 111, 120, 0.08), rgba(199, 125, 42, 0.05)), rgba(255, 253, 248, 0.76)",
    foregroundValue: "#1f2933",
    borderValue: "rgba(40, 56, 71, 0.16)",
    borderWidthValue: "0.0625rem",
    radiusValue: "0.5rem",
    shadowValue: "none",
    layoutContext: "pipeline showcase panels and visual proof regions",
    label: "Showcase",
    sample: "Showcase",
  },
];

export const tokenDefinitionV1 = {
  schema: "kanbien.designSystem.tokenDefinition.v1",
  contractScope: "shared",
  designSystem: "brochure",
  uiFamily: "surface-frame",
  tokenType: "surface-frame",
  status: "review-ready",
  behaviorRulePath: "docs/design-system/01-behavior-rule/shared/colours/Colours-Behaviour.md",
  tokenContractPath: "docs/design-system/02-token/shared/surface-frame/SurfaceFrame-Contract.md",
  tokenDefinitionPath: "docs/design-system/02-token/systems/brochure/surface-frame/SurfaceFrame-Implementation.md",
  page: {
    route: "/design-system/brochure/tokens/surface-frame",
    htmlPath: "src/frontend/designSystem/systems/brochure/tokens/surface-frame/index.html",
    title: "Surface Frame Tokens",
    description: "Review governed brochure surface frame values before primitives and patterns consume them.",
  },
  codeSeam: {
    contractModule: "src/frontend/designSystem/layers/02-token/surface-frame/contract.mjs",
    contractExport: "surfaceFrameTokenContract",
    governedRuntimeModule: "src/frontend/designSystem/layers/02-token/surface-frame/systems/brochure.mjs",
    systemProofModule: "src/frontend/designSystem/systems/brochure/tokens/proofs/surfaceFrame.tokens.mjs",
    systemTokenExport: "surfaceFrameTokenSpec",
    rendererModule: "src/frontend/designSystem/shared/renderers/renderTokenSpecPage.mjs",
    rendererExport: "renderTokenSpecPage",
    allowedConsumers: ["03-primitive", "04-pattern-contract"],
  },
  variants: variantsInput.map((variant) => ({
    id: variant.id,
    tokenName: variant.tokenName,
    value: {
      surfaceRole: variant.surfaceRole,
      backgroundValue: variant.backgroundValue,
      foregroundValue: variant.foregroundValue,
      borderValue: variant.borderValue,
      borderWidthValue: variant.borderWidthValue,
      radiusValue: variant.radiusValue,
      shadowValue: variant.shadowValue,
      layoutContext: variant.layoutContext,
    },
    derivation: {
      sourceTokenName: "none",
      sourceValue: `${variant.backgroundValue} / ${variant.borderValue} / ${variant.shadowValue}`,
      formulaOrMapping: "system implementation value",
      renderedValue: `${variant.backgroundValue} with ${variant.borderWidthValue} border and ${variant.shadowValue} shadow`,
    },
    preview: {
      kind: "surface-card",
      sample: variant.sample,
      background: variant.backgroundValue,
      foreground: variant.foregroundValue,
      border: variant.borderValue,
      radius: variant.radiusValue,
      shadow: variant.shadowValue,
      label: variant.label,
    },
    metadata: {
      surfaceRole: variant.surfaceRole,
      layoutContext: variant.layoutContext,
      theme: "all",
      accessibility: "Surface treatment must not be the only indication of state, selection, or interactivity.",
    },
    useCaseInstructions: [
      `Use for ${variant.layoutContext}.`,
      "Do not use as component anatomy, layout grid, state styling, or app-local decoration.",
      "Pair with spacing, typography, and interaction primitives rather than adding local CSS literals.",
    ],
  })),
};

export const variants = tokenDefinitionV1.variants;

function toPageVariant(variant) {
  return {
    id: variant.id,
    tokenName: variant.tokenName,
    tokenValue: `${variant.value.backgroundValue} / ${variant.value.borderValue}`,
    surfaceRole: variant.value.surfaceRole,
    backgroundValue: variant.value.backgroundValue,
    foregroundValue: variant.value.foregroundValue,
    borderValue: variant.value.borderValue,
    borderWidthValue: variant.value.borderWidthValue,
    radiusValue: variant.value.radiusValue,
    shadowValue: variant.value.shadowValue,
    layoutContext: variant.value.layoutContext,
    formulaOrMapping: variant.derivation.formulaOrMapping,
    theme: variant.metadata.theme,
    accessibility: variant.metadata.accessibility,
    preview: variant.preview,
    usage: [
      { label: "Allowed", text: variant.useCaseInstructions[0] },
      { label: "Denied", text: variant.useCaseInstructions[1] },
      { label: "Composition", text: variant.useCaseInstructions[2] },
    ],
  };
}

export const surfaceFrameTokenVariants = variants.map(toPageVariant);

export const surfaceFrameTokenSpec = {
  contractId: surfaceFrameTokenContract.contractId,
  systemKey: tokenDefinitionV1.designSystem,
  tokenType: tokenDefinitionV1.tokenType,
  title: tokenDefinitionV1.page.title,
  description: tokenDefinitionV1.page.description,
  variantSectionDescription: "These tokens govern reusable brochure surface frames without defining component anatomy.",
  tokenTypeTemplate,
  summaryPanels: [
    { label: "Panel", title: "Plain content panel", variantId: "surface-frame-panel" },
    { label: "Elevated", title: "Raised public card", variantId: "surface-frame-elevated-panel" },
    { label: "Nav", title: "Navigation chrome", variantId: "surface-frame-navigation" },
  ],
  variantFields: [
    ["surfaceRole", "Role"],
    ["backgroundValue", "Background"],
    ["borderValue", "Border"],
    ["borderWidthValue", "Border width"],
    ["radiusValue", "Radius"],
    ["shadowValue", "Shadow"],
    ["layoutContext", "Layout context"],
  ],
  variants: surfaceFrameTokenVariants,
  consumerRestrictions: surfaceFrameTokenContract.consumerRules,
  requiredEvidence: [
    "The proof route must render every surface frame.",
    "Later primitives and patterns must consume these frame values through the runtime seam.",
  ],
};
