export const statusColorTokenContract = {
  schema: "kanbien.designSystem.tokenContract.v1",
  contractId: "tokens.status-color",
  tokenType: "status-color",
  requiredVariantRoles: ["status color"],
  requiredStates: ["warning"],
  requiredThemes: ["original", "dark", "desert"],
  requiredVariantFields: ["id", "tokenName", "value", "preview", "metadata", "useCaseInstructions"],
  valueFields: [
    "statusRole",
    "status",
    "theme",
    "sourceColorValue",
    "backgroundValue",
    "foregroundValue",
    "borderValue",
    "subtleBackgroundValue",
    "strongBackgroundValue",
    "contrastPairing",
  ],
  metadataFields: ["statusRole", "theme", "status", "accessibility"],
  useCaseInstructionFields: ["allowedUse", "forbiddenUse", "colorIndependentRule"],
  consumerRules: [
    "Consumers must use this token for governed status colour pairings instead of local warning, error, success, or status literals.",
    "The current review-ready status is warning only; success, info, and broader error status colour variants are not approved by this token until added explicitly.",
    "Status colour must never be the only cue for status meaning.",
    "This token does not define validation behavior, status text, live region semantics, icons, badges, cards, or component state transitions.",
  ],
};
