export const topNavigationFrameTokenContract = {
  schema: "kanbien.designSystem.tokenContract.v1",
  contractId: "tokens.top-navigation-frame",
  tokenType: "top-navigation-frame",
  status: "review-ready",
  requiredVariantRoles: [
    "top navigation chrome",
    "top navigation destination",
    "top navigation current destination",
    "top navigation trigger",
    "top navigation open trigger",
    "top navigation menu panel",
  ],
  requiredVariantFields: ["id", "tokenName", "value", "preview", "metadata", "useCaseInstructions"],
  valueFields: [
    "frameRole",
    "backgroundValue",
    "foregroundValue",
    "supportingForegroundValue",
    "borderValue",
    "radiusValue",
    "paddingBlockValue",
    "paddingInlineValue",
    "gapValue",
    "minInlineSize",
    "minBlockSize",
    "shadowValue",
    "zIndexValue",
    "themeMapping",
    "stateMapping",
  ],
  metadataFields: ["frameRole", "theme", "state", "accessibility"],
  useCaseInstructionFields: ["allowedUse", "forbiddenUse", "proofRequirement"],
  consumerRules: [
    "Top-navigation primitives may consume this seam for chrome, destination, current-destination, trigger, open-trigger, and transient menu frame values.",
    "Consumers must not use old design-system CSS variables such as --surface-1, --ink, --line, --accent, --shadow, or --radius as construction tokens.",
    "This token does not define brand markup, destination semantics, profile behavior, overflow measurement, mobile collapse, keyboard behavior, menu item anatomy, component APIs, or app adoption.",
    "Current-destination values must be paired with programmatic current semantics in the primitive or pattern layer.",
    "Open-trigger values must be paired with programmatic expanded semantics in the primitive or pattern layer.",
  ],
};
