export const contextNavigationOverflowMenuFrameTokenContract = {
  schema: "kanbien.designSystem.tokenContract.v1",
  contractId: "tokens.context-navigation-overflow-menu-frame",
  tokenType: "context-navigation-overflow-menu-frame",
  requiredVariantRoles: ["context navigation overflow menu frame"],
  requiredThemes: ["all"],
  requiredVariantFields: ["id", "tokenName", "value", "preview", "metadata", "useCaseInstructions"],
  valueFields: [
    "frameRole",
    "minInlineSize",
    "paddingValue",
    "borderValue",
    "radiusValue",
    "backgroundValue",
    "shadowValue",
    "zIndexValue",
    "desktopBottomOffset",
    "desktopInlineOffset",
    "mobileBottomOffset",
    "mobileInlineInset",
  ],
  metadataFields: ["frameRole", "placementBehavior", "accessibility"],
  useCaseInstructionFields: ["allowedUse", "forbiddenUse", "proofRequirement"],
  consumerRules: [
    "Context-navigation overflow menu primitives must consume this token for menu frame, placement, and layer values.",
    "Consumers must not use this token to define item semantics, trigger behavior, drawer payloads, or app routing.",
    "Overflow menus must preserve keyboard close and focus restoration behavior in their primitive or pattern consumer.",
  ],
};
