export const toggleFrameTokenContract = {
  schema: "kanbien.designSystem.tokenContract.v1",
  contractId: "tokens.toggle-frame",
  tokenType: "toggle-frame",
  requiredVariantRoles: ["toggle frame"],
  requiredThemes: ["original", "dark", "desert"],
  requiredStates: ["off", "on", "read-only", "disabled", "error"],
  requiredVariantFields: ["id", "tokenName", "value", "preview", "metadata", "useCaseInstructions"],
  valueFields: [
    "frameRole",
    "state",
    "theme",
    "trackBackgroundValue",
    "trackBorderValue",
    "trackBorderWidthValue",
    "thumbBackgroundValue",
    "thumbForegroundValue",
    "trackInlineSize",
    "trackBlockSize",
    "thumbInlineSize",
    "thumbBlockSize",
    "thumbOffsetValue",
    "trackPaddingValue",
    "trackRadiusValue",
    "thumbRadiusValue",
    "thumbShadowValue",
    "motionDurationValue",
    "motionEasingValue",
    "minimumTargetWidth",
    "minimumTargetHeight",
  ],
  metadataFields: ["frameRole", "theme", "state", "accessibility"],
  useCaseInstructionFields: ["allowedUse", "forbiddenUse", "pairingRule"],
  consumerRules: [
    "Consumers must use this token for governed toggle track, thumb, state, and motion visuals instead of hard-coding switch values locally.",
    "Toggle on-state visuals must derive from primary-color-source over a signed host surface for the selected design system.",
    "This token does not define toggle semantics, keyboard behavior, accessible names, validation copy, field labels, or persistence.",
    "Toggle primitives must pair this token with focus-ring, minimum-target-size, and a governed semantic control strategy.",
  ],
};
