export interface RootAuthzCapabilityCatalogEntry {
  capabilityKey: string;
  description: string;
  mandatoryForRootUserAdmin: boolean;
  protectedForRootUserAdmin: boolean;
}

export const ROOT_USER_ADMIN_ROLE_KEY = "RootUserAdmin";

export const ROOT_AUTHZ_CAPABILITY_CATALOG: RootAuthzCapabilityCatalogEntry[] = [
  {
    capabilityKey: "root-auth.principal.create",
    description: "Create a root auth principal for a root user.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-auth.password.change.own",
    description: "Change the authenticated root user's own password.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-auth.ssh-key.create.own",
    description: "Add an SSH public key to the authenticated root user's own auth principal.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-auth.ssh-key.read.own",
    description: "List SSH public keys for the authenticated root user's own auth principal.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-auth.ssh-key.revoke.own",
    description: "Revoke an SSH public key for the authenticated root user's own auth principal.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-auth.session.read.own",
    description: "List sessions for the authenticated root user's own auth principal.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-auth.session.revoke.own",
    description: "Revoke a session for the authenticated root user's own auth principal.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-auth.session.logout.own",
    description: "Log out the authenticated root user's own current session.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-admin-shell.session.read.own",
    description: "Read the authenticated root user's own browser session summary.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-admin-shell.session.logout.own",
    description: "Log out the authenticated root user's own browser session.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-user.create",
    description: "Create a root user.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-user.read.visible",
    description: "Read visible root users and exact visible root-user lookups.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-user.read.active",
    description: "List active root users only.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: false,
  },
  {
    capabilityKey: "root-user.read.deleted",
    description: "List deleted root users explicitly.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-user.update",
    description: "Update editable root-user metadata and lifecycle-safe fields.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-user.delete",
    description: "Soft-delete a root user.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-user.remove",
    description: "Irreversibly anonymize and remove a root user.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-user.reactivate",
    description: "Reactivate a previously deleted root user.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "tenant.create",
    description: "Create a tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "tenant.read",
    description: "Read one visible tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "tenant.list",
    description: "List visible tenants.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "tenant.update",
    description: "Update editable tenant metadata.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "tenant.read.deleted",
    description: "Read one deleted tenant explicitly.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "tenant.list.deleted",
    description: "List deleted tenants explicitly.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "tenant.delete",
    description: "Soft-delete a tenant.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "tenant.reactivate",
    description: "Reactivate a previously deleted tenant.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "tenant.remove",
    description:
      "Irreversibly remove a tenant while no dependent tenant-owned entities exist.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "notification.email.send",
    description: "Send outbound emails through the shared notification-delivery feature.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "notification.email.resend",
    description: "Resend an outbound email through the shared notification-delivery feature.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "notification.email.read",
    description:
      "List and inspect outbound-email metadata through the shared notification-delivery feature.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "capability-contract-catalog.read",
    description: "Read persisted capability contract catalog records.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "capability-contract-catalog.export",
    description: "Export deterministic capability contract catalog snapshots.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "capability-contract-catalog.materialize",
    description: "Materialize persisted capability contract catalog records from approved source truth.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "capability-contract-catalog.audit-drift",
    description: "Audit drift between persisted capability contract catalog truth and current approved sources.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "tenant-admin.create",
    description: "Create a tenant-admin actor record within a tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "tenant-admin.read",
    description: "Read one visible tenant-admin actor record.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "tenant-admin.list",
    description: "List visible tenant-admin actor records.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "tenant-admin.update",
    description: "Update editable tenant-admin profile fields.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "tenant-admin.verification.send",
    description: "Send an email-verification message for a tenant admin.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "tenant-admin.verification.resend",
    description: "Resend an email-verification message for a tenant admin.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "tenant-admin.onboarding.restart",
    description: "Restart tenant-auth onboarding for a verified tenant admin.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.create",
    description: "Create an organization within a tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.read",
    description: "Read active organization records within a tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.list",
    description: "List active organization records within a tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.update",
    description: "Update editable organization fields within a tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.move",
    description: "Move an organization within an approved tenant hierarchy.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.archive",
    description: "Archive an organization branch or archive while reparenting children.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.restore",
    description: "Restore an archived organization record when hierarchy rules allow it.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.delete",
    description: "Soft-delete an organization record with no active children.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.legal-profile.manage",
    description: "Create and manage organization legal profiles within a tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.legal-profile.read",
    description: "Read organization legal profiles within a tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.location.manage",
    description: "Create and manage organization locations within a tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.location.read",
    description: "Read organization locations within a tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.weekly-hours-slot.manage",
    description: "Create and manage organization weekly opening-hour slots within a tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.weekly-hours-slot.read",
    description: "Read organization weekly opening-hour slots within a tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.opening-hours-exception.manage",
    description: "Create and manage organization opening-hour exceptions within a tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.opening-hours-exception.read",
    description: "Read organization opening-hour exceptions within a tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.business-unit.manage",
    description: "Create and manage organization business units within a tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.business-unit.read",
    description: "Read organization business units within a tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.business-unit-membership.manage",
    description: "Create and manage organization business-unit memberships within a tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.business-unit-membership.read",
    description: "Read organization business-unit memberships within a tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.root.search",
    description: "Run grouped Organization-domain search for a selected tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.tenant.search",
    description: "Run grouped Organization-domain search for the current tenant context.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.root.logo.manage",
    description: "Manage Organization primary logo relationships and upload flow for a selected tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.tenant.logo.manage",
    description: "Manage Organization primary logo relationships and upload flow for the current tenant context.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.root.export.manage",
    description: "Manage private Organization export bundles for a selected tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "organization.tenant.export.manage",
    description: "Manage private Organization export bundles for the current tenant context.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-hierarchy.create-module",
    description: "Create a web-app module within a root family.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-hierarchy.update-module",
    description: "Update editable web-app module metadata.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-hierarchy.update-module-landing-page",
    description: "Update the direct-child landing page for a web-app module.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-hierarchy.create-page",
    description: "Create a durable web-app page node.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-hierarchy.update-page",
    description: "Update editable web-app page metadata.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-hierarchy.move-page",
    description: "Move or orphan a web-app page node safely.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-hierarchy.read-tree",
    description: "Read the resolved web-app hierarchy tree.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-hierarchy.read-planner-options",
    description: "Read planner-selectable hierarchy nodes.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-hierarchy.list-orphans",
    description: "List orphaned web-app pages for recovery workflows.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-hierarchy.bootstrap",
    description: "Bootstrap the web-app hierarchy from real navigable pages.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-hierarchy.sync-discovery",
    description: "Run discovery-backed web-app hierarchy sync and return the updated tree.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-hierarchy.preview-discovery-sync",
    description: "Preview structure-aware discovery reconcile before mutating the curated hierarchy.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-hierarchy.apply-discovery-sync",
    description: "Apply structure-aware discovery reconcile to the curated hierarchy.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-hierarchy.read-discovery-link-status",
    description: "Read durable discovery-link and drift status for the web-app hierarchy.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-page-settings.read",
    description: "Read durable page settings for one curated web-app page.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-page-settings.update",
    description: "Create or update durable page settings for one curated web-app page.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-page-settings.read-options",
    description: "Read approved page-settings options for one curated web-app page.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-surface-discovery.run",
    description: "Run web-app surface discovery over approved route families.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-surface-discovery.read",
    description: "Read current discovered web-app surfaces.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-surface-discovery.read-runs",
    description: "Read web-app discovery run history.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "web-app-surface-discovery.read-structure",
    description: "Read current discovered web-app structure trees and exact structure nodes.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "tenant-auth-policy.read",
    description: "Read the effective tenant auth policy for a tenant.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "tenant-auth-policy.update",
    description: "Update tenant-scoped tenant auth policy overrides.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "entity-builder.create",
    description: "Create an entity-definition lineage or replacement version.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "entity-builder.update",
    description: "Update a draft entity-definition version.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "entity-builder.read",
    description: "Read current and exact entity-definition versions.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "entity-builder.catalog.read",
    description: "Read approved entity-builder catalogs.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "entity-builder.validate",
    description: "Validate entity-definition versions for activation and export.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "entity-builder.export",
    description: "Export derived entity-definition snapshots.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "entity.create",
    description: "Create a root-managed Entity instruction record.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "entity.read",
    description: "Read and list root-managed Entity instruction records.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "entity.update",
    description: "Update root-managed Entity instruction metadata and lifecycle status.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "entity.delete",
    description: "Archive a root-managed Entity instruction record.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "tenant-admin.delete",
    description: "Soft-delete a tenant-admin actor record.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "tenant-admin.reactivate",
    description: "Reactivate a previously deleted tenant-admin actor record.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-role.create",
    description: "Create a system root role.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-role.read",
    description: "Read one system root role.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-role.list",
    description: "List system root roles.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-role.update",
    description: "Update editable system root-role metadata.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-role.delete",
    description: "Deactivate a system root role from future assignment.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-role.reactivate",
    description: "Reactivate a deactivated system root role.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-role.capability-catalog.read",
    description: "List eligible authz capabilities for root-role editing.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-role.capability-assignment.read",
    description: "Read assigned authz capabilities for a root role.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-role.capability-assignment.update",
    description: "Bulk update authz capability grants for a root role.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-role.assignment.assign",
    description: "Assign a root role to a root user.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-role.assignment.unassign",
    description: "Unassign a root role from a root user safely.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-role.assignment.list",
    description: "List root-role assignments for a root user.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-role.assignment.replace",
    description: "Atomically replace one root-role assignment with another.",
    mandatoryForRootUserAdmin: true,
    protectedForRootUserAdmin: true,
  },
  {
    capabilityKey: "root-role.effective-permissions.read",
    description: "Read the effective permission set for a root user.",
    mandatoryForRootUserAdmin: false,
    protectedForRootUserAdmin: true,
  },
];

const CAPABILITY_ENTRY_BY_KEY = new Map(
  ROOT_AUTHZ_CAPABILITY_CATALOG.map((entry) => [entry.capabilityKey, entry]),
);

export function getRootAuthzCapabilityEntry(
  capabilityKey: string,
): RootAuthzCapabilityCatalogEntry | null {
  return CAPABILITY_ENTRY_BY_KEY.get(capabilityKey) ?? null;
}
