export const visualProofOrnamentTokenContract = {
  schema: "kanbien.designSystem.tokenContract.v1",
  contractId: "tokens.visual-proof-ornament",
  tokenType: "visual-proof-ornament",
  requiredVariantRoles: ["grid lines", "visual chip", "connector line", "accent bar", "overlay wash", "visual marker"],
  requiredThemes: ["all"],
  requiredVariantFields: ["id", "tokenName", "value", "preview", "metadata", "useCaseInstructions"],
  valueFields: [
    "ornamentRole",
    "backgroundValue",
    "foregroundValue",
    "gridColorValue",
    "gridSizeValue",
    "chipBackgroundValue",
    "chipBorderValue",
    "chipRadiusValue",
    "chipOpacityValue",
    "lineColorValue",
    "lineSizeValue",
    "accentBarValue",
    "overlayValue",
    "markerSizeValue",
    "markerBackgroundValue",
    "markerRadiusValue",
    "layoutContext",
  ],
  metadataFields: ["ornamentRole", "layoutContext", "theme", "accessibility"],
  useCaseInstructionFields: ["allowedUse", "forbiddenUse", "meaningRule"],
  consumerRules: [
    "Consumers must use this token for governed visual proof ornament materials instead of local diagram decoration literals.",
    "This token does not define illustration layout, number of chips, artifact content, product workflow, animation, or semantic state.",
    "Visual ornaments must not be the only carrier of status, validation, selected, or proof outcome meaning.",
  ],
};
