export const menuSimpleSelectFrameTokenContract = {
  schema: "kanbien.designSystem.tokenContract.v1",
  contractId: "tokens.menu-simple-select-frame",
  tokenType: "menu-simple-select-frame",
  requiredVariantRoles: [
    "trigger frame",
    "icon trigger frame",
    "menu panel",
    "option item",
    "current option item",
    "disabled option item",
  ],
  requiredValueFields: [
    "frameRole",
    "backgroundValue",
    "foregroundValue",
    "borderValue",
    "radiusValue",
    "paddingBlockValue",
    "paddingInlineValue",
    "gapValue",
    "minBlockSize",
    "minInlineSize",
    "maxInlineSize",
    "maxBlockSize",
    "zIndexValue",
    "scrollBehavior",
  ],
  consumerRules: [
    "Every design system must expose governed menu-simple-select frame values before primitives own text trigger, icon trigger, panel, or option visuals.",
    "Consumers must use the runtime seam instead of local trigger, menu, option, selected, disabled, border, radius, spacing, z-index, or scroll-height literals.",
    "This token does not define select ARIA behavior, keyboard handling, option row anatomy, header placement, or app adoption.",
  ],
};
