export const contextNavigationFrameTokenContract = {
  schema: "kanbien.designSystem.tokenContract.v1",
  contractId: "tokens.context-navigation-frame",
  tokenType: "context-navigation-frame",
  requiredVariantRoles: ["context navigation frame"],
  requiredValueFields: [
    "frameRole",
    "desktopPositioningModel",
    "mobilePositioningModel",
    "desktopRailInlineSize",
    "desktopRailTopOffset",
    "desktopRailBottomOffset",
    "desktopRailGapValue",
    "desktopRailPaddingBlockValue",
    "desktopRailPaddingInlineValue",
    "desktopPrimaryScrollBehavior",
    "utilityZoneAnchorBehavior",
    "mobileBreakpoint",
    "mobileBarBlockOffset",
    "mobileBarInsetInlineStart",
    "mobileBarInsetInlineEnd",
    "mobileBarColumns",
    "mobileBarPaddingBlockStart",
    "mobileBarPaddingInline",
    "mobileBarPaddingBlockEnd",
    "mobilePageBottomReserve",
    "mobileDrawerBottomOffset",
    "mobileViewportPinningBehavior",
    "mobileScrollBoundaryBehavior",
    "surfaceValue",
    "borderValue",
    "shadowValue",
  ],
  consumerRules: [
    "Every design system must expose governed context-navigation frame values before primitives, patterns, or components own rail placement, primary-zone scrolling, utility anchoring, mobile bottom-bar placement, drawer offsets, or scroll-boundary behavior.",
    "Mobile context navigation must remain pinned to the visual viewport bottom and must not participate in document scroll or page-end overscroll.",
    "Desktop context navigation must keep the primary zone scrollable while the bottom utility zone remains anchored and visible.",
    "This token does not approve destination item anatomy, active-state treatment, More-menu behavior, drawer payload behavior, component seams, or app adoption.",
  ],
};
