export const supportingTextStyleTokenContract = {
  schema: "kanbien.designSystem.tokenContract.v1",
  contractId: "tokens.supporting-text-style",
  tokenType: "text-style",
  requiredVariantRoles: ["supporting text"],
  requiredThemes: ["all"],
  requiredVariantFields: ["id", "tokenName", "value", "preview", "metadata", "useCaseInstructions"],
  valueFields: [
    "textStyleRole",
    "fontFamilyValue",
    "fontFallbackRule",
    "fontSizeValue",
    "fontWeightValue",
    "lineHeightValue",
    "letterSpacingValue",
    "textTransform",
    "overflowReadiness",
    "zoomBehavior",
  ],
  metadataFields: ["textStyleRole", "theme", "state", "accessibility"],
  useCaseInstructionFields: ["allowedUse", "forbiddenUse", "overflowRule"],
  consumerRules: [
    "Consumers must use this token for compact supporting text instead of local typography literals.",
    "Consumers must preserve the complete font fallback stack.",
    "This token does not define count calculation, item state, foreground color, opacity, or tooltip behavior.",
  ],
};
