export const detailSlotFrameTokenContract = {
  schema: "kanbien.designSystem.tokenContract.v1",
  contractId: "tokens.detail-slot-frame",
  tokenType: "detail-slot-frame",
  requiredVariantRoles: ["detail slot frame"],
  requiredValueFields: [
    "frameRole",
    "theme",
    "backgroundValue",
    "foregroundValue",
    "borderValue",
    "detailSurfaceValue",
    "radiusValue",
    "paddingBlockValue",
    "paddingInlineValue",
    "gapValue",
    "minInlineSize",
    "maxInlineSize",
    "mobileInlineSize",
    "mobileBreakpointValue",
    "maxBlockSize",
    "scrollBehavior",
  ],
  consumerRules: [
    "Every design system must expose governed detail-slot frame values before list-detail, drawer-like detail, or record-detail primitives own panel surface, padding, width, theme, or scroll sizing.",
    "Consumers must use the runtime seam instead of local detail-slot width, padding, surface, border, radius, or scroll-height literals.",
    "This token does not define row activation, list composition, close-button behavior, focus return, product detail content, route selection, workflow behavior, or app adoption.",
  ],
};
