export const standardPageShellFrameTokenContract = {
  schema: "kanbien.designSystem.tokenContract.v1",
  contractId: "tokens.standard-page-shell-frame",
  tokenType: "standard-page-shell-frame",
  requiredVariantRoles: ["standard page shell frame"],
  requiredValueFields: [
    "frameRole",
    "topNavLayer",
    "subNavLayer",
    "contextNavLayer",
    "contextNavDrawerLayer",
    "contextNavMenuLayer",
    "tooltipLayer",
    "topNavPaddingBlockValue",
    "topNavPaddingInlineValue",
    "topNavGapValue",
    "subNavPaddingBlockValue",
    "subNavPaddingInlineValue",
    "subNavGapValue",
    "subNavSearchMaxInlineSize",
    "mobileBreakpoint",
    "contextRailInlineSize",
    "contextRailItemSize",
    "contextRailGapValue",
    "contextRailPaddingBlockValue",
    "contextRailPaddingInlineValue",
    "mobileContextBarOffset",
    "mobileShellPagePaddingBottom",
    "sidePanelInlineSize",
    "secondarySidePanelInlineStart",
    "mobileContextBarColumns",
    "mobileContextBarPinning",
    "surfaceTopNav",
    "surfaceSubNav",
    "surfaceContextNav",
    "borderValue",
  ],
  consumerRules: [
    "Every design system must expose governed shell-frame values before shell primitives, patterns, or components own shell chrome placement, layer ordering, rail sizing, drawer placement, or mobile safe-area insets.",
    "Consumers must use the runtime seam instead of local shell z-index, rail width, drawer offset, shell padding, search max-width, mobile context-bar column, or mobile page-bottom inset literals.",
    "This token does not approve child navigation item anatomy, profile menus, breadcrumb behavior, search behavior, tools-nav content, bottom interaction bars, component seams, or app adoption.",
  ],
};
