export const choiceCardStateAffordanceTokenContract = {
  schema: "kanbien.designSystem.tokenContract.v1",
  contractId: "tokens.choice-card-state-affordance",
  tokenType: "choice-card-state-affordance",
  requiredVariantRoles: ["choice card state affordance"],
  requiredStates: ["visible", "hidden", "priority-selected", "priority-not-on"],
  requiredThemes: ["original", "dark", "desert"],
  requiredVariantFields: ["id", "tokenName", "value", "preview", "metadata", "useCaseInstructions"],
  valueFields: [
    "affordanceRole",
    "variant",
    "state",
    "theme",
    "glyphSemantic",
    "glyphDisplay",
    "stateTextRole",
    "glyphInlineSize",
    "glyphBlockSize",
    "leadingInlineSize",
    "trailingMinInlineSize",
    "contentGapValue",
    "glyphColorValue",
    "stateTextColorValue",
    "stateTextStyleTokenName",
  ],
  metadataFields: ["affordanceRole", "variant", "state", "theme", "glyphSemantic", "accessibility"],
  useCaseInstructionFields: ["allowedUse", "forbiddenUse", "pairingRule"],
  consumerRules: [
    "Consumers must use this token for governed card-list select state affordance slots instead of primitive-local slot, gap, or trailing-status values.",
    "Visible/hidden and priority/not-on states must remain color-independent through glyph semantics and state text.",
    "This token does not define glyph artwork, checkbox behavior, priority ranking behavior, selected value state, focus behavior, or card frame visuals.",
    "Card-list select primitives must pair this token with choice-option-frame, choice-group-layout, focus-ring, label text, supporting text, and text disclosure.",
  ],
};
