export const feedbackTextStyleTokenContract = {
  schema: "kanbien.designSystem.tokenContract.v1",
  contractId: "tokens.feedback-text-style",
  tokenType: "feedback-text-style",
  requiredVariantRoles: ["feedback text"],
  requiredThemes: ["original", "dark", "desert"],
  requiredStates: ["neutral", "warning", "error"],
  requiredVariantFields: ["id", "tokenName", "value", "preview", "metadata", "useCaseInstructions"],
  valueFields: [
    "textStyleRole",
    "feedbackTone",
    "theme",
    "fontFamilyValue",
    "fontFallbackRule",
    "fontSizeValue",
    "fontWeightValue",
    "lineHeightValue",
    "letterSpacingValue",
    "textTransform",
    "foregroundValue",
    "overflowReadiness",
    "zoomBehavior",
  ],
  metadataFields: ["textStyleRole", "feedbackTone", "theme", "accessibility"],
  useCaseInstructionFields: ["allowedUse", "forbiddenUse", "overflowRule"],
  consumerRules: [
    "Consumers must use this token for short non-field panel or pattern feedback text instead of local typography or foreground literals.",
    "Consumers must preserve the complete font fallback stack and signed foreground source.",
    "This token does not define product copy, live-region semantics, validation behavior, icons, empty-state layout, helper text, field-row errors, tooltip text, or body paragraphs.",
  ],
};
