export const pipelineShowcaseFrameTokenContract = {
  schema: "kanbien.designSystem.tokenContract.v1",
  contractId: "tokens.pipeline-showcase-frame",
  tokenType: "pipeline-showcase-frame",
  requiredVariantRoles: [
    "step selector inactive frame",
    "step selector active frame",
    "mobile dropdown selector frame",
    "active step panel frame",
  ],
  requiredThemes: ["all"],
  requiredVariantFields: ["id", "tokenName", "value", "preview", "metadata", "useCaseInstructions"],
  valueFields: [
    "frameRole",
    "backgroundValue",
    "foregroundValue",
    "borderValue",
    "borderWidthValue",
    "radiusValue",
    "shadowValue",
    "paddingBlockValue",
    "paddingInlineValue",
    "minBlockSizeValue",
    "gapValue",
    "layoutContext",
  ],
  metadataFields: ["frameRole", "state", "theme", "accessibility"],
  useCaseInstructionFields: ["allowedUse", "forbiddenUse", "pairingRule"],
  consumerRules: [
    "Consumers must use this token for governed ordered pipeline selector and panel frames instead of local frame literals.",
    "This token does not define tablist markup, select controller behavior, panel composition, responsive breakpoints, or app adoption.",
    "Selected state must remain programmatic and visible through more than color; these frame values are visual support only.",
    "Consumers must pair this token with governed focus-ring, text, spacing, and minimum-target-size tokens.",
  ],
};
