export const toolsNavigationFrameTokenContract = {
  schema: "kanbien.designSystem.tokenContract.v1",
  contractId: "tokens.tools-navigation-frame",
  tokenType: "tools-navigation-frame",
  requiredVariantRoles: ["tools navigation frame"],
  requiredVariantFields: ["id", "tokenName", "value", "preview", "metadata", "useCaseInstructions"],
  valueFields: [
    "frameRole",
    "desktopPositioningModel",
    "desktopRailInlineSize",
    "desktopRailTopOffset",
    "desktopRailBottomOffset",
    "desktopRailGapValue",
    "desktopRailPaddingBlockValue",
    "desktopRailPaddingInlineValue",
    "mobileBreakpoint",
    "mobileVisibility",
    "surfaceValue",
    "borderValue",
    "shadowValue",
    "itemInlineSize",
    "itemBlockSize",
    "itemRadiusValue",
    "itemRestingBackgroundValue",
    "itemRestingForegroundValue",
    "itemHoverBackgroundValue",
    "itemActiveBackgroundValue",
    "itemActiveForegroundValue",
    "itemUnavailableOpacityValue",
  ],
  metadataFields: ["frameRole", "responsiveBehavior", "stateModel", "accessibility"],
  useCaseInstructionFields: ["allowedUse", "forbiddenUse", "proofRequirement"],
  consumerRules: [
    "Tools-navigation primitives and patterns must consume this token for desktop right-rail placement, item affordance values, and the current mobile-hidden posture.",
    "Mobile tools-navigation is hidden in this token version; consumers must not invent a mobile drawer, bottom bar, floating launcher, or overflow menu from this token.",
    "This token does not define tool payloads, panel internals, product action semantics, component props, or app adoption.",
  ],
};
