export const choiceOptionFrameTokenContract = {
  schema: "kanbien.designSystem.tokenContract.v1",
  contractId: "tokens.choice-option-frame",
  tokenType: "choice-option-frame",
  requiredVariantRoles: ["choice option frame"],
  requiredStates: ["default", "selected", "disabled", "error"],
  requiredThemes: ["original", "dark", "desert"],
  requiredVariantFields: ["id", "tokenName", "value", "preview", "metadata", "useCaseInstructions"],
  valueFields: [
    "frameRole",
    "state",
    "theme",
    "backgroundValue",
    "foregroundValue",
    "borderValue",
    "radiusValue",
    "paddingBlockValue",
    "paddingInlineValue",
    "textGapValue",
    "minBlockSize",
    "labelTextStyleTokenName",
    "supportingTextStyleTokenName",
  ],
  metadataFields: ["frameRole", "theme", "state", "accessibility"],
  useCaseInstructionFields: ["allowedUse", "forbiddenUse", "pairingRule"],
  consumerRules: [
    "Consumers must use this token for governed selectable choice-option frame visuals instead of primitive-local or pattern-local frame values.",
    "Selected option frames must derive from signed primary tint tokens; error option frames must derive from signed error text foreground.",
    "This token does not define radio semantics, checkbox semantics, selected value behavior, accessible names, focus rings, text disclosure, or option-grid layout.",
    "Interactive choice primitives must pair this token with minimum-target-size, focus-ring, label-text-style, supporting-text-style, and the relevant native control behavior.",
  ],
};
