export const accordionFrameTokenContract = {
  schema: "kanbien.designSystem.tokenContract.v1",
  contractId: "tokens.accordion-frame",
  tokenType: "accordion-frame",
  requiredVariantRoles: ["accordion section frame"],
  requiredValueFields: [
    "frameRole",
    "theme",
    "headerBackgroundValue",
    "headerForegroundValue",
    "contentBackgroundValue",
    "contentForegroundValue",
    "borderValue",
    "separatorValue",
    "headerMinBlockSize",
    "headerPaddingBlockValue",
    "headerPaddingInlineValue",
    "contentPaddingBlockValue",
    "contentPaddingInlineValue",
    "gapValue",
    "indicatorInlineSize",
    "indicatorBlockSize",
    "motionDurationValue",
    "motionEasingValue",
  ],
  consumerRules: [
    "Every design system must expose governed accordion section frame values before accordion primitives own header, indicator, content-region, or separator visuals.",
    "Consumers must use the runtime seam instead of local accordion header height, padding, border, separator, indicator size, or motion literals.",
    "This token does not define accordion markup, expanded/collapsed semantics, keyboard behavior, multi-section grouping, nested form controls, validation, persistence, or app adoption.",
  ],
};
