export const countCardFrameTokenContract = {
  schema: "kanbien.designSystem.tokenContract.v1",
  contractId: "tokens.count-card-frame",
  tokenType: "count-card-frame",
  requiredVariantRoles: ["count card frame"],
  requiredStates: ["default", "selected", "disabled", "warning", "error"],
  requiredThemes: ["original", "dark", "desert"],
  requiredVariantFields: ["id", "tokenName", "value", "preview", "metadata", "useCaseInstructions"],
  valueFields: [
    "frameRole",
    "state",
    "theme",
    "backgroundValue",
    "foregroundValue",
    "borderValue",
    "radiusValue",
    "paddingBlockValue",
    "paddingInlineValue",
    "contentGapValue",
    "minBlockSize",
    "countSlotMinInlineSize",
    "countBackgroundValue",
    "countForegroundValue",
    "countBorderValue",
  ],
  metadataFields: ["frameRole", "theme", "state", "accessibility"],
  useCaseInstructionFields: ["allowedUse", "forbiddenUse", "statusScope"],
  consumerRules: [
    "Consumers must use this token for governed count-card frame visuals instead of route-local or pattern-local card values.",
    "Selected count-card frames must derive from signed primary tint tokens.",
    "Warning count-card frames must consume the signed status-color warning token instead of owning warning colour values locally.",
    "This token does not define count-card behavior, button or link semantics, selected-item calculations, filtering, search, grouping, or tooltip disclosure.",
  ],
};
