export const dropdownListboxFrameTokenContract = {
  schema: "kanbien.designSystem.tokenContract.v1",
  contractId: "tokens.dropdown-listbox-frame",
  tokenType: "dropdown-listbox-frame",
  requiredVariantRoles: ["listbox popup frame"],
  requiredThemes: ["original", "dark", "desert"],
  requiredVariantFields: ["id", "tokenName", "value", "preview", "metadata", "useCaseInstructions"],
  valueFields: [
    "frameRole",
    "theme",
    "backgroundValue",
    "foregroundValue",
    "borderValue",
    "radiusValue",
    "paddingBlockValue",
    "paddingInlineValue",
    "gapValue",
    "popupOffsetBlock",
    "desktopMaxBlockSize",
    "mobileMaxBlockSize",
    "scrollBehavior",
    "scrollbarSkinTokenName",
  ],
  consumerRules: [
    "Consumers must use this token for governed simple dropdown listbox popup frame values.",
    "Consumers must not hard-code dropdown popup max height, popup offset, internal scroll styling, or listbox surface values in primitive or pattern CSS.",
    "This token does not define option semantics, keyboard behavior, selection state, search, multi-select, or popup placement beyond the simple dropdown below-trigger posture.",
  ],
};
