export const designSystems = {
  default: {
    systemKey: "default",
    label: "Default",
    assetsBase: "/design-system/systems/default/assets",
    tokens: {
      accordionFrame: () => import("../systems/default/tokens/proofs/accordionFrame.tokens.mjs"),
      backgroundColor: () => import("../systems/default/tokens/proofs/backgroundColor.tokens.mjs"),
      bodyRegionFrame: () => import("../systems/default/tokens/proofs/bodyRegionFrame.tokens.mjs"),
      buttonFrame: () => import("../systems/default/tokens/proofs/buttonFrame.tokens.mjs"),
      choiceCardStateAffordance: () => import("../systems/default/tokens/proofs/choiceCardStateAffordance.tokens.mjs"),
      countCardFrame: () => import("../systems/default/tokens/proofs/countCardFrame.tokens.mjs"),
      dropdownListboxFrame: () => import("../systems/default/tokens/proofs/dropdownListboxFrame.tokens.mjs"),
      dropdownTriggerFrame: () => import("../systems/default/tokens/proofs/dropdownTriggerFrame.tokens.mjs"),
      dragDropAffordanceFrame: () => import("../systems/default/tokens/proofs/dragDropAffordanceFrame.tokens.mjs"),
      errorTextStyle: () => import("../systems/default/tokens/proofs/errorTextStyle.tokens.mjs"),
      focusRing: () => import("../systems/default/tokens/proofs/focusRing.tokens.mjs"),
      fieldContainerFrame: () => import("../systems/default/tokens/proofs/fieldContainerFrame.tokens.mjs"),
      fieldRowFrame: () => import("../systems/default/tokens/proofs/fieldRowFrame.tokens.mjs"),
      fieldValueTextStyle: () => import("../systems/default/tokens/proofs/fieldValueTextStyle.tokens.mjs"),
      iconSize: () => import("../systems/default/tokens/proofs/iconSize.tokens.mjs"),
      indexNavItemCurrentIndicator: () => import("../systems/default/tokens/proofs/indexNavItemCurrentIndicator.tokens.mjs"),
      indexNavItemGap: () => import("../systems/default/tokens/proofs/indexNavItemGap.tokens.mjs"),
      indexNavItemPadding: () => import("../systems/default/tokens/proofs/indexNavItemPadding.tokens.mjs"),
      indexNavItemRadius: () => import("../systems/default/tokens/proofs/indexNavItemRadius.tokens.mjs"),
      indexNavItemSurface: () => import("../systems/default/tokens/proofs/indexNavItemSurface.tokens.mjs"),
      supportingTextStyle: () => import("../systems/default/tokens/proofs/supportingTextStyle.tokens.mjs"),
      textControlFrame: () => import("../systems/default/tokens/proofs/textControlFrame.tokens.mjs"),
      textareaGrowth: () => import("../systems/default/tokens/proofs/textareaGrowth.tokens.mjs"),
      toggleFrame: () => import("../systems/default/tokens/proofs/toggleFrame.tokens.mjs"),
      indexNavListGap: () => import("../systems/default/tokens/proofs/indexNavListGap.tokens.mjs"),
      indexNavPanelFrame: () => import("../systems/default/tokens/proofs/indexNavPanelFrame.tokens.mjs"),
      scrollbarSkin: () => import("../systems/default/tokens/proofs/scrollbarSkin.tokens.mjs"),
      statusColor: () => import("../systems/default/tokens/proofs/statusColor.tokens.mjs"),
      labelTextStyle: () => import("../systems/default/tokens/proofs/labelTextStyle.tokens.mjs"),
      minimumTargetSize: () => import("../systems/default/tokens/proofs/minimumTargetSize.tokens.mjs"),
      panelCornerRadius: () => import("../systems/default/tokens/proofs/panelCornerRadius.tokens.mjs"),
      panelFrame: () => import("../systems/default/tokens/proofs/panelFrame.tokens.mjs"),
      panelHeaderFrame: () => import("../systems/default/tokens/proofs/panelHeaderFrame.tokens.mjs"),
      panelStackPlacement: () => import("../systems/default/tokens/proofs/panelStackPlacement.tokens.mjs"),
      pageHeaderStructure: () => import("../systems/default/tokens/proofs/pageHeaderStructure.tokens.mjs"),
      primaryColorSource: () => import("../systems/default/tokens/proofs/primaryColorSource.tokens.mjs"),
      primaryTintedBackground: () => import("../systems/default/tokens/proofs/primaryTintedBackground.tokens.mjs"),
      primaryTintedForeground: () => import("../systems/default/tokens/proofs/primaryTintedForeground.tokens.mjs"),
      resizeHandle: () => import("../systems/default/tokens/proofs/resizeHandle.tokens.mjs"),
      recordListItemFrame: () => import("../systems/default/tokens/proofs/recordListItemFrame.tokens.mjs"),
      tooltipSurface: () => import("../systems/default/tokens/proofs/tooltipSurface.tokens.mjs"),
      tooltipTextStyle: () => import("../systems/default/tokens/proofs/tooltipTextStyle.tokens.mjs"),
    },
  },
};

export function getDesignSystem(systemKey = "default") {
  return designSystems[systemKey] ?? null;
}
