export const errorTextStyleTokenContract = {
  schema: "kanbien.designSystem.tokenContract.v1",
  contractId: "tokens.error-text-style",
  tokenType: "error-text-style",
  requiredVariantRoles: ["field error text"],
  requiredThemes: ["all"],
  requiredVariantFields: ["id", "tokenName", "value", "preview", "metadata", "useCaseInstructions"],
  valueFields: [
    "textStyleRole",
    "fontFamilyValue",
    "fontFallbackRule",
    "fontSizeValue",
    "fontWeightValue",
    "lineHeightValue",
    "letterSpacingValue",
    "textTransform",
    "foregroundValue",
    "overflowReadiness",
    "zoomBehavior",
  ],
  metadataFields: ["textStyleRole", "theme", "state", "accessibility"],
  useCaseInstructionFields: ["allowedUse", "forbiddenUse", "overflowRule"],
  consumerRules: [
    "Consumers must use this token for field-row error text instead of local typography or color literals.",
    "Consumers must preserve the complete font fallback stack.",
    "This token does not define validation copy, invalid semantics, input frame color, focus behavior, or form submission.",
  ],
};
