export const contextNavigationItemAffordanceTokenContract = {
  schema: "kanbien.designSystem.tokenContract.v1",
  contractId: "tokens.context-navigation-item-affordance",
  tokenType: "context-navigation-item-affordance",
  requiredVariantRoles: ["context navigation item affordance"],
  requiredThemes: ["all"],
  requiredVariantFields: ["id", "tokenName", "value", "preview", "metadata", "useCaseInstructions"],
  valueFields: [
    "itemRole",
    "desktopInlineSize",
    "desktopBlockSize",
    "mobilePaddingBlockValue",
    "mobilePaddingInlineValue",
    "radiusValue",
    "restingBorderValue",
    "restingBackgroundValue",
    "restingForegroundValue",
    "hoverBorderValue",
    "hoverBackgroundValue",
    "hoverForegroundValue",
    "currentBorderValue",
    "currentBackgroundValue",
    "currentForegroundValue",
    "disabledOpacityValue",
  ],
  metadataFields: ["itemRole", "stateModel", "responsiveBehavior", "accessibility"],
  useCaseInstructionFields: ["allowedUse", "forbiddenUse", "proofRequirement"],
  consumerRules: [
    "Context-navigation item primitives must consume this token for item state affordance values instead of local CSS literals.",
    "Current state must pair visual affordance with programmatic current semantics such as aria-current.",
    "This token does not define icon artwork, label truncation, tooltip behavior, More-menu overflow, drawer behavior, or rail placement.",
  ],
};
