import { contextNavigationFrameTokenContract } from "../../../../layers/02-token/context-navigation-frame/contract.mjs";
import { standardPageShellFrameTokenSpec } from "./standardPageShellFrame.tokens.mjs";

const shellFrame = standardPageShellFrameTokenSpec.variants.find((variant) => variant.id === "standard-page-shell-frame-default");

if (!shellFrame) {
  throw new Error("context-navigation-frame requires the signed standard-page-shell-frame dependency.");
}

export const tokenTypeTemplate = {
  schema: "kanbien.designSystem.tokenTypeTemplate.v1",
  tokenType: "context-navigation-frame",
  previewKind: "context-navigation-frame-sample",
  variantSchema: {
    valueFields: [
      "frameRole",
      "desktopPositioningModel",
      "mobilePositioningModel",
      "desktopRailInlineSize",
      "desktopRailTopOffset",
      "desktopRailBottomOffset",
      "desktopRailGapValue",
      "desktopRailPaddingBlockValue",
      "desktopRailPaddingInlineValue",
      "desktopPrimaryScrollBehavior",
      "utilityZoneAnchorBehavior",
      "mobileBreakpoint",
      "mobileBarBlockOffset",
      "mobileBarInsetInlineStart",
      "mobileBarInsetInlineEnd",
      "mobileBarColumns",
      "mobileBarPaddingBlockStart",
      "mobileBarPaddingInline",
      "mobileBarPaddingBlockEnd",
      "mobilePageBottomReserve",
      "mobileDrawerBottomOffset",
      "mobileViewportPinningBehavior",
      "mobileScrollBoundaryBehavior",
      "surfaceValue",
      "borderValue",
      "shadowValue",
    ],
    metadataFields: ["frameRole", "responsiveBehavior", "scrollBehavior", "accessibility"],
    useCaseInstructionFields: ["allowedUse", "forbiddenUse", "proofRequirement"],
  },
};

export const tokenDefinitionV1 = {
  schema: "kanbien.designSystem.tokenDefinition.v1",
  contractScope: "shared",
  designSystem: "default",
  uiFamily: "context-navigation",
  tokenType: "context-navigation-frame",
  status: "review-ready",
  behaviorRulePath: "docs/design-system/01-behavior-rule/shared/context-navigation/ContextNavigation-Behaviour.md",
  tokenContractPath: "docs/design-system/02-token/shared/context-navigation-frame/ContextNavigationFrame-Contract.md",
  tokenDefinitionPath: "docs/design-system/02-token/systems/default/context-navigation-frame/ContextNavigationFrame-Implementation.md",
  page: {
    route: "/design-system/default/tokens/context-navigation-frame",
    htmlPath: "src/frontend/designSystem/systems/default/tokens/context-navigation-frame/index.html",
    title: "Context Navigation Frame Token",
    description:
      "Review governed context-navigation frame values before rail, bottom-bar, drawer, or shell-navigation patterns consume them.",
  },
  codeSeam: {
    contractModule: "src/frontend/designSystem/layers/02-token/context-navigation-frame/contract.mjs",
    contractExport: "contextNavigationFrameTokenContract",
    governedRuntimeModule: "src/frontend/designSystem/layers/02-token/context-navigation-frame/systems/default.mjs",
    systemProofModule: "src/frontend/designSystem/systems/default/tokens/proofs/contextNavigationFrame.tokens.mjs",
    systemTokenExport: "contextNavigationFrameTokenSpec",
    rendererModule: "src/frontend/designSystem/shared/renderers/renderTokenSpecPage.mjs",
    rendererExport: "renderTokenSpecPage",
    allowedConsumers: ["03-primitive", "04-pattern-contract", "05-component-seam"],
  },
  dependencies: [
    {
      contractId: "tokens.standard-page-shell-frame",
      variantId: shellFrame.id,
      tokenName: shellFrame.tokenName,
      value: "context rail 4.25rem / mobile bottom inset 5.75rem",
      relationship: "paired-with",
    },
  ],
  diagnostic: {
    kind: "none",
    rule: "No diagnostic override is approved; browser proof must verify pinned mobile behavior with signed values.",
  },
  variants: [
    {
      id: "context-navigation-frame-default",
      tokenName: "--context-navigation-frame",
      value: {
        frameRole: "context navigation frame",
        desktopPositioningModel: "fixed rail from combined shell chrome bottom to viewport bottom",
        mobilePositioningModel: "fixed bottom bar pinned to visual viewport bottom",
        desktopRailInlineSize: "4.25rem",
        desktopRailTopOffset: "var(--context-nav-top, 8rem)",
        desktopRailBottomOffset: "0",
        desktopRailGapValue: "0.55rem",
        desktopRailPaddingBlockValue: "0.75rem",
        desktopRailPaddingInlineValue: "0.5rem",
        desktopPrimaryScrollBehavior: "primary zone flexes and scrolls with overscroll-behavior: contain",
        utilityZoneAnchorBehavior: "bottom utility zone remains anchored with margin-top: auto",
        mobileBreakpoint: "44rem",
        mobileBarBlockOffset: "0",
        mobileBarInsetInlineStart: "0",
        mobileBarInsetInlineEnd: "0",
        mobileBarColumns: "repeat(5, minmax(0, 1fr))",
        mobileBarPaddingBlockStart: "0.55rem",
        mobileBarPaddingInline: "0.5rem",
        mobileBarPaddingBlockEnd: "calc(0.55rem + env(safe-area-inset-bottom, 0))",
        mobilePageBottomReserve: "5.75rem",
        mobileDrawerBottomOffset: "calc(4.125rem + env(safe-area-inset-bottom, 0))",
        mobileViewportPinningBehavior: "bottom bar remains fixed to the visual viewport bottom during document scroll and page-end pressure",
        mobileScrollBoundaryBehavior: "document scroll must not move the bottom bar; any page-end overscroll must not expose content below the bar",
        surfaceValue: "var(--surface-2)",
        borderValue: "0.0625rem solid var(--line)",
        shadowValue: "0 -0.75rem 1.875rem rgba(38, 48, 86, 0.08)",
      },
      derivation: {
        sourceTokenName: `${shellFrame.tokenName} + 40-system context-nav CSS`,
        sourceValue: "src/frontend/designSystem/assets/styles.css",
        formulaOrMapping:
          "Rail size, bottom bar columns, padding, page reserve, and drawer offset are lifted from existing context-nav CSS; viewport pinning is promoted from observed defect into a token invariant.",
        renderedValue:
          "desktop fixed rail 4.25rem / mobile fixed bottom bar / mobile page reserve 5.75rem / mobile drawer offset calc(4.125rem + env(safe-area-inset-bottom, 0))",
      },
      preview: {
        kind: "context-navigation-frame-sample",
        sample: "Context navigation frame",
        background: "var(--surface-2)",
        foreground: "var(--text)",
        border: "0.0625rem solid var(--line)",
        radius: "0",
      },
      metadata: {
        frameRole: "context navigation frame",
        responsiveBehavior:
          "desktop uses fixed side rail; mobile uses fixed bottom bar with reserved page-bottom space and drawer offset above the bar",
        scrollBehavior: "desktop primary zone owns internal overflow; mobile bar remains viewport-pinned and does not scroll with page content",
        accessibility: "Context navigation must remain reachable and visible at page top, page middle, page bottom, zoom, mobile safe-area, and RTL.",
      },
      useCaseInstructions: [
        "Use for context-navigation primitives and patterns that place the desktop rail, primary scroll zone, utility zone, mobile bottom bar, and mobile drawer offset.",
        "Do not use for destination item anatomy, active-state treatment, More-menu behavior, tooltip behavior, drawer payloads, component props, or app-local CSS.",
        "Browser proof must verify the mobile bottom bar stays pinned at scroll top, middle, and bottom before downstream adoption.",
      ],
    },
  ],
};

export const variants = tokenDefinitionV1.variants;

function toPageVariant(variant) {
  return {
    id: variant.id,
    tokenName: variant.tokenName,
    tokenValue: variant.derivation.renderedValue,
    frameRole: variant.value.frameRole,
    desktopPositioningModel: variant.value.desktopPositioningModel,
    mobilePositioningModel: variant.value.mobilePositioningModel,
    desktopRailInlineSize: variant.value.desktopRailInlineSize,
    desktopRailTopOffset: variant.value.desktopRailTopOffset,
    desktopRailBottomOffset: variant.value.desktopRailBottomOffset,
    desktopRailGapValue: variant.value.desktopRailGapValue,
    desktopRailPaddingBlockValue: variant.value.desktopRailPaddingBlockValue,
    desktopRailPaddingInlineValue: variant.value.desktopRailPaddingInlineValue,
    desktopPrimaryScrollBehavior: variant.value.desktopPrimaryScrollBehavior,
    utilityZoneAnchorBehavior: variant.value.utilityZoneAnchorBehavior,
    mobileBreakpoint: variant.value.mobileBreakpoint,
    mobileBarBlockOffset: variant.value.mobileBarBlockOffset,
    mobileBarInsetInlineStart: variant.value.mobileBarInsetInlineStart,
    mobileBarInsetInlineEnd: variant.value.mobileBarInsetInlineEnd,
    mobileBarColumns: variant.value.mobileBarColumns,
    mobileBarPaddingBlockStart: variant.value.mobileBarPaddingBlockStart,
    mobileBarPaddingInline: variant.value.mobileBarPaddingInline,
    mobileBarPaddingBlockEnd: variant.value.mobileBarPaddingBlockEnd,
    mobilePageBottomReserve: variant.value.mobilePageBottomReserve,
    mobileDrawerBottomOffset: variant.value.mobileDrawerBottomOffset,
    mobileViewportPinningBehavior: variant.value.mobileViewportPinningBehavior,
    mobileScrollBoundaryBehavior: variant.value.mobileScrollBoundaryBehavior,
    surfaceValue: variant.value.surfaceValue,
    borderValue: variant.value.borderValue,
    shadowValue: variant.value.shadowValue,
    sourceTokenName: variant.derivation.sourceTokenName,
    sourceValue: variant.derivation.sourceValue,
    formulaOrMapping: variant.derivation.formulaOrMapping,
    theme: "all",
    accessibility: variant.metadata.accessibility,
    responsiveBehavior: variant.metadata.responsiveBehavior,
    scrollBehavior: variant.metadata.scrollBehavior,
    preview: variant.preview,
    usage: [
      { label: "Allowed", text: variant.useCaseInstructions[0] },
      { label: "Denied", text: variant.useCaseInstructions[1] },
      { label: "Proof", text: variant.useCaseInstructions[2] },
    ],
  };
}

export const contextNavigationFrameTokenVariants = variants.map(toPageVariant);

export const contextNavigationFrameTokenSpec = {
  contractId: contextNavigationFrameTokenContract.contractId,
  systemKey: tokenDefinitionV1.designSystem,
  tokenType: "context-navigation-frame",
  title: tokenDefinitionV1.page.title,
  description: tokenDefinitionV1.page.description,
  variantSectionDescription: "This variant governs context-navigation rail, mobile bottom-bar, drawer-offset, and scroll-boundary values.",
  tokenTypeTemplate,
  summaryPanels: [
    {
      label: "Context navigation",
      title: "Pinned rail and mobile bottom bar",
      variantId: "context-navigation-frame-default",
      supportingText: "The proof separates desktop rail scroll ownership from the mobile bottom bar's viewport-pinned behavior.",
    },
  ],
  variantFields: [
    ["frameRole", "Role"],
    ["desktopPositioningModel", "Desktop positioning"],
    ["mobilePositioningModel", "Mobile positioning"],
    ["desktopRailInlineSize", "Desktop rail width"],
    ["desktopRailTopOffset", "Desktop rail top"],
    ["desktopRailBottomOffset", "Desktop rail bottom"],
    ["desktopRailGapValue", "Desktop rail gap"],
    ["desktopRailPaddingBlockValue", "Desktop block padding"],
    ["desktopRailPaddingInlineValue", "Desktop inline padding"],
    ["desktopPrimaryScrollBehavior", "Desktop primary scroll"],
    ["utilityZoneAnchorBehavior", "Utility anchor"],
    ["mobileBreakpoint", "Mobile breakpoint"],
    ["mobileBarBlockOffset", "Mobile bar bottom"],
    ["mobileBarInsetInlineStart", "Mobile inline start"],
    ["mobileBarInsetInlineEnd", "Mobile inline end"],
    ["mobileBarColumns", "Mobile columns"],
    ["mobileBarPaddingBlockStart", "Mobile block start padding"],
    ["mobileBarPaddingInline", "Mobile inline padding"],
    ["mobileBarPaddingBlockEnd", "Mobile block end padding"],
    ["mobilePageBottomReserve", "Mobile page reserve"],
    ["mobileDrawerBottomOffset", "Mobile drawer bottom"],
    ["mobileViewportPinningBehavior", "Mobile viewport pinning"],
    ["mobileScrollBoundaryBehavior", "Mobile scroll boundary"],
    ["surfaceValue", "Surface"],
    ["borderValue", "Border"],
    ["shadowValue", "Shadow"],
    ["sourceTokenName", "Source"],
    ["sourceValue", "Source file"],
    ["formulaOrMapping", "Formula or mapping"],
  ],
  variants: contextNavigationFrameTokenVariants,
  consumerRestrictions: [
    "Consumers must import this token seam instead of hard-coding context rail widths, bottom-bar columns, bottom offsets, page-bottom reserve, drawer offsets, scroll containment, or viewport pinning behavior.",
    "The mobile bottom bar must remain fixed to the visual viewport bottom and must not participate in document scroll or page-end overscroll.",
    "This token does not approve destination item anatomy, active-state treatment, More-menu behavior, drawer payload behavior, component seams, or app adoption.",
  ],
  requiredEvidence: [
    "Rendered proof must show desktop rail and mobile bottom-bar frame regions.",
    "Layer 3 context-navigation primitives must consume this token before owning rail or bottom-bar markup.",
    "Browser proof must verify the mobile bottom bar stays pinned at scroll top, middle, and bottom before downstream adoption.",
  ],
};
