import { indexNavPanelFrameTokenContract } from "../../../../layers/02-token/index-nav-panel-frame/contract.mjs";

export const tokenTypeTemplate = {
  schema: "kanbien.designSystem.tokenTypeTemplate.v1",
  tokenType: "index-nav-panel-frame",
  previewKind: "surface-card",
  variantSchema: {
    valueFields: [
      "frameRole",
      "backgroundValue",
      "foregroundValue",
      "borderValue",
      "radiusValue",
      "paddingBlockValue",
      "paddingInlineValue",
      "gapValue",
      "minInlineSize",
      "standardInlineSize",
      "doubleInlineSize",
      "maxInlineSize",
      "mobileInlineSize",
      "mobileBreakpointValue",
      "maxBlockSize",
      "blockSize",
      "minBlockSize",
      "maxBlockSizeValue",
      "stickyInsetBlockStart",
      "scrollBehavior",
    ],
    metadataFields: ["frameRole", "responsiveBehavior", "scrollBehavior", "accessibility"],
    useCaseInstructionFields: ["allowedUse", "forbiddenUse", "responsiveBehavior"],
  },
};

export const tokenDefinitionV1 = {
  schema: "kanbien.designSystem.tokenDefinition.v1",
  contractScope: "shared",
  designSystem: "default",
  uiFamily: "index-nav",
  tokenType: "index-nav-panel-frame",
  status: "review-ready",
  behaviorRulePath: "docs/design-system/01-behavior-rule/shared/index-navigation/IndexNavigation-Behaviour.md",
  tokenContractPath: "docs/design-system/02-token/shared/index-nav-panel-frame/IndexNavPanelFrame-Contract.md",
  tokenDefinitionPath: "docs/design-system/02-token/systems/default/index-nav-panel-frame/IndexNavPanelFrame-Implementation.md",
  page: {
    route: "/design-system/default/tokens/index-nav-panel-frame",
    htmlPath: "src/frontend/designSystem/systems/default/tokens/index-nav-panel-frame/index.html",
    title: "Index Nav Panel Frame Token",
    description: "Review governed panel container, scroll, and add-action frame values for index navigation.",
  },
  codeSeam: {
    contractModule: "src/frontend/designSystem/layers/02-token/index-nav-panel-frame/contract.mjs",
    contractExport: "indexNavPanelFrameTokenContract",
    governedRuntimeModule: "src/frontend/designSystem/layers/02-token/index-nav-panel-frame/systems/default.mjs",
    systemProofModule: "src/frontend/designSystem/systems/default/tokens/proofs/indexNavPanelFrame.tokens.mjs",
    systemTokenExport: "indexNavPanelFrameTokenSpec",
    rendererModule: "src/frontend/designSystem/shared/renderers/renderTokenSpecPage.mjs",
    rendererExport: "renderTokenSpecPage",
    allowedConsumers: ["03-primitive", "04-pattern-contract"],
  },
  variants: [
    {
      id: "index-nav-panel-frame-default",
      tokenName: "--index-nav-panel-frame",
      value: {
        frameRole: "panel frame",
        backgroundValue: "#ffffff",
        foregroundValue: "#111827",
        borderValue: "#dbe4f0",
        radiusValue: "0.5rem",
        paddingBlockValue: "0.5rem",
        paddingInlineValue: "0.5rem",
        gapValue: "0.75rem",
        minInlineSize: "10rem",
        standardInlineSize: "13rem",
        doubleInlineSize: "26rem",
        maxInlineSize: "32rem",
        mobileInlineSize: "100vw",
        mobileBreakpointValue: "44rem",
        maxBlockSize: "32rem",
        scrollBehavior: "desktop panel owns internal list scrolling; mobile panel expands to screen width and scrolls with page",
      },
      derivation: {
        sourceTokenName: "none",
        sourceValue: "default index-nav panel values",
        formulaOrMapping: "system implementation value",
        renderedValue: "10rem min / 13rem standard / 26rem double / 32rem max / 100vw below 44rem",
      },
      preview: {
        kind: "surface-card",
        sample: "Index panel",
        background: "#ffffff",
        foreground: "#111827",
        border: "#dbe4f0",
        label: "Panel frame",
      },
      metadata: {
        frameRole: "panel frame",
        responsiveBehavior: "resizable desktop width between min and max limits; single width, optional double width, and mobile full-screen inline size below the governed mobile breakpoint",
        scrollBehavior: "desktop scroll region is internal; mobile uses document scroll",
        accessibility: "Scroll ownership must not trap keyboard focus or hide list items from normal navigation.",
      },
      useCaseInstructions: [
        "Use for the index-nav panel container around one or two index lists.",
        "Do not use for item surfaces, cards, page shells, or app-local sidebars.",
        "Mobile full-screen behavior belongs to the panel pattern using this token, not to the list pattern.",
      ],
    },
    {
      id: "index-nav-panel-header-default",
      tokenName: "--index-nav-panel-header-frame",
      value: {
        frameRole: "panel header",
        backgroundValue: "inherit",
        foregroundValue: "inherit",
        borderValue: "#dbe4f0",
        radiusValue: "0",
        paddingBlockValue: "0",
        paddingInlineValue: "0",
        gapValue: "0.75rem",
        minInlineSize: "0",
        standardInlineSize: "auto",
        doubleInlineSize: "auto",
        maxInlineSize: "100%",
        mobileInlineSize: "100%",
        mobileBreakpointValue: "44rem",
        maxBlockSize: "none",
        blockSize: "3.25rem",
        minBlockSize: "3.25rem",
        maxBlockSizeValue: "3.25rem",
        stickyInsetBlockStart: "0",
        scrollBehavior: "header remains fixed-height and sticky at the top of the panel scroll context",
      },
      derivation: {
        sourceTokenName: "minimum-target-size + index-nav-panel-frame",
        sourceValue: "2.75rem interactive target height; #dbe4f0 panel border",
        formulaOrMapping: "minimum target height plus 0.25rem block breathing room on each side; separator inherits the panel border value",
        renderedValue: "3.25rem fixed header height with panel-border separator",
      },
      preview: {
        kind: "surface-card",
        sample: "Primary index",
        background: "#ffffff",
        foreground: "#111827",
        border: "#dbe4f0",
        label: "Panel header",
      },
      metadata: {
        frameRole: "panel header",
        responsiveBehavior: "fixed block size across item counts and viewport modes; sticky within the panel scroll context",
        scrollBehavior: "sticky header belongs to the panel header primitive; scrollbar appearance remains browser-native unless a future scrollbar token is signed",
        accessibility: "Header height must not reduce the icon button target below the signed minimum target size.",
      },
      useCaseInstructions: [
        "Use for index-nav panel header height, title/action alignment, and sticky top inset.",
        "Do not use for list items, page headers, app-local sidebars, or arbitrary toolbar rows.",
        "Pair with the governed icon-button primitive when an add action is present.",
      ],
    },
    {
      id: "index-nav-panel-action-default",
      tokenName: "--index-nav-panel-action-frame",
      value: {
        frameRole: "panel action",
        backgroundValue: "color-mix(in srgb, #4f46e5 10%, #ffffff)",
        foregroundValue: "#312e81",
        borderValue: "color-mix(in srgb, #4f46e5 28%, #dbe4f0)",
        radiusValue: "0.375rem",
        paddingBlockValue: "0.35rem",
        paddingInlineValue: "0.55rem",
        gapValue: "0.25rem",
        minInlineSize: "auto",
        standardInlineSize: "auto",
        doubleInlineSize: "auto",
        maxInlineSize: "auto",
        mobileInlineSize: "auto",
        mobileBreakpointValue: "not applicable",
        maxBlockSize: "none",
        scrollBehavior: "not applicable to action control",
      },
      derivation: {
        sourceTokenName: "primary-color-source",
        sourceValue: "#4f46e5",
        formulaOrMapping: "primary source mixed into action surface and border",
        renderedValue: "tinted action surface",
      },
      preview: {
        kind: "surface-card",
        sample: "Add",
        background: "color-mix(in srgb, #4f46e5 10%, #ffffff)",
        foreground: "#312e81",
        border: "color-mix(in srgb, #4f46e5 28%, #dbe4f0)",
        label: "Panel action",
      },
      metadata: {
        frameRole: "panel action",
        responsiveBehavior: "uses target-size primitive sizing rather than panel width",
        scrollBehavior: "not applicable",
        accessibility: "Action contrast and focus visibility must be verified in the consuming primitive.",
      },
      useCaseInstructions: [
        "Use for the index-nav add action frame.",
        "Do not use for destructive, navigation, or item-current state actions.",
        "Pair with minimum-target-size and focus-ring in the action primitive.",
      ],
    },
  ],
};

export const variants = tokenDefinitionV1.variants;

function toPageVariant(variant) {
  return {
    id: variant.id,
    tokenName: variant.tokenName,
    tokenValue: variant.derivation.renderedValue,
    frameRole: variant.value.frameRole,
    backgroundValue: variant.value.backgroundValue,
    foregroundValue: variant.value.foregroundValue,
    borderValue: variant.value.borderValue,
    radiusValue: variant.value.radiusValue,
    paddingBlockValue: variant.value.paddingBlockValue,
    paddingInlineValue: variant.value.paddingInlineValue,
    gapValue: variant.value.gapValue,
    minInlineSize: variant.value.minInlineSize,
    standardInlineSize: variant.value.standardInlineSize,
    doubleInlineSize: variant.value.doubleInlineSize,
    maxInlineSize: variant.value.maxInlineSize,
    mobileInlineSize: variant.value.mobileInlineSize,
    mobileBreakpointValue: variant.value.mobileBreakpointValue,
    maxBlockSize: variant.value.maxBlockSize,
    blockSize: variant.value.blockSize,
    minBlockSize: variant.value.minBlockSize,
    maxBlockSizeValue: variant.value.maxBlockSizeValue,
    stickyInsetBlockStart: variant.value.stickyInsetBlockStart,
    scrollBehavior: variant.value.scrollBehavior,
    sourceTokenName: variant.derivation.sourceTokenName,
    formulaOrMapping: variant.derivation.formulaOrMapping,
    theme: "all",
    accessibility: variant.metadata.accessibility,
    preview: variant.preview,
    usage: [
      { label: "Allowed", text: variant.useCaseInstructions[0] },
      { label: "Denied", text: variant.useCaseInstructions[1] },
      { label: "Responsive", text: variant.useCaseInstructions[2] },
    ],
  };
}

export const indexNavPanelFrameTokenVariants = variants.map(toPageVariant);

export const indexNavPanelFrameTokenSpec = {
  contractId: indexNavPanelFrameTokenContract.contractId,
  systemKey: tokenDefinitionV1.designSystem,
  tokenType: "index-nav-panel-frame",
  title: tokenDefinitionV1.page.title,
  description: tokenDefinitionV1.page.description,
  variantSectionDescription: "These variants govern the index-nav panel frame, header frame, and add-action frame.",
  tokenTypeTemplate,
  summaryPanels: [
    {
      label: "Panel",
      title: "Single and double width",
      variantId: "index-nav-panel-frame-default",
      supportingText: "Panel width and scroll ownership are tokenized before panel composition.",
    },
    {
      label: "Header",
      title: "Fixed sticky header",
      variantId: "index-nav-panel-header-default",
      supportingText: "Header height and sticky inset are tokenized before the panel pattern uses them.",
    },
    {
      label: "Action",
      title: "Add action frame",
      variantId: "index-nav-panel-action-default",
      supportingText: "Action appearance is tokenized before the add primitive consumes it.",
    },
  ],
  variantFields: [
    ["frameRole", "Role"],
    ["minInlineSize", "Min width"],
    ["standardInlineSize", "Standard width"],
    ["doubleInlineSize", "Double width"],
    ["maxInlineSize", "Max width"],
    ["mobileInlineSize", "Mobile width"],
    ["mobileBreakpointValue", "Mobile breakpoint"],
    ["maxBlockSize", "Desktop max height"],
    ["blockSize", "Header height"],
    ["minBlockSize", "Header min height"],
    ["maxBlockSizeValue", "Header max height"],
    ["stickyInsetBlockStart", "Sticky top"],
    ["scrollBehavior", "Scroll behavior"],
    ["formulaOrMapping", "Formula or mapping"],
  ],
  variants: indexNavPanelFrameTokenVariants,
  diagnostic: {
    kind: "inline-size-range",
    kicker: "Diagnostic override",
    label: "Review Desktop Resize Limits",
    description: "Drag within the signed minimum and maximum panel widths. This changes only the rendered review sample.",
    inputLabel: "Panel width",
    sourceVariantId: "index-nav-panel-frame-default",
    minField: "minInlineSize",
    maxField: "maxInlineSize",
    defaultField: "standardInlineSize",
    previewLabel: "Resizable panel preview",
    statusPrefix: "Rendered review width",
  },
  consumerRestrictions: [
    "Consumers must import this token seam instead of hard-coding index-nav panel width, breakpoint, padding, surface, radius, or scroll height.",
    "The panel frame token does not approve list item behavior, route selection, or app adoption.",
    "Proof-only width controls may test single and double width, but downstream consumers must use the token variants.",
  ],
  requiredEvidence: [
    "Rendered proof must show single width, double width, and mobile full-width behavior from the governed breakpoint without horizontal overflow.",
    "Panel scroll behavior must be verified in a Layer 4 browser proof.",
    "The panel header and add action must consume this token through governed primitives before the panel pattern uses them.",
  ],
};
