import { menuSimpleSelectFrameTokenContract } from "../../../../layers/02-token/menu-simple-select-frame/contract.mjs";

export const tokenTypeTemplate = {
  schema: "kanbien.designSystem.tokenTypeTemplate.v1",
  tokenType: "menu-simple-select-frame",
  previewKind: "surface-card",
  variantSchema: {
    valueFields: [
      "frameRole",
      "backgroundValue",
      "foregroundValue",
      "supportingForegroundValue",
      "iconForegroundValue",
      "borderValue",
      "radiusValue",
      "paddingBlockValue",
      "paddingInlineValue",
      "gapValue",
      "minBlockSize",
      "minInlineSize",
      "maxInlineSize",
      "maxBlockSize",
      "zIndexValue",
      "scrollBehavior",
    ],
    metadataFields: ["frameRole", "theme", "state", "accessibility"],
    useCaseInstructionFields: ["allowedUse", "forbiddenUse", "proofRequirement"],
  },
};

const themeValues = {
  original: {
    surface: "#ffffff",
    foreground: "#111827",
    supportingForeground: "#64748b",
    iconForeground: "#008575",
    border: "#d6deeb",
    currentSurface: "#e4f4f1",
    currentBorder: "#77c2b6",
    disabledSurface: "#f8fafc",
    disabledForeground: "#64748b",
    disabledBorder: "#e2e8f0",
  },
  dark: {
    surface: "#171b22",
    foreground: "#f4f7fb",
    supportingForeground: "#a8b5c7",
    iconForeground: "#5eead4",
    border: "#334155",
    currentSurface: "#123c3a",
    currentBorder: "#5eead4",
    disabledSurface: "#111827",
    disabledForeground: "#94a3b8",
    disabledBorder: "#334155",
  },
  desert: {
    surface: "#fffaf0",
    foreground: "#493327",
    supportingForeground: "#7a6652",
    iconForeground: "#0f766e",
    border: "#decfb8",
    currentSurface: "#f0ead2",
    currentBorder: "#a38b5f",
    disabledSurface: "#f7eddc",
    disabledForeground: "#7a6652",
    disabledBorder: "#decfb8",
  },
};

function themedId(baseId, theme) {
  return theme === "original" ? baseId : `${baseId}-${theme}`;
}

function variantsForTheme(theme) {
  const values = themeValues[theme];
  const themeLabel = theme === "original" ? "original" : `${theme} theme`;

  return [
    {
      id: themedId("menu-simple-select-trigger-frame-default", theme),
      tokenName: `--menu-simple-select-trigger-frame-${theme}`,
      value: {
        frameRole: "trigger frame",
        backgroundValue: values.surface,
        foregroundValue: values.foreground,
        supportingForegroundValue: values.supportingForeground,
        iconForegroundValue: values.iconForeground,
        borderValue: values.border,
        radiusValue: "0.375rem",
        paddingBlockValue: "0.5rem",
        paddingInlineValue: "0.75rem",
        gapValue: "0.5rem",
        minBlockSize: "2.75rem",
        minInlineSize: "10rem",
        maxInlineSize: "18rem",
        maxBlockSize: "none",
        zIndexValue: "auto",
        scrollBehavior: "not applicable to closed trigger",
      },
      derivation: {
        sourceTokenName: "background-color + minimum-target-size",
        sourceValue: `${values.surface} ${themeLabel} surface; 2.75rem minimum target`,
        formulaOrMapping: "surface and target size are paired with select-specific border, radius, and inline padding",
        renderedValue: "2.75rem minimum text trigger with compact header-friendly inline padding",
      },
      preview: {
        kind: "menu-simple-select-trigger-sample",
        frameRole: "trigger frame",
        labelText: "Layer",
        valueText: "Current",
        sample: "Layer Current",
        background: values.surface,
        foreground: values.foreground,
        supportingForeground: values.supportingForeground,
        iconForeground: values.iconForeground,
        border: values.border,
        radius: "0.375rem",
        paddingBlock: "0.5rem",
        paddingInline: "0.75rem",
        gap: "0.5rem",
        minBlockSize: "2.75rem",
        minInlineSize: "10rem",
        maxInlineSize: "18rem",
        label: `Text trigger ${theme}`,
      },
      metadata: {
        frameRole: "trigger frame",
        theme,
        state: "closed",
        accessibility: "Text trigger sizing must preserve the signed minimum target size and visible focus ring.",
      },
      useCaseInstructions: [
        "Use for compact text-backed menu-simple-select triggers in headers and toolbars.",
        "Do not use for icon-only triggers, text inputs, drawer selects, command menus, or app-local cards.",
        "Primitive proof must verify focus, accessible name, and current-value reflection.",
      ],
    },
    {
      id: themedId("menu-simple-select-trigger-frame-icon", theme),
      tokenName: `--menu-simple-select-trigger-frame-icon-${theme}`,
      value: {
        frameRole: "icon trigger frame",
        backgroundValue: values.surface,
        foregroundValue: values.foreground,
        supportingForegroundValue: values.supportingForeground,
        iconForegroundValue: values.iconForeground,
        borderValue: values.border,
        radiusValue: "0.375rem",
        paddingBlockValue: "0",
        paddingInlineValue: "0",
        gapValue: "0",
        minBlockSize: "2.75rem",
        minInlineSize: "2.75rem",
        maxInlineSize: "2.75rem",
        maxBlockSize: "none",
        zIndexValue: "auto",
        scrollBehavior: "not applicable to closed icon trigger",
      },
      derivation: {
        sourceTokenName: "background-color + minimum-target-size",
        sourceValue: `${values.surface} ${themeLabel} surface; 2.75rem square target`,
        formulaOrMapping: "icon-only trigger uses the same surface language with a square target footprint",
        renderedValue: "2.75rem square icon-only trigger",
      },
      preview: {
        kind: "menu-simple-select-trigger-sample",
        frameRole: "icon trigger frame",
        labelText: "",
        valueText: "",
        sample: "Chevron",
        background: values.surface,
        foreground: values.foreground,
        supportingForeground: values.supportingForeground,
        iconForeground: values.iconForeground,
        border: values.border,
        radius: "0.375rem",
        paddingBlock: "0",
        paddingInline: "0",
        gap: "0",
        minBlockSize: "2.75rem",
        minInlineSize: "2.75rem",
        maxInlineSize: "2.75rem",
        label: `Icon trigger ${theme}`,
      },
      metadata: {
        frameRole: "icon trigger frame",
        theme,
        state: "closed",
        accessibility: "Icon-only trigger must preserve an accessible name that includes the control label and current value.",
      },
      useCaseInstructions: [
        "Use for square icon-only menu-simple-select triggers where visible text is supplied by surrounding context.",
        "Do not use without an accessible label and current-value announcement.",
        "Primitive proof must verify square geometry and accessible trigger naming.",
      ],
    },
    {
      id: themedId("menu-simple-select-panel-frame-default", theme),
      tokenName: `--menu-simple-select-panel-frame-${theme}`,
      value: {
        frameRole: "menu panel",
        backgroundValue: values.surface,
        foregroundValue: values.foreground,
        supportingForegroundValue: values.supportingForeground,
        iconForegroundValue: values.iconForeground,
        borderValue: values.border,
        radiusValue: "0.375rem",
        paddingBlockValue: "0.375rem",
        paddingInlineValue: "0.375rem",
        gapValue: "0.25rem",
        minBlockSize: "auto",
        minInlineSize: "18rem",
        maxInlineSize: "20rem",
        maxBlockSize: "32rem",
        zIndexValue: "20",
        scrollBehavior: "anchored panel owns internal option scrolling when options exceed max block size",
      },
      derivation: {
        sourceTokenName: "background-color",
        sourceValue: `${values.surface} ${themeLabel} surface`,
        formulaOrMapping: "menu panel uses the matching theme surface with select-specific padding, radius, max height, and stacking",
        renderedValue: "18rem minimum / 20rem maximum inline size / 32rem maximum block size / z-index 20",
      },
      preview: {
        kind: "surface-card",
        sample: "Anchored menu",
        background: values.surface,
        foreground: values.foreground,
        border: values.border,
        radius: "0.375rem",
        label: `Menu panel ${theme}`,
      },
      metadata: {
        frameRole: "menu panel",
        theme,
        state: "open",
        accessibility: "Panel scrolling must not hide focused options or trap keyboard users; the open panel must paint above adjacent content.",
      },
      useCaseInstructions: [
        "Use for the anchored option panel opened by menu-simple-select triggers.",
        "Do not use for modals, drawers, popovers with arbitrary content, or long virtualized lists.",
        "Pattern proof must verify constrained-height internal scrolling.",
      ],
    },
    {
      id: themedId("menu-simple-select-option-frame-rest", theme),
      tokenName: `--menu-simple-select-option-frame-rest-${theme}`,
      value: {
        frameRole: "option item",
        backgroundValue: values.surface,
        foregroundValue: values.foreground,
        supportingForegroundValue: values.supportingForeground,
        iconForegroundValue: values.iconForeground,
        borderValue: values.border,
        radiusValue: "0.375rem",
        paddingBlockValue: "0.625rem",
        paddingInlineValue: "0.75rem",
        gapValue: "0.25rem",
        minBlockSize: "4.5rem",
        minInlineSize: "0",
        maxInlineSize: "100%",
        maxBlockSize: "none",
        zIndexValue: "auto",
        scrollBehavior: "not applicable to individual option",
      },
      derivation: {
        sourceTokenName: "background-color",
        sourceValue: `${values.surface} ${themeLabel} surface`,
        formulaOrMapping: "option item uses matching theme surface with row padding for short menu choices",
        renderedValue: "4.5rem minimum option card height",
      },
      preview: {
        kind: "surface-card",
        sample: "Chats",
        background: values.surface,
        foreground: values.foreground,
        border: values.border,
        radius: "0.375rem",
        label: `Option rest ${theme}`,
      },
      metadata: {
        frameRole: "option item",
        theme,
        state: "rest",
        accessibility: "Resting options must keep visible text contrast and target size.",
      },
      useCaseInstructions: [
        "Use for enabled menu-simple-select options that are not current or disabled.",
        "Do not use as selected/current, disabled, warning, error, or validation state.",
        "Primitive proof must verify keyboard traversal lands on enabled options.",
      ],
    },
    {
      id: themedId("menu-simple-select-option-frame-current", theme),
      tokenName: `--menu-simple-select-option-frame-current-${theme}`,
      value: {
        frameRole: "current option item",
        backgroundValue: values.currentSurface,
        foregroundValue: values.foreground,
        supportingForegroundValue: values.supportingForeground,
        iconForegroundValue: values.iconForeground,
        borderValue: values.currentBorder,
        radiusValue: "0.375rem",
        paddingBlockValue: "0.625rem",
        paddingInlineValue: "0.75rem",
        gapValue: "0.25rem",
        minBlockSize: "4.5rem",
        minInlineSize: "0",
        maxInlineSize: "100%",
        maxBlockSize: "none",
        zIndexValue: "auto",
        scrollBehavior: "not applicable to individual option",
      },
      derivation: {
        sourceTokenName: "primary-tinted-background",
        sourceValue: `${values.currentSurface} ${themeLabel} current surface`,
        formulaOrMapping: "current option uses a low-emphasis selected surface and stronger border; semantic current state must also be programmatic",
        renderedValue: `${values.currentSurface} current surface with ${values.currentBorder} border`,
      },
      preview: {
        kind: "surface-card",
        sample: "Organizations",
        background: values.currentSurface,
        foreground: values.foreground,
        border: values.currentBorder,
        radius: "0.375rem",
        label: `Current option ${theme}`,
      },
      metadata: {
        frameRole: "current option item",
        theme,
        state: "current",
        accessibility: "Current meaning must be paired with aria-selected or equivalent primitive semantics; color cannot be the only carrier.",
      },
      useCaseInstructions: [
        "Use only for the single current option in a menu-simple-select list.",
        "Do not use as hover, focus, success, validation, or arbitrary selected-card styling.",
        "Primitive proof must verify programmatic selected state and visible text meaning.",
      ],
    },
    {
      id: themedId("menu-simple-select-option-frame-disabled", theme),
      tokenName: `--menu-simple-select-option-frame-disabled-${theme}`,
      value: {
        frameRole: "disabled option item",
        backgroundValue: values.disabledSurface,
        foregroundValue: values.disabledForeground,
        supportingForegroundValue: values.disabledForeground,
        iconForegroundValue: values.disabledForeground,
        borderValue: values.disabledBorder,
        radiusValue: "0.375rem",
        paddingBlockValue: "0.625rem",
        paddingInlineValue: "0.75rem",
        gapValue: "0.25rem",
        minBlockSize: "4.5rem",
        minInlineSize: "0",
        maxInlineSize: "100%",
        maxBlockSize: "none",
        zIndexValue: "auto",
        scrollBehavior: "not applicable to individual option",
      },
      derivation: {
        sourceTokenName: "background-color + supporting-text-style",
        sourceValue: `${values.disabledSurface} muted surface; ${values.disabledForeground} muted text`,
        formulaOrMapping: "disabled option uses muted surface, foreground, and border while preserving row geometry",
        renderedValue: "muted option frame",
      },
      preview: {
        kind: "surface-card",
        sample: "Unavailable",
        background: values.disabledSurface,
        foreground: values.disabledForeground,
        border: values.disabledBorder,
        radius: "0.375rem",
        label: `Disabled option ${theme}`,
      },
      metadata: {
        frameRole: "disabled option item",
        theme,
        state: "disabled",
        accessibility: "Disabled meaning must be programmatic and not rely on muted color alone.",
      },
      useCaseInstructions: [
        "Use for unavailable menu-simple-select options only when the primitive exposes disabled semantics.",
        "Do not use for inactive, archived, or unselected options that remain selectable.",
        "Primitive proof must verify disabled options cannot be selected.",
      ],
    },
  ];
}

export const tokenDefinitionV1 = {
  schema: "kanbien.designSystem.tokenDefinition.v1",
  contractScope: "shared",
  designSystem: "default",
  uiFamily: "menu-simple-select",
  tokenType: "menu-simple-select-frame",
  status: "review-ready",
  behaviorRulePath: "docs/design-system/01-behavior-rule/shared/menu-simple-select/MenuSimpleSelect-Behaviour.md",
  tokenContractPath: "docs/design-system/02-token/shared/menu-simple-select-frame/MenuSimpleSelectFrame-Contract.md",
  tokenDefinitionPath: "docs/design-system/02-token/systems/default/menu-simple-select-frame/MenuSimpleSelectFrame-Implementation.md",
  page: {
    route: "/design-system/default/tokens/menu-simple-select-frame",
    htmlPath: "src/frontend/designSystem/systems/default/tokens/menu-simple-select-frame/index.html",
    title: "Menu Simple Select Frame Token",
    description: "Review governed trigger, icon-trigger, anchored menu, option, current, and disabled frame values for compact menu selects.",
  },
  codeSeam: {
    contractModule: "src/frontend/designSystem/layers/02-token/menu-simple-select-frame/contract.mjs",
    contractExport: "menuSimpleSelectFrameTokenContract",
    governedRuntimeModule: "src/frontend/designSystem/layers/02-token/menu-simple-select-frame/systems/default.mjs",
    systemProofModule: "src/frontend/designSystem/systems/default/tokens/proofs/menuSimpleSelectFrame.tokens.mjs",
    systemTokenExport: "menuSimpleSelectFrameTokenSpec",
    rendererModule: "src/frontend/designSystem/shared/renderers/renderTokenSpecPage.mjs",
    rendererExport: "renderTokenSpecPage",
    allowedConsumers: ["03-primitive", "04-pattern-contract"],
  },
  dependencies: [
    {
      contractId: "tokens.background-color",
      variantId: "background-color-surface-original",
      tokenName: "--background-color-surface-original",
      value: "#ffffff",
      relationship: "paired-with",
    },
    {
      contractId: "tokens.primary-tinted-background",
      variantId: "primary-tinted-background-original",
      tokenName: "--primary-tinted-background-original",
      value: "color-mix(in srgb, #635bff 12%, white)",
      relationship: "derived-from",
    },
  ],
  diagnostic: {
    kind: "none",
    rule: "No diagnostic override is needed for signed frame values; primitive and pattern proofs own rendered state controls.",
  },
  variants: ["original", "dark", "desert"].flatMap(variantsForTheme),
};

export const variants = tokenDefinitionV1.variants;

function toPageVariant(variant) {
  return {
    id: variant.id,
    tokenName: variant.tokenName,
    tokenValue: variant.derivation.renderedValue,
    frameRole: variant.value.frameRole,
    backgroundValue: variant.value.backgroundValue,
    foregroundValue: variant.value.foregroundValue,
    supportingForegroundValue: variant.value.supportingForegroundValue,
    iconForegroundValue: variant.value.iconForegroundValue,
    borderValue: variant.value.borderValue,
    radiusValue: variant.value.radiusValue,
    paddingBlockValue: variant.value.paddingBlockValue,
    paddingInlineValue: variant.value.paddingInlineValue,
    gapValue: variant.value.gapValue,
    minBlockSize: variant.value.minBlockSize,
    minInlineSize: variant.value.minInlineSize,
    maxInlineSize: variant.value.maxInlineSize,
    maxBlockSize: variant.value.maxBlockSize,
    zIndexValue: variant.value.zIndexValue,
    scrollBehavior: variant.value.scrollBehavior,
    sourceTokenName: variant.derivation.sourceTokenName,
    formulaOrMapping: variant.derivation.formulaOrMapping,
    state: variant.metadata.state,
    theme: variant.metadata.theme,
    accessibility: variant.metadata.accessibility,
    preview: variant.preview,
    usage: [
      { label: "Allowed", text: variant.useCaseInstructions[0] },
      { label: "Denied", text: variant.useCaseInstructions[1] },
      { label: "Proof", text: variant.useCaseInstructions[2] },
    ],
  };
}

export const menuSimpleSelectFrameTokenVariants = variants.map(toPageVariant);

export const menuSimpleSelectFrameTokenSpec = {
  contractId: menuSimpleSelectFrameTokenContract.contractId,
  systemKey: tokenDefinitionV1.designSystem,
  tokenType: tokenDefinitionV1.tokenType,
  title: tokenDefinitionV1.page.title,
  description: tokenDefinitionV1.page.description,
  variantSectionDescription:
    "Review text trigger, icon trigger, panel, resting option, current option, and disabled option frame values across original, dark, and desert themes.",
  tokenTypeTemplate,
  summaryPanels: [
    {
      label: "Text trigger",
      title: "Compact text-backed selection trigger",
      variantId: "menu-simple-select-trigger-frame-default",
      supportingText: "Text-backed trigger owns label and current-value space.",
    },
    {
      label: "Icon trigger",
      title: "Square icon-only selection trigger",
      variantId: "menu-simple-select-trigger-frame-icon",
      supportingText: "Icon-only trigger keeps the same accessible name while visible text is suppressed.",
    },
    {
      label: "Panel",
      title: "Anchored scrollable option panel",
      variantId: "menu-simple-select-panel-frame-default",
      supportingText: "Panel has governed width, max height, and stacking.",
    },
  ],
  variantFields: [
    ["frameRole", "Frame role"],
    ["theme", "Theme"],
    ["backgroundValue", "Background"],
    ["foregroundValue", "Foreground"],
    ["supportingForegroundValue", "Supporting foreground"],
    ["iconForegroundValue", "Icon foreground"],
    ["borderValue", "Border"],
    ["radiusValue", "Radius"],
    ["paddingBlockValue", "Block padding"],
    ["paddingInlineValue", "Inline padding"],
    ["gapValue", "Gap"],
    ["minBlockSize", "Min block"],
    ["minInlineSize", "Min inline"],
    ["maxInlineSize", "Max inline"],
    ["maxBlockSize", "Max block"],
    ["zIndexValue", "Z index"],
    ["scrollBehavior", "Scroll behavior"],
  ],
  variants: menuSimpleSelectFrameTokenVariants,
  consumerRestrictions: [
    "Consumers must use this token instead of local trigger, menu, option, selected, disabled, border, radius, spacing, z-index, or scroll-height literals.",
    "Current and disabled frame values must be paired with primitive-owned programmatic state semantics.",
    "Icon-only trigger values must preserve an accessible name through the primitive.",
    "This token does not define select ARIA behavior, keyboard handling, option row anatomy, header placement, or app adoption.",
  ],
  requiredEvidence: [
    "Token proof must show text and icon trigger frame roles separately.",
    "Token proof must expose original, dark, and desert theme frame variants.",
    "Primitive proof must verify text and icon trigger variants.",
    "Primitive proof must verify RTL, constrained mobile width, and themed review states.",
  ],
};
