import { standardPageShellFrameTokenContract } from "../../../../layers/02-token/standard-page-shell-frame/contract.mjs";

export const tokenTypeTemplate = {
  schema: "kanbien.designSystem.tokenTypeTemplate.v1",
  tokenType: "standard-page-shell-frame",
  previewKind: "standard-page-shell-frame-sample",
  variantSchema: {
    valueFields: [
      "frameRole",
      "topNavLayer",
      "subNavLayer",
      "contextNavLayer",
      "contextNavDrawerLayer",
      "contextNavMenuLayer",
      "tooltipLayer",
      "topNavPaddingBlockValue",
      "topNavPaddingInlineValue",
      "topNavGapValue",
      "subNavPaddingBlockValue",
      "subNavPaddingInlineValue",
      "subNavGapValue",
      "subNavSearchMaxInlineSize",
      "mobileBreakpoint",
      "contextRailInlineSize",
      "contextRailItemSize",
      "contextRailGapValue",
      "contextRailPaddingBlockValue",
      "contextRailPaddingInlineValue",
      "mobileContextBarOffset",
      "mobileShellPagePaddingBottom",
      "sidePanelInlineSize",
      "secondarySidePanelInlineStart",
      "mobileContextBarColumns",
      "mobileContextBarPinning",
      "surfaceTopNav",
      "surfaceSubNav",
      "surfaceContextNav",
      "borderValue",
    ],
    metadataFields: ["frameRole", "responsiveBehavior", "layering", "accessibility"],
    useCaseInstructionFields: ["allowedUse", "forbiddenUse", "childTokenBoundary"],
  },
};

export const tokenDefinitionV1 = {
  schema: "kanbien.designSystem.tokenDefinition.v1",
  contractScope: "shared",
  designSystem: "default",
  uiFamily: "standard-page-shell",
  tokenType: "standard-page-shell-frame",
  status: "review-ready",
  behaviorRulePath: "docs/design-system/01-behavior-rule/shared/standard-page-shell/StandardPageShell-Behaviour.md",
  tokenContractPath: "docs/design-system/02-token/shared/standard-page-shell-frame/StandardPageShellFrame-Contract.md",
  tokenDefinitionPath: "docs/design-system/02-token/systems/default/standard-page-shell-frame/StandardPageShellFrame-Implementation.md",
  page: {
    route: "/design-system/default/tokens/standard-page-shell-frame",
    htmlPath: "src/frontend/designSystem/systems/default/tokens/standard-page-shell-frame/index.html",
    title: "Standard Page Shell Frame Token",
    description: "Review governed shell frame values before shell primitives, patterns, or components consume them.",
  },
  codeSeam: {
    contractModule: "src/frontend/designSystem/layers/02-token/standard-page-shell-frame/contract.mjs",
    contractExport: "standardPageShellFrameTokenContract",
    governedRuntimeModule: "src/frontend/designSystem/layers/02-token/standard-page-shell-frame/systems/default.mjs",
    systemProofModule: "src/frontend/designSystem/systems/default/tokens/proofs/standardPageShellFrame.tokens.mjs",
    systemTokenExport: "standardPageShellFrameTokenSpec",
    rendererModule: "src/frontend/designSystem/shared/renderers/renderTokenSpecPage.mjs",
    rendererExport: "renderTokenSpecPage",
    allowedConsumers: ["03-primitive", "04-pattern-contract", "05-component-seam"],
  },
  dependencies: [],
  diagnostic: {
    kind: "none",
    rule: "No diagnostic override is approved; proof route must render signed shell-frame values only.",
  },
  variants: [
    {
      id: "standard-page-shell-frame-default",
      tokenName: "--standard-page-shell-frame",
      value: {
        frameRole: "standard page shell frame",
        topNavLayer: "6",
        subNavLayer: "4",
        contextNavLayer: "2147481000",
        contextNavDrawerLayer: "2147481001",
        contextNavMenuLayer: "2147481002",
        tooltipLayer: "2147483000",
        topNavPaddingBlockValue: "0.5rem",
        topNavPaddingInlineValue: "1rem",
        topNavGapValue: "1rem",
        subNavPaddingBlockValue: "0.75rem",
        subNavPaddingInlineValue: "1rem",
        subNavGapValue: "1rem",
        subNavSearchMaxInlineSize: "40rem",
        mobileBreakpoint: "44rem",
        contextRailInlineSize: "4.25rem",
        contextRailItemSize: "2.75rem",
        contextRailGapValue: "0.55rem",
        contextRailPaddingBlockValue: "0.75rem",
        contextRailPaddingInlineValue: "0.5rem",
        mobileContextBarOffset: "calc(4.125rem + env(safe-area-inset-bottom, 0))",
        mobileShellPagePaddingBottom: "5.75rem",
        sidePanelInlineSize: "min(22rem, calc(100vw - 4.25rem))",
        secondarySidePanelInlineStart: "calc(4.25rem + min(22rem, calc(100vw - 4.25rem)))",
        mobileContextBarColumns: "repeat(5, minmax(0, 1fr))",
        mobileContextBarPinning:
          "context-navigation child frame must remain fixed to the visual viewport bottom and must not participate in document scroll",
        surfaceTopNav: "var(--surface-3)",
        surfaceSubNav: "var(--surface-1)",
        surfaceContextNav: "var(--surface-2)",
        borderValue: "0.0625rem solid var(--line)",
      },
      derivation: {
        sourceTokenName: "40-system shell CSS",
        sourceValue: "src/frontend/designSystem/assets/styles.css",
        formulaOrMapping:
          "Values are lifted from the existing signed shell CSS selectors and root shell layer variables; no child tools-nav sizing value is invented in this parent token.",
        renderedValue:
          "top nav layer 6 / sub nav layer 4 / context rail 4.25rem / context item 2.75rem / drawer width min(22rem, calc(100vw - 4.25rem)) / mobile bottom inset 5.75rem",
      },
      preview: {
        kind: "standard-page-shell-frame-sample",
        sample: "Standard page shell frame",
        background: "var(--surface-3)",
        foreground: "var(--text)",
        border: "0.0625rem solid var(--line)",
        radius: "0",
      },
      metadata: {
        frameRole: "standard page shell frame",
        responsiveBehavior:
          "desktop preserves top/sub chrome plus fixed context rail and drawer offsets; mobile preserves bottom context bar offset and page-bottom inset above safe-area",
        layering:
          "top nav, sub nav, context rail, context drawers, context menus, and tooltips use signed layer values instead of local z-index literals",
        accessibility:
          "Shell frame values must keep navigation, drawers, tooltips, and page content reachable at reduced width, zoom, mobile safe-area, and RTL.",
      },
      useCaseInstructions: [
        "Use for shell primitives and patterns that place top nav, sub nav, context rail, context drawers, and shell content in the standard page frame.",
        "Do not use for child navigation item anatomy, page-specific workflow controls, tools-nav action semantics, bottom interaction bars, component props, or app-local CSS.",
        "Tools navigation concrete sizing and placement must be governed by a later tools-navigation token before downstream consumers may rely on those values.",
      ],
    },
  ],
};

export const variants = tokenDefinitionV1.variants;

function toPageVariant(variant) {
  return {
    id: variant.id,
    tokenName: variant.tokenName,
    tokenValue: variant.derivation.renderedValue,
    frameRole: variant.value.frameRole,
    topNavLayer: variant.value.topNavLayer,
    subNavLayer: variant.value.subNavLayer,
    contextNavLayer: variant.value.contextNavLayer,
    contextNavDrawerLayer: variant.value.contextNavDrawerLayer,
    contextNavMenuLayer: variant.value.contextNavMenuLayer,
    tooltipLayer: variant.value.tooltipLayer,
    topNavPaddingBlockValue: variant.value.topNavPaddingBlockValue,
    topNavPaddingInlineValue: variant.value.topNavPaddingInlineValue,
    topNavGapValue: variant.value.topNavGapValue,
    subNavPaddingBlockValue: variant.value.subNavPaddingBlockValue,
    subNavPaddingInlineValue: variant.value.subNavPaddingInlineValue,
    subNavGapValue: variant.value.subNavGapValue,
    subNavSearchMaxInlineSize: variant.value.subNavSearchMaxInlineSize,
    mobileBreakpoint: variant.value.mobileBreakpoint,
    contextRailInlineSize: variant.value.contextRailInlineSize,
    contextRailItemSize: variant.value.contextRailItemSize,
    contextRailGapValue: variant.value.contextRailGapValue,
    contextRailPaddingBlockValue: variant.value.contextRailPaddingBlockValue,
    contextRailPaddingInlineValue: variant.value.contextRailPaddingInlineValue,
    mobileContextBarOffset: variant.value.mobileContextBarOffset,
    mobileShellPagePaddingBottom: variant.value.mobileShellPagePaddingBottom,
    sidePanelInlineSize: variant.value.sidePanelInlineSize,
    secondarySidePanelInlineStart: variant.value.secondarySidePanelInlineStart,
    mobileContextBarColumns: variant.value.mobileContextBarColumns,
    mobileContextBarPinning: variant.value.mobileContextBarPinning,
    surfaceTopNav: variant.value.surfaceTopNav,
    surfaceSubNav: variant.value.surfaceSubNav,
    surfaceContextNav: variant.value.surfaceContextNav,
    borderValue: variant.value.borderValue,
    sourceTokenName: variant.derivation.sourceTokenName,
    sourceValue: variant.derivation.sourceValue,
    formulaOrMapping: variant.derivation.formulaOrMapping,
    theme: "all",
    accessibility: variant.metadata.accessibility,
    responsiveBehavior: variant.metadata.responsiveBehavior,
    layering: variant.metadata.layering,
    preview: variant.preview,
    usage: [
      { label: "Allowed", text: variant.useCaseInstructions[0] },
      { label: "Denied", text: variant.useCaseInstructions[1] },
      { label: "Child token boundary", text: variant.useCaseInstructions[2] },
    ],
  };
}

export const standardPageShellFrameTokenVariants = variants.map(toPageVariant);

export const standardPageShellFrameTokenSpec = {
  contractId: standardPageShellFrameTokenContract.contractId,
  systemKey: tokenDefinitionV1.designSystem,
  tokenType: "standard-page-shell-frame",
  title: tokenDefinitionV1.page.title,
  description: tokenDefinitionV1.page.description,
  variantSectionDescription: "This variant governs parent standard page shell frame values.",
  tokenTypeTemplate,
  summaryPanels: [
    {
      label: "Shell",
      title: "Desktop and mobile shell geometry",
      variantId: "standard-page-shell-frame-default",
      supportingText: "The proof maps each signed value onto the shell region it governs before shell composition can consume it.",
    },
  ],
  variantFields: [
    ["frameRole", "Role"],
    ["topNavLayer", "Top nav layer"],
    ["subNavLayer", "Sub nav layer"],
    ["contextNavLayer", "Context nav layer"],
    ["contextNavDrawerLayer", "Context drawer layer"],
    ["contextNavMenuLayer", "Context menu layer"],
    ["tooltipLayer", "Tooltip layer"],
    ["topNavPaddingBlockValue", "Top nav block padding"],
    ["topNavPaddingInlineValue", "Top nav inline padding"],
    ["topNavGapValue", "Top nav gap"],
    ["subNavPaddingBlockValue", "Sub nav block padding"],
    ["subNavPaddingInlineValue", "Sub nav inline padding"],
    ["subNavGapValue", "Sub nav gap"],
    ["subNavSearchMaxInlineSize", "Sub nav search max width"],
    ["mobileBreakpoint", "Mobile breakpoint"],
    ["contextRailInlineSize", "Context rail width"],
    ["contextRailItemSize", "Context item size"],
    ["contextRailGapValue", "Context rail gap"],
    ["contextRailPaddingBlockValue", "Context rail block padding"],
    ["contextRailPaddingInlineValue", "Context rail inline padding"],
    ["mobileContextBarOffset", "Mobile context bar offset"],
    ["mobileShellPagePaddingBottom", "Mobile page bottom inset"],
    ["sidePanelInlineSize", "Side panel width"],
    ["secondarySidePanelInlineStart", "Secondary side panel offset"],
    ["mobileContextBarColumns", "Mobile context columns"],
    ["mobileContextBarPinning", "Mobile context pinning"],
    ["surfaceTopNav", "Top nav surface"],
    ["surfaceSubNav", "Sub nav surface"],
    ["surfaceContextNav", "Context nav surface"],
    ["borderValue", "Border"],
    ["sourceTokenName", "Source"],
    ["sourceValue", "Source file"],
    ["formulaOrMapping", "Formula or mapping"],
  ],
  variants: standardPageShellFrameTokenVariants,
  consumerRestrictions: [
    "Consumers must import this token seam instead of hard-coding shell z-indexes, context rail widths, drawer offsets, chrome spacing, search max width, or mobile bottom insets.",
    "The standard page shell frame token does not approve child navigation item anatomy, profile menus, breadcrumb behavior, search behavior, tools-nav content, bottom interaction bars, component seams, or app adoption.",
    "Tools navigation concrete sizing and placement must be governed by a later tools-navigation token before downstream consumers may rely on those values.",
  ],
  requiredEvidence: [
    "Rendered proof must show signed shell layer and frame values.",
    "Layer 3 shell primitives must consume this token before owning shell markup.",
    "Layer 4 shell patterns must prove desktop, mobile, RTL, reduced-width, and overlay reachability in the browser.",
  ],
};
