import { tooltipSurfaceTokenContract } from "../../../../layers/02-token/tooltip-surface/contract.mjs";

export const tokenTypeTemplate = {
  schema: "kanbien.designSystem.tokenTypeTemplate.v1",
  tokenType: "tooltip-surface",
  previewKind: "tooltip-surface-sample",
  variantSchema: {
    valueFields: [
      "surfaceRole",
      "backgroundValue",
      "foregroundValue",
      "borderValue",
      "shadowValue",
      "radiusValue",
      "paddingBlockValue",
      "paddingInlineValue",
      "maxInlineSizeValue",
      "zIndexValue",
      "motionDurationValue",
      "motionEasingValue",
    ],
    metadataFields: ["surfaceRole", "theme", "state", "accessibility"],
    useCaseInstructionFields: ["allowedUse", "forbiddenUse", "accessibilityRule"],
  },
};

export const tokenDefinitionV1 = {
  schema: "kanbien.designSystem.tokenDefinition.v1",
  contractScope: "shared",
  designSystem: "default",
  uiFamily: "tooltip-surface",
  tokenType: "tooltip-surface",
  status: "review-ready",
  behaviorRulePath:
    "docs/design-system/01-behavior-rule/shared/text-overflow-disclosure/TextOverflowDisclosure-Behaviour.md",
  tokenContractPath: "docs/design-system/02-token/shared/tooltip-surface/TooltipSurface-Contract.md",
  tokenDefinitionPath: "docs/design-system/02-token/systems/default/tooltip-surface/TooltipSurface-Implementation.md",
  page: {
    route: "/design-system/default/tokens/tooltip-surface",
    htmlPath: "src/frontend/designSystem/systems/default/tokens/tooltip-surface/index.html",
    title: "Tooltip Surface Tokens",
    description:
      "Review governed visual values for full-text disclosure tooltip surfaces before tooltip primitives consume them.",
  },
  codeSeam: {
    contractModule: "src/frontend/designSystem/layers/02-token/tooltip-surface/contract.mjs",
    contractExport: "tooltipSurfaceTokenContract",
    governedRuntimeModule: "src/frontend/designSystem/layers/02-token/tooltip-surface/systems/default.mjs",
    systemProofModule: "src/frontend/designSystem/systems/default/tokens/proofs/tooltipSurface.tokens.mjs",
    systemTokenExport: "tooltipSurfaceTokenSpec",
    rendererModule: "src/frontend/designSystem/shared/renderers/renderTokenSpecPage.mjs",
    rendererExport: "renderTokenSpecPage",
    allowedConsumers: ["02-token", "03-primitive", "04-pattern-contract"],
  },
  dependencies: [],
  diagnostic: {
    kind: "none",
    rule: "No upstream token dependency exists for this standalone tooltip surface visual token.",
  },
  variants: [
    {
      id: "tooltip-surface-original",
      tokenName: "--tooltip-surface-original",
      value: {
        surfaceRole: "text overflow disclosure surface",
        backgroundValue: "#111827",
        foregroundValue: "#ffffff",
        borderValue: "rgba(255, 255, 255, 0.14)",
        shadowValue: "0 0.75rem 1.6rem rgba(15, 23, 42, 0.22)",
        radiusValue: "0.375rem",
        paddingBlockValue: "0.45rem",
        paddingInlineValue: "0.6rem",
        maxInlineSizeValue: "18rem",
        zIndexValue: "1300",
        motionDurationValue: "120ms",
        motionEasingValue: "ease-out",
      },
      preview: {
        kind: "tooltip-surface-sample",
        sample: "Organization label with long text that is fully available here.",
        label: "Original tooltip surface",
        background: "#111827",
        foreground: "#ffffff",
        border: "rgba(255, 255, 255, 0.14)",
        shadow: "0 0.75rem 1.6rem rgba(15, 23, 42, 0.22)",
        radius: "0.375rem",
        paddingBlock: "0.45rem",
        paddingInline: "0.6rem",
        maxInlineSize: "18rem",
      },
      metadata: {
        surfaceRole: "text overflow disclosure surface",
        theme: "original",
        state: "none",
        accessibility:
          "Surface values must keep full text readable, bounded, and visually separated from the host surface.",
      },
      useCaseInstructions: [
        "Use for full-text disclosure surfaces created by later governed tooltip or disclosure primitives.",
        "Do not use as menu, popover, dialog, toast, validation, selected, active, or app-local tooltip approval.",
        "A later primitive must provide keyboard, pointer, touch, dismissal, accessible-name, and placement behavior.",
      ],
    },
    {
      id: "tooltip-surface-dark",
      tokenName: "--tooltip-surface-dark",
      value: {
        surfaceRole: "text overflow disclosure surface",
        backgroundValue: "#f8fafc",
        foregroundValue: "#111827",
        borderValue: "rgba(15, 23, 42, 0.16)",
        shadowValue: "0 0.8rem 1.7rem rgba(0, 0, 0, 0.36)",
        radiusValue: "0.375rem",
        paddingBlockValue: "0.45rem",
        paddingInlineValue: "0.6rem",
        maxInlineSizeValue: "18rem",
        zIndexValue: "1300",
        motionDurationValue: "120ms",
        motionEasingValue: "ease-out",
      },
      preview: {
        kind: "tooltip-surface-sample",
        sample: "Organization label with long text that is fully available here.",
        label: "Dark tooltip surface",
        background: "#f8fafc",
        foreground: "#111827",
        border: "rgba(15, 23, 42, 0.16)",
        shadow: "0 0.8rem 1.7rem rgba(0, 0, 0, 0.36)",
        radius: "0.375rem",
        paddingBlock: "0.45rem",
        paddingInline: "0.6rem",
        maxInlineSize: "18rem",
      },
      metadata: {
        surfaceRole: "text overflow disclosure surface",
        theme: "dark",
        state: "none",
        accessibility: "Dark-theme tooltip surface must remain readable against dark application chrome.",
      },
      useCaseInstructions: [
        "Use for dark-theme full-text disclosure surfaces created by later governed tooltip or disclosure primitives.",
        "Do not use as original-theme evidence, menu, popover, dialog, toast, validation, selected, or active styling.",
        "A later primitive must provide keyboard, pointer, touch, dismissal, accessible-name, and placement behavior.",
      ],
    },
    {
      id: "tooltip-surface-desert",
      tokenName: "--tooltip-surface-desert",
      value: {
        surfaceRole: "text overflow disclosure surface",
        backgroundValue: "#3b2a20",
        foregroundValue: "#fffaf0",
        borderValue: "rgba(255, 250, 240, 0.18)",
        shadowValue: "0 0.75rem 1.55rem rgba(83, 50, 28, 0.24)",
        radiusValue: "0.375rem",
        paddingBlockValue: "0.45rem",
        paddingInlineValue: "0.6rem",
        maxInlineSizeValue: "18rem",
        zIndexValue: "1300",
        motionDurationValue: "120ms",
        motionEasingValue: "ease-out",
      },
      preview: {
        kind: "tooltip-surface-sample",
        sample: "Organization label with long text that is fully available here.",
        label: "Desert tooltip surface",
        background: "#3b2a20",
        foreground: "#fffaf0",
        border: "rgba(255, 250, 240, 0.18)",
        shadow: "0 0.75rem 1.55rem rgba(83, 50, 28, 0.24)",
        radius: "0.375rem",
        paddingBlock: "0.45rem",
        paddingInline: "0.6rem",
        maxInlineSize: "18rem",
      },
      metadata: {
        surfaceRole: "text overflow disclosure surface",
        theme: "desert",
        state: "none",
        accessibility: "Desert-theme tooltip surface must preserve contrast without relying on original-theme colors.",
      },
      useCaseInstructions: [
        "Use for desert-theme full-text disclosure surfaces created by later governed tooltip or disclosure primitives.",
        "Do not use as original or dark-theme evidence, menu, popover, dialog, toast, validation, selected, or active styling.",
        "A later primitive must provide keyboard, pointer, touch, dismissal, accessible-name, and placement behavior.",
      ],
    },
  ],
};

export const variants = tokenDefinitionV1.variants;

function toPageVariant(variant) {
  return {
    id: variant.id,
    tokenName: variant.tokenName,
    tokenValue: `${variant.value.backgroundValue} / ${variant.value.foregroundValue}`,
    role: variant.metadata.surfaceRole,
    backgroundValue: variant.value.backgroundValue,
    foregroundValue: variant.value.foregroundValue,
    borderValue: variant.value.borderValue,
    shadowValue: variant.value.shadowValue,
    radiusValue: variant.value.radiusValue,
    paddingBlockValue: variant.value.paddingBlockValue,
    paddingInlineValue: variant.value.paddingInlineValue,
    maxInlineSizeValue: variant.value.maxInlineSizeValue,
    zIndexValue: variant.value.zIndexValue,
    motionDurationValue: variant.value.motionDurationValue,
    motionEasingValue: variant.value.motionEasingValue,
    theme: variant.metadata.theme,
    state: variant.metadata.state,
    accessibility: variant.metadata.accessibility,
    preview: variant.preview,
    usage: [
      { label: "Allowed", text: variant.useCaseInstructions[0] },
      { label: "Denied", text: variant.useCaseInstructions[1] },
      { label: "Behavior", text: variant.useCaseInstructions[2] },
    ],
  };
}

export const tooltipSurfaceTokenVariants = variants.map(toPageVariant);

export const tooltipSurfaceTokenSpec = {
  contractId: tooltipSurfaceTokenContract.contractId,
  systemKey: tokenDefinitionV1.designSystem,
  tokenType: tokenDefinitionV1.tokenType,
  title: tokenDefinitionV1.page.title,
  description: tokenDefinitionV1.page.description,
  variantSectionDescription:
    "Each row is a visual surface recipe for later full-text disclosure primitives. Behavior and placement are not approved here.",
  tokenTypeTemplate,
  summaryPanels: [
    {
      label: "Original",
      title: "Readable full-text disclosure",
      variantId: "tooltip-surface-original",
      supportingText: "Surface, text, spacing, shadow, layer, and motion values move together.",
    },
    {
      label: "Dark",
      title: "Dark-theme disclosure surface",
      variantId: "tooltip-surface-dark",
      supportingText: "Theme-specific visual values are reviewed separately before primitive consumption.",
    },
    {
      label: "Desert",
      title: "Desert disclosure surface",
      variantId: "tooltip-surface-desert",
      supportingText: "Desert review prevents original-theme tooltip values from being copied blindly.",
    },
  ],
  variantFields: [
    ["role", "Role"],
    ["backgroundValue", "Background"],
    ["foregroundValue", "Foreground"],
    ["borderValue", "Border"],
    ["shadowValue", "Shadow"],
    ["radiusValue", "Radius"],
    ["paddingBlockValue", "Block padding"],
    ["paddingInlineValue", "Inline padding"],
    ["maxInlineSizeValue", "Max inline size"],
    ["zIndexValue", "Layer"],
    ["motionDurationValue", "Motion duration"],
    ["motionEasingValue", "Motion easing"],
  ],
  variants: tooltipSurfaceTokenVariants,
  consumerRestrictions: [
    "Consumers must use this token instead of local tooltip surface, foreground, border, shadow, radius, padding, z-index, or motion literals.",
    "Consumers must not treat this token as trigger behavior, hover/focus handling, touch behavior, dismissal behavior, placement logic, or ARIA approval.",
    "Consumers must not use this token for menus, popovers, dialogs, toasts, selected states, validation states, or app-local tooltip approximations.",
    "Tooltip primitives must preserve the text-overflow-disclosure behavior rule before claiming readiness.",
  ],
  requiredEvidence: [
    "The tooltip surface sample must render full text as readable text, not only as metadata.",
    "The sample must stay inside its preview container on desktop and mobile.",
    "RTL rendering must preserve readable full text and stable inline padding.",
    "The proof must state that trigger semantics, placement, dismissal, and accessible behavior remain later-layer work.",
  ],
};
