INSERT INTO root_authz_capabilities (
  capability_key,
  description,
  root_user_admin_default_mandatory,
  root_user_admin_default_protected,
  created_at,
  updated_at
)
VALUES
  (
    'design-system-canonicals.family.manage',
    'Create and update persisted design-system canonical family governance truth.',
    TRUE,
    TRUE,
    NOW(),
    NOW()
  ),
  (
    'design-system-canonicals.reference.manage',
    'Create and update persisted design-system canonical reference governance truth.',
    TRUE,
    TRUE,
    NOW(),
    NOW()
  ),
  (
    'web-app-hierarchy.sync-design-system-canonical-renderings',
    'Sync live persisted canonical-rendering routes into durable web-app hierarchy truth.',
    TRUE,
    TRUE,
    NOW(),
    NOW()
  )
ON CONFLICT (capability_key)
DO UPDATE SET
  description = EXCLUDED.description,
  root_user_admin_default_mandatory = EXCLUDED.root_user_admin_default_mandatory,
  root_user_admin_default_protected = EXCLUDED.root_user_admin_default_protected,
  updated_at = NOW();

INSERT INTO system_root_role_capability_grants (
  system_root_role_capability_grant_id,
  system_root_role_id,
  capability_key,
  is_mandatory,
  is_protected,
  created_at,
  updated_at,
  revoked_at
)
SELECT
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000001',
  c.capability_key,
  c.root_user_admin_default_mandatory,
  c.root_user_admin_default_protected,
  NOW(),
  NOW(),
  NULL
FROM root_authz_capabilities c
WHERE c.capability_key IN (
  'design-system-canonicals.family.manage',
  'design-system-canonicals.reference.manage',
  'web-app-hierarchy.sync-design-system-canonical-renderings'
)
ON CONFLICT (system_root_role_id, capability_key)
DO UPDATE SET
  is_mandatory = EXCLUDED.is_mandatory,
  is_protected = EXCLUDED.is_protected,
  revoked_at = NULL,
  updated_at = NOW();

INSERT INTO design_system_canonical_families (
  design_system_canonical_family_id,
  family_key,
  normalized_family_key,
  display_label,
  family_kind,
  launcher_title,
  launcher_description,
  launcher_category,
  generated_launcher_route_path,
  generated_root_route_path,
  legacy_launcher_route_path,
  source_surface_route_path,
  status,
  sort_order,
  featured,
  created_at,
  updated_at
)
VALUES
  (
    'de5d8395-3983-4efb-a160-bb7447624d9d',
    'page-shell-banner',
    'page-shell-banner',
    'Page-Shell Banner',
    'pattern',
    'Page-Shell Banner Canonical Renderings',
    'Persistence-backed launcher for the approved page-shell-banner canonical renderings.',
    'shell',
    '/design-system/canonical-renderings/page-shell-banner',
    '/design-system/canonical-renderings',
    '/design-system/canonicals/page-shell-banner',
    '/design-system/templates/page-shell',
    'live',
    10,
    TRUE,
    NOW(),
    NOW()
  )
ON CONFLICT (normalized_family_key)
DO UPDATE SET
  display_label = EXCLUDED.display_label,
  family_kind = EXCLUDED.family_kind,
  launcher_title = EXCLUDED.launcher_title,
  launcher_description = EXCLUDED.launcher_description,
  launcher_category = EXCLUDED.launcher_category,
  generated_launcher_route_path = EXCLUDED.generated_launcher_route_path,
  generated_root_route_path = EXCLUDED.generated_root_route_path,
  legacy_launcher_route_path = EXCLUDED.legacy_launcher_route_path,
  source_surface_route_path = EXCLUDED.source_surface_route_path,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  featured = EXCLUDED.featured,
  updated_at = NOW();

INSERT INTO design_system_canonical_references (
  design_system_canonical_reference_id,
  design_system_canonical_family_id,
  reference_id,
  normalized_reference_id,
  display_label,
  description,
  render_route_path,
  legacy_render_route_path,
  viewport,
  width,
  height,
  theme,
  direction,
  zoom,
  locale_fixture,
  label_density_fixture,
  state_variant_key,
  specimen_payload,
  status,
  sort_order,
  featured,
  created_at,
  updated_at
)
VALUES (
  'b1a15cb8-c054-4bec-a745-fa3f2ec7a9b8',
  'de5d8395-3983-4efb-a160-bb7447624d9d',
  'PSBR-001',
  'psbr-001',
  'Full four-state stack',
  'Captures the signed-off combined banner stack above page content.',
  '/design-system/canonical-renderings/page-shell-banner/PSBR-001',
  '/design-system/components/page-shell-banner?ref=PSBR-001&theme=normal&dir=ltr&zoom=0',
  'template-hosted shell banner reviewed on a dedicated canonical render surface',
  NULL,
  NULL,
  'normal',
  'ltr',
  0,
  NULL,
  NULL,
  'full-stack',
  '{"banners":["info","success","warning","danger"]}'::jsonb,
  'live',
  10,
  TRUE,
  NOW(),
  NOW()
)
ON CONFLICT (design_system_canonical_family_id, normalized_reference_id)
DO UPDATE SET
  display_label = EXCLUDED.display_label,
  description = EXCLUDED.description,
  render_route_path = EXCLUDED.render_route_path,
  legacy_render_route_path = EXCLUDED.legacy_render_route_path,
  viewport = EXCLUDED.viewport,
  width = EXCLUDED.width,
  height = EXCLUDED.height,
  theme = EXCLUDED.theme,
  direction = EXCLUDED.direction,
  zoom = EXCLUDED.zoom,
  locale_fixture = EXCLUDED.locale_fixture,
  label_density_fixture = EXCLUDED.label_density_fixture,
  state_variant_key = EXCLUDED.state_variant_key,
  specimen_payload = EXCLUDED.specimen_payload,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  featured = EXCLUDED.featured,
  updated_at = NOW();

INSERT INTO design_system_canonical_references (
  design_system_canonical_reference_id,
  design_system_canonical_family_id,
  reference_id,
  normalized_reference_id,
  display_label,
  description,
  render_route_path,
  legacy_render_route_path,
  viewport,
  width,
  height,
  theme,
  direction,
  zoom,
  locale_fixture,
  label_density_fixture,
  state_variant_key,
  specimen_payload,
  status,
  sort_order,
  featured,
  created_at,
  updated_at
)
VALUES (
  '4fa38036-7bdb-4d9f-a16f-91d8db685781',
  'de5d8395-3983-4efb-a160-bb7447624d9d',
  'PSBR-002',
  'psbr-002',
  'Success state with dismiss affordance',
  'Confirms positive shell feedback uses the same close grammar and spacing rules.',
  '/design-system/canonical-renderings/page-shell-banner/PSBR-002',
  '/design-system/components/page-shell-banner?ref=PSBR-002&theme=normal&dir=ltr&zoom=0',
  'template-hosted shell banner reviewed on a dedicated canonical render surface',
  NULL,
  NULL,
  'normal',
  'ltr',
  0,
  NULL,
  NULL,
  'success',
  '{"banners":["success"]}'::jsonb,
  'live',
  20,
  FALSE,
  NOW(),
  NOW()
)
ON CONFLICT (design_system_canonical_family_id, normalized_reference_id)
DO UPDATE SET
  display_label = EXCLUDED.display_label,
  description = EXCLUDED.description,
  render_route_path = EXCLUDED.render_route_path,
  legacy_render_route_path = EXCLUDED.legacy_render_route_path,
  viewport = EXCLUDED.viewport,
  width = EXCLUDED.width,
  height = EXCLUDED.height,
  theme = EXCLUDED.theme,
  direction = EXCLUDED.direction,
  zoom = EXCLUDED.zoom,
  locale_fixture = EXCLUDED.locale_fixture,
  label_density_fixture = EXCLUDED.label_density_fixture,
  state_variant_key = EXCLUDED.state_variant_key,
  specimen_payload = EXCLUDED.specimen_payload,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  featured = EXCLUDED.featured,
  updated_at = NOW();

INSERT INTO design_system_canonical_references (
  design_system_canonical_reference_id,
  design_system_canonical_family_id,
  reference_id,
  normalized_reference_id,
  display_label,
  description,
  render_route_path,
  legacy_render_route_path,
  viewport,
  width,
  height,
  theme,
  direction,
  zoom,
  locale_fixture,
  label_density_fixture,
  state_variant_key,
  specimen_payload,
  status,
  sort_order,
  featured,
  created_at,
  updated_at
)
VALUES (
  'd56145ec-25e5-45a6-92b3-4304b939095d',
  'de5d8395-3983-4efb-a160-bb7447624d9d',
  'PSBR-003',
  'psbr-003',
  'Warning state with dismiss affordance',
  'Confirms warning posture is distinct but still governed by the same shell anatomy.',
  '/design-system/canonical-renderings/page-shell-banner/PSBR-003',
  '/design-system/components/page-shell-banner?ref=PSBR-003&theme=normal&dir=ltr&zoom=0',
  'template-hosted shell banner reviewed on a dedicated canonical render surface',
  NULL,
  NULL,
  'normal',
  'ltr',
  0,
  NULL,
  NULL,
  'warning',
  '{"banners":["warning"]}'::jsonb,
  'live',
  30,
  FALSE,
  NOW(),
  NOW()
)
ON CONFLICT (design_system_canonical_family_id, normalized_reference_id)
DO UPDATE SET
  display_label = EXCLUDED.display_label,
  description = EXCLUDED.description,
  render_route_path = EXCLUDED.render_route_path,
  legacy_render_route_path = EXCLUDED.legacy_render_route_path,
  viewport = EXCLUDED.viewport,
  width = EXCLUDED.width,
  height = EXCLUDED.height,
  theme = EXCLUDED.theme,
  direction = EXCLUDED.direction,
  zoom = EXCLUDED.zoom,
  locale_fixture = EXCLUDED.locale_fixture,
  label_density_fixture = EXCLUDED.label_density_fixture,
  state_variant_key = EXCLUDED.state_variant_key,
  specimen_payload = EXCLUDED.specimen_payload,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  featured = EXCLUDED.featured,
  updated_at = NOW();

INSERT INTO design_system_canonical_references (
  design_system_canonical_reference_id,
  design_system_canonical_family_id,
  reference_id,
  normalized_reference_id,
  display_label,
  description,
  render_route_path,
  legacy_render_route_path,
  viewport,
  width,
  height,
  theme,
  direction,
  zoom,
  locale_fixture,
  label_density_fixture,
  state_variant_key,
  specimen_payload,
  status,
  sort_order,
  featured,
  created_at,
  updated_at
)
VALUES (
  '879a2f66-78f6-4043-9311-760b8572c83e',
  'de5d8395-3983-4efb-a160-bb7447624d9d',
  'PSBR-004',
  'psbr-004',
  'Danger state with dismiss affordance',
  'Confirms error posture remains dismissible and separated from page content.',
  '/design-system/canonical-renderings/page-shell-banner/PSBR-004',
  '/design-system/components/page-shell-banner?ref=PSBR-004&theme=normal&dir=ltr&zoom=0',
  'template-hosted shell banner reviewed on a dedicated canonical render surface',
  NULL,
  NULL,
  'normal',
  'ltr',
  0,
  NULL,
  NULL,
  'danger',
  '{"banners":["danger"]}'::jsonb,
  'live',
  40,
  FALSE,
  NOW(),
  NOW()
)
ON CONFLICT (design_system_canonical_family_id, normalized_reference_id)
DO UPDATE SET
  display_label = EXCLUDED.display_label,
  description = EXCLUDED.description,
  render_route_path = EXCLUDED.render_route_path,
  legacy_render_route_path = EXCLUDED.legacy_render_route_path,
  viewport = EXCLUDED.viewport,
  width = EXCLUDED.width,
  height = EXCLUDED.height,
  theme = EXCLUDED.theme,
  direction = EXCLUDED.direction,
  zoom = EXCLUDED.zoom,
  locale_fixture = EXCLUDED.locale_fixture,
  label_density_fixture = EXCLUDED.label_density_fixture,
  state_variant_key = EXCLUDED.state_variant_key,
  specimen_payload = EXCLUDED.specimen_payload,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  featured = EXCLUDED.featured,
  updated_at = NOW();

INSERT INTO design_system_canonical_references (
  design_system_canonical_reference_id,
  design_system_canonical_family_id,
  reference_id,
  normalized_reference_id,
  display_label,
  description,
  render_route_path,
  legacy_render_route_path,
  viewport,
  width,
  height,
  theme,
  direction,
  zoom,
  locale_fixture,
  label_density_fixture,
  state_variant_key,
  specimen_payload,
  status,
  sort_order,
  featured,
  created_at,
  updated_at
)
VALUES (
  '81c93f31-0322-457f-b6fb-c0b616b7c1a1',
  'de5d8395-3983-4efb-a160-bb7447624d9d',
  'PSBR-005',
  'psbr-005',
  'Partial stack after one dismiss',
  'Confirms dismissing one state leaves the remaining stack stable.',
  '/design-system/canonical-renderings/page-shell-banner/PSBR-005',
  '/design-system/components/page-shell-banner?ref=PSBR-005&theme=normal&dir=ltr&zoom=0',
  'template-hosted shell banner reviewed on a dedicated canonical render surface',
  NULL,
  NULL,
  'normal',
  'ltr',
  0,
  NULL,
  NULL,
  'partial-stack',
  '{"banners":["info","success","danger"]}'::jsonb,
  'live',
  50,
  FALSE,
  NOW(),
  NOW()
)
ON CONFLICT (design_system_canonical_family_id, normalized_reference_id)
DO UPDATE SET
  display_label = EXCLUDED.display_label,
  description = EXCLUDED.description,
  render_route_path = EXCLUDED.render_route_path,
  legacy_render_route_path = EXCLUDED.legacy_render_route_path,
  viewport = EXCLUDED.viewport,
  width = EXCLUDED.width,
  height = EXCLUDED.height,
  theme = EXCLUDED.theme,
  direction = EXCLUDED.direction,
  zoom = EXCLUDED.zoom,
  locale_fixture = EXCLUDED.locale_fixture,
  label_density_fixture = EXCLUDED.label_density_fixture,
  state_variant_key = EXCLUDED.state_variant_key,
  specimen_payload = EXCLUDED.specimen_payload,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  featured = EXCLUDED.featured,
  updated_at = NOW();
