INSERT INTO design_system_canonical_families (
  design_system_canonical_family_id,
  family_key,
  normalized_family_key,
  display_label,
  family_kind,
  launcher_title,
  launcher_description,
  launcher_category,
  generated_launcher_route_path,
  generated_root_route_path,
  legacy_launcher_route_path,
  source_surface_route_path,
  status,
  sort_order,
  featured,
  created_at,
  updated_at
)
VALUES (
  'e49c80a9-c34b-4b32-948f-174118971928',
  'drawer-select',
  'drawer-select',
  'Drawer Select',
  'component',
  'Drawer Select Canonical Renderings',
  'Persistence-backed launcher for the approved drawer-select canonical renderings.',
  'forms',
  '/design-system/canonical-renderings/drawer-select',
  '/design-system/canonical-renderings',
  '/design-system/canonicals/drawer-select',
  '/design-system/components/drawer-select',
  'live',
  70,
  FALSE,
  NOW(),
  NOW()
)
ON CONFLICT (normalized_family_key)
DO UPDATE SET
  display_label = EXCLUDED.display_label,
  family_kind = EXCLUDED.family_kind,
  launcher_title = EXCLUDED.launcher_title,
  launcher_description = EXCLUDED.launcher_description,
  launcher_category = EXCLUDED.launcher_category,
  generated_launcher_route_path = EXCLUDED.generated_launcher_route_path,
  generated_root_route_path = EXCLUDED.generated_root_route_path,
  legacy_launcher_route_path = EXCLUDED.legacy_launcher_route_path,
  source_surface_route_path = EXCLUDED.source_surface_route_path,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  featured = EXCLUDED.featured,
  updated_at = NOW();

WITH drawer_select_family AS (
  SELECT design_system_canonical_family_id
  FROM design_system_canonical_families
  WHERE normalized_family_key = 'drawer-select'
),
reference_rows (
  reference_id,
  display_label,
  description,
  render_route_path,
  legacy_render_route_path,
  viewport,
  width,
  theme,
  direction,
  zoom,
  state_variant_key,
  specimen_payload,
  sort_order,
  featured
) AS (
  VALUES
    ('DSR-001', 'Descriptive resting trigger with compressed three-plus summary', 'Resting descriptive trigger shows the approved three-plus summary compression while parent field framing stays visible.', '/design-system/canonical-renderings/drawer-select/DSR-001', '/design-system/components/drawer-select?ref=DSR-001&width=940&state=collections-resting-threeplus&theme=normal&dir=ltr&zoom=0', 'Parent field lane', 940, 'normal', 'ltr', 0, 'collections-resting-threeplus', '{"state":"collections-resting-threeplus"}'::jsonb, 10, FALSE),
    ('DSR-002', 'Descriptive open drawer with search, Selected, and Available stacks', 'Primary open state exposes the search-first drawer chassis with the approved Selected and Available naming.', '/design-system/canonical-renderings/drawer-select/DSR-002', '/design-system/components/drawer-select?ref=DSR-002&width=940&state=collections-open&theme=normal&dir=ltr&zoom=0', 'Parent field lane', 940, 'normal', 'ltr', 0, 'collections-open', '{"state":"collections-open"}'::jsonb, 20, TRUE),
    ('DSR-003', 'Descriptive no-match search while selections remain visible', 'Search empty state hides the Available stack contents without dropping the still-selected chips.', '/design-system/canonical-renderings/drawer-select/DSR-003', '/design-system/components/drawer-select?ref=DSR-003&width=940&state=collections-no-match&theme=normal&dir=ltr&zoom=0', 'Parent field lane', 940, 'normal', 'ltr', 0, 'collections-no-match', '{"state":"collections-no-match"}'::jsonb, 30, TRUE),
    ('DSR-004', 'Descriptive no-selected open state with empty fallback summary', 'Selected-empty review keeps the drawer open while the trigger falls back to the honest empty-summary noun.', '/design-system/canonical-renderings/drawer-select/DSR-004', '/design-system/components/drawer-select?ref=DSR-004&width=940&state=collections-empty-open&theme=normal&dir=ltr&zoom=0', 'Parent field lane', 940, 'normal', 'ltr', 0, 'collections-empty-open', '{"state":"collections-empty-open"}'::jsonb, 40, TRUE),
    ('DSR-005', 'Compact attribute-card variant open drawer', 'Compact variant keeps the same drawer contract while compressing the selected and available content to a single attribute line.', '/design-system/canonical-renderings/drawer-select/DSR-005', '/design-system/components/drawer-select?ref=DSR-005&width=820&state=segments-open&theme=normal&dir=ltr&zoom=0', 'Compact attribute-card lane', 820, 'normal', 'ltr', 0, 'segments-open', '{"state":"segments-open"}'::jsonb, 50, TRUE),
    ('DSR-006', 'Descriptive resting trigger with exact two-selection summary', 'Exact-two resting state keeps both labels visible without summary compression.', '/design-system/canonical-renderings/drawer-select/DSR-006', '/design-system/components/drawer-select?ref=DSR-006&width=940&state=collections-resting-two&theme=normal&dir=ltr&zoom=0', 'Parent field lane', 940, 'normal', 'ltr', 0, 'collections-resting-two', '{"state":"collections-resting-two"}'::jsonb, 60, TRUE),
    ('DSR-007', 'Descriptive resting trigger with exact one-selection summary', 'Single-selection resting state keeps the summary truthful without introducing a synthetic placeholder.', '/design-system/canonical-renderings/drawer-select/DSR-007', '/design-system/components/drawer-select?ref=DSR-007&width=940&state=collections-resting-one&theme=normal&dir=ltr&zoom=0', 'Parent field lane', 940, 'normal', 'ltr', 0, 'collections-resting-one', '{"state":"collections-resting-one"}'::jsonb, 70, TRUE),
    ('DSR-008', 'Descriptive open state after adding one available option', 'Add-flow review shows selected count and trigger summary after one Available option has been toggled on.', '/design-system/canonical-renderings/drawer-select/DSR-008', '/design-system/components/drawer-select?ref=DSR-008&width=940&state=collections-open-after-add&theme=normal&dir=ltr&zoom=0', 'Parent field lane', 940, 'normal', 'ltr', 0, 'collections-open-after-add', '{"state":"collections-open-after-add"}'::jsonb, 80, TRUE),
    ('DSR-009', 'Descriptive open state after removing one selected chip', 'Remove-flow review shows the open drawer after one Selected chip has been removed and synchronization has completed.', '/design-system/canonical-renderings/drawer-select/DSR-009', '/design-system/components/drawer-select?ref=DSR-009&width=940&state=collections-open-after-remove&theme=normal&dir=ltr&zoom=0', 'Parent field lane', 940, 'normal', 'ltr', 0, 'collections-open-after-remove', '{"state":"collections-open-after-remove"}'::jsonb, 90, TRUE),
    ('DSR-010', 'Descriptive resting trigger with empty fallback summary', 'Closed empty state preserves the hosted empty-summary noun without forcing the drawer open.', '/design-system/canonical-renderings/drawer-select/DSR-010', '/design-system/components/drawer-select?ref=DSR-010&width=940&state=collections-empty-resting&theme=normal&dir=ltr&zoom=0', 'Parent field lane', 940, 'normal', 'ltr', 0, 'collections-empty-resting', '{"state":"collections-empty-resting"}'::jsonb, 100, TRUE),
    ('DSR-011', 'Compact resting trigger with populated attribute-card summary', 'Closed compact state preserves the approved populated summary without opening the drawer.', '/design-system/canonical-renderings/drawer-select/DSR-011', '/design-system/components/drawer-select?ref=DSR-011&width=820&state=segments-resting&theme=normal&dir=ltr&zoom=0', 'Compact attribute-card lane', 820, 'normal', 'ltr', 0, 'segments-resting', '{"state":"segments-resting"}'::jsonb, 110, TRUE),
    ('DSR-012', 'Compact resting trigger with empty fallback summary', 'Closed compact empty state confirms the segment-specific fallback noun instead of reusing the descriptive one.', '/design-system/canonical-renderings/drawer-select/DSR-012', '/design-system/components/drawer-select?ref=DSR-012&width=820&state=segments-empty-resting&theme=normal&dir=ltr&zoom=0', 'Compact attribute-card lane', 820, 'normal', 'ltr', 0, 'segments-empty-resting', '{"state":"segments-empty-resting"}'::jsonb, 120, TRUE),
    ('DSR-013', 'Compact open state with no selected items', 'Compact selected-empty state keeps the attribute-card drawer open while showing the empty Selected stack.', '/design-system/canonical-renderings/drawer-select/DSR-013', '/design-system/components/drawer-select?ref=DSR-013&width=820&state=segments-empty-open&theme=normal&dir=ltr&zoom=0', 'Compact attribute-card lane', 820, 'normal', 'ltr', 0, 'segments-empty-open', '{"state":"segments-empty-open"}'::jsonb, 130, TRUE),
    ('DSR-014', 'Compact open state with no search matches', 'Compact search-empty state preserves the selected stack while the Available list is fully filtered out.', '/design-system/canonical-renderings/drawer-select/DSR-014', '/design-system/components/drawer-select?ref=DSR-014&width=820&state=segments-no-match&theme=normal&dir=ltr&zoom=0', 'Compact attribute-card lane', 820, 'normal', 'ltr', 0, 'segments-no-match', '{"state":"segments-no-match"}'::jsonb, 140, TRUE),
    ('DSR-015', 'RTL descriptive open drawer review', 'RTL open-state review keeps the child seam structure intact while mirroring directionality.', '/design-system/canonical-renderings/drawer-select/DSR-015', '/design-system/components/drawer-select?ref=DSR-015&width=940&state=collections-open&theme=normal&dir=rtl&zoom=0', 'Parent field lane', 940, 'normal', 'rtl', 0, 'collections-open', '{"state":"collections-open"}'::jsonb, 150, TRUE),
    ('DSR-016', 'Dark and magnified compact open review', 'Dark-theme magnified review keeps the compact drawer legible while preserving the same core seam structure.', '/design-system/canonical-renderings/drawer-select/DSR-016', '/design-system/components/drawer-select?ref=DSR-016&width=820&state=segments-open&theme=dark&dir=ltr&zoom=100', 'Magnified compact attribute-card lane', 820, 'dark', 'ltr', 100, 'segments-open', '{"state":"segments-open"}'::jsonb, 160, TRUE),
    ('DSR-017', 'Mobile descriptive open drawer review', 'Mobile descriptive review keeps the drawer in a narrow overlay posture while preserving the same search-first open contract.', '/design-system/canonical-renderings/drawer-select/DSR-017', '/design-system/components/drawer-select?ref=DSR-017&width=390&state=collections-open&theme=normal&dir=ltr&zoom=0', 'Mobile descriptive lane', 390, 'normal', 'ltr', 0, 'collections-open', '{"state":"collections-open"}'::jsonb, 170, TRUE),
    ('DSR-018', 'Mobile compact open drawer review', 'Mobile compact review keeps the attribute-card variant readable in the narrow overlay posture.', '/design-system/canonical-renderings/drawer-select/DSR-018', '/design-system/components/drawer-select?ref=DSR-018&width=390&state=segments-open&theme=normal&dir=ltr&zoom=0', 'Mobile compact attribute-card lane', 390, 'normal', 'ltr', 0, 'segments-open', '{"state":"segments-open"}'::jsonb, 180, TRUE),
    ('DSR-019', 'Descriptive open drawer with long-label stress', 'Long-label descriptive review keeps summary, selected chips, and available options readable without collapsing the drawer structure.', '/design-system/canonical-renderings/drawer-select/DSR-019', '/design-system/components/drawer-select?ref=DSR-019&width=940&state=collections-open-long&theme=normal&dir=ltr&zoom=0', 'Parent field lane', 940, 'normal', 'ltr', 0, 'collections-open-long', '{"state":"collections-open-long"}'::jsonb, 190, TRUE),
    ('DSR-020', 'Compact open drawer with long-label stress', 'Long-label compact review proves the denser attribute-card variant still stays readable under extended labels and attributes.', '/design-system/canonical-renderings/drawer-select/DSR-020', '/design-system/components/drawer-select?ref=DSR-020&width=820&state=segments-open-long&theme=normal&dir=ltr&zoom=0', 'Compact attribute-card lane', 820, 'normal', 'ltr', 0, 'segments-open-long', '{"state":"segments-open-long"}'::jsonb, 200, TRUE),
    ('DSR-021', 'Localized RTL descriptive open drawer review', 'Localized RTL descriptive review keeps child-owned text, headings, and option rows coherent under translated copy.', '/design-system/canonical-renderings/drawer-select/DSR-021', '/design-system/components/drawer-select?ref=DSR-021&width=940&state=collections-open-localized&theme=normal&dir=rtl&zoom=0', 'Parent field lane', 940, 'normal', 'rtl', 0, 'collections-open-localized', '{"state":"collections-open-localized"}'::jsonb, 210, TRUE),
    ('DSR-022', 'Localized RTL compact open drawer review', 'Localized RTL compact review keeps dense card content legible under translated labels and attribute copy.', '/design-system/canonical-renderings/drawer-select/DSR-022', '/design-system/components/drawer-select?ref=DSR-022&width=820&state=segments-open-localized&theme=normal&dir=rtl&zoom=0', 'Compact attribute-card lane', 820, 'normal', 'rtl', 0, 'segments-open-localized', '{"state":"segments-open-localized"}'::jsonb, 220, TRUE),
    ('DSR-023', 'Disabled descriptive resting review', 'Disabled descriptive resting review keeps the hosted trigger truthful while blocking interaction in inherited disabled mode.', '/design-system/canonical-renderings/drawer-select/DSR-023', '/design-system/components/drawer-select?ref=DSR-023&width=940&state=collections-resting-disabled&theme=normal&dir=ltr&zoom=0', 'Parent field lane', 940, 'normal', 'ltr', 0, 'collections-resting-disabled', '{"state":"collections-resting-disabled"}'::jsonb, 230, TRUE),
    ('DSR-024', 'Disabled compact resting review', 'Disabled compact resting review keeps the denser trigger readable while honoring inherited disabled mode.', '/design-system/canonical-renderings/drawer-select/DSR-024', '/design-system/components/drawer-select?ref=DSR-024&width=820&state=segments-resting-disabled&theme=normal&dir=ltr&zoom=0', 'Compact attribute-card lane', 820, 'normal', 'ltr', 0, 'segments-resting-disabled', '{"state":"segments-resting-disabled"}'::jsonb, 240, TRUE),
    ('DSR-025', 'Dark compact open review', 'Dark compact review isolates theme stress without magnification so approved-host parity can compare the actual dark seam directly.', '/design-system/canonical-renderings/drawer-select/DSR-025', '/design-system/components/drawer-select?ref=DSR-025&width=820&state=segments-open-dark&theme=dark&dir=ltr&zoom=0', 'Compact attribute-card lane', 820, 'dark', 'ltr', 0, 'segments-open-dark', '{"state":"segments-open-dark"}'::jsonb, 250, TRUE),
    ('DSR-026', 'Dark mobile descriptive open drawer review', 'Dark mobile descriptive review keeps the narrow overlay posture legible under dark theme treatment.', '/design-system/canonical-renderings/drawer-select/DSR-026', '/design-system/components/drawer-select?ref=DSR-026&width=390&state=collections-open-mobile-dark&theme=dark&dir=ltr&zoom=0', 'Mobile descriptive lane', 390, 'dark', 'ltr', 0, 'collections-open-mobile-dark', '{"state":"collections-open-mobile-dark"}'::jsonb, 260, TRUE),
    ('DSR-027', 'Dark mobile compact open drawer review', 'Dark mobile compact review keeps the denser overlay readable under the narrowest dark-theme posture.', '/design-system/canonical-renderings/drawer-select/DSR-027', '/design-system/components/drawer-select?ref=DSR-027&width=390&state=segments-open-mobile-dark&theme=dark&dir=ltr&zoom=0', 'Mobile compact attribute-card lane', 390, 'dark', 'ltr', 0, 'segments-open-mobile-dark', '{"state":"segments-open-mobile-dark"}'::jsonb, 270, TRUE)
)
INSERT INTO design_system_canonical_references (
  design_system_canonical_reference_id,
  design_system_canonical_family_id,
  reference_id,
  normalized_reference_id,
  display_label,
  description,
  render_route_path,
  legacy_render_route_path,
  viewport,
  width,
  height,
  theme,
  direction,
  zoom,
  locale_fixture,
  label_density_fixture,
  state_variant_key,
  specimen_payload,
  status,
  sort_order,
  featured,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  drawer_select_family.design_system_canonical_family_id,
  reference_rows.reference_id,
  lower(reference_rows.reference_id),
  reference_rows.display_label,
  reference_rows.description,
  reference_rows.render_route_path,
  reference_rows.legacy_render_route_path,
  reference_rows.viewport,
  reference_rows.width,
  NULL,
  reference_rows.theme,
  reference_rows.direction,
  reference_rows.zoom,
  NULL,
  NULL,
  reference_rows.state_variant_key,
  reference_rows.specimen_payload,
  'live',
  reference_rows.sort_order,
  reference_rows.featured,
  NOW(),
  NOW()
FROM reference_rows
CROSS JOIN drawer_select_family
ON CONFLICT (design_system_canonical_family_id, normalized_reference_id)
DO UPDATE SET
  display_label = EXCLUDED.display_label,
  description = EXCLUDED.description,
  render_route_path = EXCLUDED.render_route_path,
  legacy_render_route_path = EXCLUDED.legacy_render_route_path,
  viewport = EXCLUDED.viewport,
  width = EXCLUDED.width,
  height = EXCLUDED.height,
  theme = EXCLUDED.theme,
  direction = EXCLUDED.direction,
  zoom = EXCLUDED.zoom,
  locale_fixture = EXCLUDED.locale_fixture,
  label_density_fixture = EXCLUDED.label_density_fixture,
  state_variant_key = EXCLUDED.state_variant_key,
  specimen_payload = EXCLUDED.specimen_payload,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  featured = EXCLUDED.featured,
  updated_at = NOW();
