WITH family_rows (
  design_system_canonical_family_id,
  family_key,
  normalized_family_key,
  display_label,
  family_kind,
  launcher_title,
  launcher_description,
  launcher_category,
  generated_launcher_route_path,
  legacy_launcher_route_path,
  source_surface_route_path,
  sort_order,
  featured
) AS (
  VALUES
    ('8fe182de-7f28-4d60-bc27-1fb723f83001'::uuid, 'list-record-card', 'list-record-card', 'List Record Card', 'component', 'List Record Card Canonical Renderings', 'Persistence-backed launcher for the signed-off list-record-card canonical renderings.', 'data-display', '/design-system/canonical-renderings/list-record-card', '/design-system/canonicals/list-record-card', '/design-system/components/list-record-card', 70, FALSE),
    ('8fe182de-7f28-4d60-bc27-1fb723f83002'::uuid, 'list-detail-panel', 'list-detail-panel', 'List Detail Panel', 'component', 'List Detail Panel Canonical Renderings', 'Persistence-backed launcher for the signed-off list-detail-panel canonical renderings.', 'data-display', '/design-system/canonical-renderings/list-detail-panel', '/design-system/canonicals/list-detail-panel', '/design-system/components/list-detail-panel', 80, FALSE),
    ('8fe182de-7f28-4d60-bc27-1fb723f83003'::uuid, 'list-detail-split-layout', 'list-detail-split-layout', 'List Detail Split Layout', 'component', 'List Detail Split Layout Canonical Renderings', 'Persistence-backed launcher for the signed-off list-detail-split-layout canonical renderings.', 'data-display', '/design-system/canonical-renderings/list-detail-split-layout', '/design-system/canonicals/list-detail-split-layout', '/design-system/components/list-detail-split-layout', 90, FALSE)
)
INSERT INTO design_system_canonical_families (
  design_system_canonical_family_id,
  family_key,
  normalized_family_key,
  display_label,
  family_kind,
  launcher_title,
  launcher_description,
  launcher_category,
  generated_launcher_route_path,
  generated_root_route_path,
  legacy_launcher_route_path,
  source_surface_route_path,
  status,
  sort_order,
  featured,
  created_at,
  updated_at
)
SELECT
  family_rows.design_system_canonical_family_id,
  family_rows.family_key,
  family_rows.normalized_family_key,
  family_rows.display_label,
  family_rows.family_kind,
  family_rows.launcher_title,
  family_rows.launcher_description,
  family_rows.launcher_category,
  family_rows.generated_launcher_route_path,
  '/design-system/canonical-renderings',
  family_rows.legacy_launcher_route_path,
  family_rows.source_surface_route_path,
  'live',
  family_rows.sort_order,
  family_rows.featured,
  NOW(),
  NOW()
FROM family_rows
ON CONFLICT (normalized_family_key)
DO UPDATE SET
  display_label = EXCLUDED.display_label,
  family_kind = EXCLUDED.family_kind,
  launcher_title = EXCLUDED.launcher_title,
  launcher_description = EXCLUDED.launcher_description,
  launcher_category = EXCLUDED.launcher_category,
  generated_launcher_route_path = EXCLUDED.generated_launcher_route_path,
  generated_root_route_path = EXCLUDED.generated_root_route_path,
  legacy_launcher_route_path = EXCLUDED.legacy_launcher_route_path,
  source_surface_route_path = EXCLUDED.source_surface_route_path,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  featured = EXCLUDED.featured,
  updated_at = NOW();

WITH reference_rows (
  normalized_family_key,
  reference_id,
  display_label,
  description,
  render_route_path,
  legacy_render_route_path,
  viewport,
  width,
  theme,
  direction,
  zoom,
  state_variant_key,
  specimen_payload,
  sort_order,
  featured
) AS (
  VALUES
    ('list-record-card', 'LRC-001', 'Desktop baseline full width', 'Baseline neutral record card for full-width list review.', '/design-system/canonical-renderings/list-record-card/LRC-001', '/design-system/components/list-record-card?ref=LRC-001&width=760&state=baseline&theme=normal&dir=ltr&zoom=0', 'Desktop full-width list lane', 760, 'normal', 'ltr', 0, 'baseline', '{"state":"baseline"}'::jsonb, 10, FALSE),
    ('list-record-card', 'LRC-002', 'Desktop selected full width', 'Selected treatment should increase emphasis without changing card geometry.', '/design-system/canonical-renderings/list-record-card/LRC-002', '/design-system/components/list-record-card?ref=LRC-002&width=760&state=selected&theme=normal&dir=ltr&zoom=0', 'Desktop full-width list lane', 760, 'normal', 'ltr', 0, 'selected', '{"state":"selected"}'::jsonb, 20, TRUE),
    ('list-record-card', 'LRC-003', 'Field-mapping placeholder', 'Mapping posture preserves field-label placeholders for future data binding review.', '/design-system/canonical-renderings/list-record-card/LRC-003', '/design-system/components/list-record-card?ref=LRC-003&width=760&state=mapping&theme=normal&dir=ltr&zoom=0', 'Desktop full-width list lane', 760, 'normal', 'ltr', 0, 'mapping', '{"state":"mapping"}'::jsonb, 30, FALSE),
    ('list-record-card', 'LRC-004', 'Missing-attribute fallback', 'Primary fallback should appear without noisy empty-field placeholders.', '/design-system/canonical-renderings/list-record-card/LRC-004', '/design-system/components/list-record-card?ref=LRC-004&width=760&state=missing&theme=normal&dir=ltr&zoom=0', 'Desktop full-width list lane', 760, 'normal', 'ltr', 0, 'missing', '{"state":"missing"}'::jsonb, 40, TRUE),
    ('list-record-card', 'LRC-005', 'Half-page long-content review', 'Compact fields should truncate while summary copy remains readable.', '/design-system/canonical-renderings/list-record-card/LRC-005', '/design-system/components/list-record-card?ref=LRC-005&width=520&state=long&theme=normal&dir=ltr&zoom=0', 'Desktop half-page list lane', 520, 'normal', 'ltr', 0, 'long', '{"state":"long"}'::jsonb, 50, TRUE),
    ('list-record-card', 'LRC-006', 'Mobile narrow review', 'Mobile review should preserve full-width button posture inside a narrow list lane.', '/design-system/canonical-renderings/list-record-card/LRC-006', '/design-system/components/list-record-card?ref=LRC-006&width=360&state=mobile&theme=normal&dir=ltr&zoom=0', 'Mobile list lane', 360, 'normal', 'ltr', 0, 'mobile', '{"state":"mobile"}'::jsonb, 60, TRUE),
    ('list-record-card', 'LRC-007', 'RTL half-page review', 'RTL half-page review keeps direction scoped to the local child surface.', '/design-system/canonical-renderings/list-record-card/LRC-007', '/design-system/components/list-record-card?ref=LRC-007&width=520&state=long&theme=normal&dir=rtl&zoom=0', 'Desktop half-page list lane', 520, 'normal', 'rtl', 0, 'long-rtl', '{"state":"long"}'::jsonb, 70, TRUE),
    ('list-record-card', 'LRC-008', 'Magnified half-page review', 'Magnified half-page review keeps scale scoped to the local child surface.', '/design-system/canonical-renderings/list-record-card/LRC-008', '/design-system/components/list-record-card?ref=LRC-008&width=520&state=long&theme=normal&dir=ltr&zoom=100', 'Desktop half-page list lane', 520, 'normal', 'ltr', 100, 'long-magnified', '{"state":"long"}'::jsonb, 80, TRUE),
    ('list-record-card', 'LRC-009', 'Theme baseline normal', 'Normal-theme baseline for local theme-scope comparison.', '/design-system/canonical-renderings/list-record-card/LRC-009', '/design-system/components/list-record-card?ref=LRC-009&width=760&state=baseline&theme=normal&dir=ltr&zoom=0', 'Desktop full-width list lane', 760, 'normal', 'ltr', 0, 'baseline-normal', '{"state":"baseline"}'::jsonb, 90, FALSE),
    ('list-record-card', 'LRC-010', 'Theme baseline dark', 'Dark-theme baseline keeps card text and stage chrome readable.', '/design-system/canonical-renderings/list-record-card/LRC-010', '/design-system/components/list-record-card?ref=LRC-010&width=760&state=baseline&theme=dark&dir=ltr&zoom=0', 'Desktop full-width list lane', 760, 'dark', 'ltr', 0, 'baseline-dark', '{"state":"baseline"}'::jsonb, 100, TRUE),
    ('list-record-card', 'LRC-011', 'Theme baseline desert', 'Desert-theme baseline keeps card text and stage chrome readable.', '/design-system/canonical-renderings/list-record-card/LRC-011', '/design-system/components/list-record-card?ref=LRC-011&width=760&state=baseline&theme=desert&dir=ltr&zoom=0', 'Desktop full-width list lane', 760, 'desert', 'ltr', 0, 'baseline-desert', '{"state":"baseline"}'::jsonb, 110, TRUE),

    ('list-detail-panel', 'LDP-001', 'Desktop baseline populated panel', 'Baseline populated panel preserves the signed-off header, body, and footer zones.', '/design-system/canonical-renderings/list-detail-panel/LDP-001', '/design-system/components/list-detail-panel?ref=LDP-001&width=760&state=baseline&theme=normal&dir=ltr&zoom=0', 'Desktop detail lane', 760, 'normal', 'ltr', 0, 'baseline', '{"state":"baseline"}'::jsonb, 10, TRUE),
    ('list-detail-panel', 'LDP-002', 'Missing secondary fields', 'Missing-secondary-fields review omits empty chrome while preserving body readability.', '/design-system/canonical-renderings/list-detail-panel/LDP-002', '/design-system/components/list-detail-panel?ref=LDP-002&width=760&state=missing&theme=normal&dir=ltr&zoom=0', 'Desktop detail lane', 760, 'normal', 'ltr', 0, 'missing', '{"state":"missing"}'::jsonb, 20, FALSE),
    ('list-detail-panel', 'LDP-003', 'Local detail error state', 'Local error review keeps the problem inside the detail panel rather than collapsing the surrounding layout.', '/design-system/canonical-renderings/list-detail-panel/LDP-003', '/design-system/components/list-detail-panel?ref=LDP-003&width=760&state=error&theme=normal&dir=ltr&zoom=0', 'Desktop detail lane', 760, 'normal', 'ltr', 0, 'error', '{"state":"error"}'::jsonb, 30, FALSE),
    ('list-detail-panel', 'LDP-004', 'Terminal footer boundary', 'Terminal footer review keeps previous available while next is honestly disabled.', '/design-system/canonical-renderings/list-detail-panel/LDP-004', '/design-system/components/list-detail-panel?ref=LDP-004&width=760&state=boundary&theme=normal&dir=ltr&zoom=0', 'Desktop detail lane', 760, 'normal', 'ltr', 0, 'boundary', '{"state":"boundary"}'::jsonb, 40, FALSE),
    ('list-detail-panel', 'LDP-005', 'Half-page long-content review', 'Half-page long-content review keeps metadata truncation and body scroll stable.', '/design-system/canonical-renderings/list-detail-panel/LDP-005', '/design-system/components/list-detail-panel?ref=LDP-005&width=520&state=long&theme=normal&dir=ltr&zoom=0', 'Desktop half-page detail lane', 520, 'normal', 'ltr', 0, 'long', '{"state":"long"}'::jsonb, 50, TRUE),
    ('list-detail-panel', 'LDP-006', 'Mobile narrow stack review', 'Mobile narrow review keeps the header compact and action row usable.', '/design-system/canonical-renderings/list-detail-panel/LDP-006', '/design-system/components/list-detail-panel?ref=LDP-006&width=360&state=mobile&theme=normal&dir=ltr&zoom=0', 'Mobile detail lane', 360, 'normal', 'ltr', 0, 'mobile', '{"state":"mobile"}'::jsonb, 60, TRUE),
    ('list-detail-panel', 'LDP-007', 'RTL half-page review', 'RTL half-page review keeps direction scoped to the local child surface.', '/design-system/canonical-renderings/list-detail-panel/LDP-007', '/design-system/components/list-detail-panel?ref=LDP-007&width=520&state=long&theme=normal&dir=rtl&zoom=0', 'Desktop half-page detail lane', 520, 'normal', 'rtl', 0, 'long-rtl', '{"state":"long"}'::jsonb, 70, FALSE),
    ('list-detail-panel', 'LDP-008', 'Magnified half-page review', 'Magnified half-page review keeps scale scoped to the local child surface.', '/design-system/canonical-renderings/list-detail-panel/LDP-008', '/design-system/components/list-detail-panel?ref=LDP-008&width=520&state=long&theme=normal&dir=ltr&zoom=100', 'Desktop half-page detail lane', 520, 'normal', 'ltr', 100, 'long-magnified', '{"state":"long"}'::jsonb, 80, FALSE),
    ('list-detail-panel', 'LDP-009', 'Focus-entry close control review', 'Focus-entry review starts on the close control without shifting panel geometry.', '/design-system/canonical-renderings/list-detail-panel/LDP-009', '/design-system/components/list-detail-panel?ref=LDP-009&width=760&state=focus-close&theme=normal&dir=ltr&zoom=0', 'Desktop detail lane', 760, 'normal', 'ltr', 0, 'focus-close', '{"state":"focus-close"}'::jsonb, 90, TRUE),
    ('list-detail-panel', 'LDP-010', 'Theme baseline dark', 'Dark-theme baseline keeps panel text and stage chrome readable.', '/design-system/canonical-renderings/list-detail-panel/LDP-010', '/design-system/components/list-detail-panel?ref=LDP-010&width=760&state=baseline&theme=dark&dir=ltr&zoom=0', 'Desktop detail lane', 760, 'dark', 'ltr', 0, 'baseline-dark', '{"state":"baseline"}'::jsonb, 100, FALSE),
    ('list-detail-panel', 'LDP-011', 'Theme baseline desert', 'Desert-theme baseline keeps panel text and stage chrome readable.', '/design-system/canonical-renderings/list-detail-panel/LDP-011', '/design-system/components/list-detail-panel?ref=LDP-011&width=760&state=baseline&theme=desert&dir=ltr&zoom=0', 'Desktop detail lane', 760, 'desert', 'ltr', 0, 'baseline-desert', '{"state":"baseline"}'::jsonb, 110, FALSE),

    ('list-detail-split-layout', 'LDSL-001', 'Desktop closed baseline', 'Closed desktop baseline keeps the page as a single list lane.', '/design-system/canonical-renderings/list-detail-split-layout/LDSL-001', '/design-system/components/list-detail-split-layout?ref=LDSL-001&width=1080&state=closed&theme=normal&dir=ltr&zoom=0', 'Desktop single-lane preview', 1080, 'normal', 'ltr', 0, 'closed', '{"state":"closed"}'::jsonb, 10, TRUE),
    ('list-detail-split-layout', 'LDSL-002', 'Desktop open split baseline', 'Open desktop baseline proves the pushed two-lane split relationship.', '/design-system/canonical-renderings/list-detail-split-layout/LDSL-002', '/design-system/components/list-detail-split-layout?ref=LDSL-002&width=1080&state=open&theme=normal&dir=ltr&zoom=0', 'Desktop split preview', 1080, 'normal', 'ltr', 0, 'open', '{"state":"open"}'::jsonb, 20, TRUE),
    ('list-detail-split-layout', 'LDSL-003', 'Independent scroll-lane pressure', 'Scroll-pressure review keeps list and detail lanes independently readable.', '/design-system/canonical-renderings/list-detail-split-layout/LDSL-003', '/design-system/components/list-detail-split-layout?ref=LDSL-003&width=1080&state=scroll&theme=normal&dir=ltr&zoom=0', 'Desktop split preview', 1080, 'normal', 'ltr', 0, 'scroll', '{"state":"scroll"}'::jsonb, 30, TRUE),
    ('list-detail-split-layout', 'LDSL-004', 'Mobile full-sheet overlay', 'Mobile review treats the detail lane as an overlay inside the seam preview.', '/design-system/canonical-renderings/list-detail-split-layout/LDSL-004', '/design-system/components/list-detail-split-layout?ref=LDSL-004&width=390&state=mobile&theme=normal&dir=ltr&zoom=0', 'Mobile overlay preview', 390, 'normal', 'ltr', 0, 'mobile', '{"state":"mobile"}'::jsonb, 40, TRUE),
    ('list-detail-split-layout', 'LDSL-005', 'Mobile overlay beneath shell chrome', 'Mobile layering review keeps the overlay below shell chrome.', '/design-system/canonical-renderings/list-detail-split-layout/LDSL-005', '/design-system/components/list-detail-split-layout?ref=LDSL-005&width=390&state=mobile-layering&theme=normal&dir=ltr&zoom=0', 'Mobile overlay preview', 390, 'normal', 'ltr', 0, 'mobile-layering', '{"state":"mobile-layering"}'::jsonb, 50, FALSE),
    ('list-detail-split-layout', 'LDSL-006', 'RTL desktop split review', 'RTL desktop review mirrors the split relationship while preserving lane clarity.', '/design-system/canonical-renderings/list-detail-split-layout/LDSL-006', '/design-system/components/list-detail-split-layout?ref=LDSL-006&width=1080&state=open&theme=normal&dir=rtl&zoom=0', 'Desktop split preview', 1080, 'normal', 'rtl', 0, 'open-rtl', '{"state":"open"}'::jsonb, 60, TRUE),
    ('list-detail-split-layout', 'LDSL-007', 'Magnified half-page split review', 'Magnified half-page review keeps the split readable under local scale pressure.', '/design-system/canonical-renderings/list-detail-split-layout/LDSL-007', '/design-system/components/list-detail-split-layout?ref=LDSL-007&width=820&state=zoom&theme=normal&dir=ltr&zoom=100', 'Half-page split preview', 820, 'normal', 'ltr', 100, 'zoom', '{"state":"zoom"}'::jsonb, 70, TRUE),
    ('list-detail-split-layout', 'LDSL-008', 'Theme baseline dark', 'Dark-theme baseline keeps split lanes and stage chrome readable.', '/design-system/canonical-renderings/list-detail-split-layout/LDSL-008', '/design-system/components/list-detail-split-layout?ref=LDSL-008&width=1080&state=open&theme=dark&dir=ltr&zoom=0', 'Desktop split preview', 1080, 'dark', 'ltr', 0, 'open-dark', '{"state":"open"}'::jsonb, 80, FALSE),
    ('list-detail-split-layout', 'LDSL-009', 'Theme baseline desert', 'Desert-theme baseline keeps split lanes and stage chrome readable.', '/design-system/canonical-renderings/list-detail-split-layout/LDSL-009', '/design-system/components/list-detail-split-layout?ref=LDSL-009&width=1080&state=open&theme=desert&dir=ltr&zoom=0', 'Desktop split preview', 1080, 'desert', 'ltr', 0, 'open-desert', '{"state":"open"}'::jsonb, 90, FALSE),
    ('list-detail-split-layout', 'LDSL-010', 'Squashed split fallback review', 'Non-mobile split falls back to overlay when both lanes would become too cramped.', '/design-system/canonical-renderings/list-detail-split-layout/LDSL-010', '/design-system/components/list-detail-split-layout?ref=LDSL-010&width=720&state=squashed&theme=normal&dir=ltr&zoom=100', 'Half-page overlay fallback preview', 720, 'normal', 'ltr', 100, 'squashed', '{"state":"squashed"}'::jsonb, 100, TRUE)
),
canonical_families AS (
  SELECT design_system_canonical_family_id, normalized_family_key
  FROM design_system_canonical_families
  WHERE normalized_family_key IN ('list-record-card', 'list-detail-panel', 'list-detail-split-layout')
)
INSERT INTO design_system_canonical_references (
  design_system_canonical_reference_id,
  design_system_canonical_family_id,
  reference_id,
  normalized_reference_id,
  display_label,
  description,
  render_route_path,
  legacy_render_route_path,
  viewport,
  width,
  height,
  theme,
  direction,
  zoom,
  locale_fixture,
  label_density_fixture,
  state_variant_key,
  specimen_payload,
  status,
  sort_order,
  featured,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  canonical_families.design_system_canonical_family_id,
  reference_rows.reference_id,
  lower(reference_rows.reference_id),
  reference_rows.display_label,
  reference_rows.description,
  reference_rows.render_route_path,
  reference_rows.legacy_render_route_path,
  reference_rows.viewport,
  reference_rows.width,
  NULL,
  reference_rows.theme,
  reference_rows.direction,
  reference_rows.zoom,
  NULL,
  NULL,
  reference_rows.state_variant_key,
  reference_rows.specimen_payload,
  'live',
  reference_rows.sort_order,
  reference_rows.featured,
  NOW(),
  NOW()
FROM reference_rows
JOIN canonical_families
  ON canonical_families.normalized_family_key = reference_rows.normalized_family_key
ON CONFLICT (design_system_canonical_family_id, normalized_reference_id)
DO UPDATE SET
  display_label = EXCLUDED.display_label,
  description = EXCLUDED.description,
  render_route_path = EXCLUDED.render_route_path,
  legacy_render_route_path = EXCLUDED.legacy_render_route_path,
  viewport = EXCLUDED.viewport,
  width = EXCLUDED.width,
  height = EXCLUDED.height,
  theme = EXCLUDED.theme,
  direction = EXCLUDED.direction,
  zoom = EXCLUDED.zoom,
  locale_fixture = EXCLUDED.locale_fixture,
  label_density_fixture = EXCLUDED.label_density_fixture,
  state_variant_key = EXCLUDED.state_variant_key,
  specimen_payload = EXCLUDED.specimen_payload,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  featured = EXCLUDED.featured,
  updated_at = NOW();
