WITH family_rows (
  design_system_canonical_family_id,
  family_key,
  normalized_family_key,
  display_label,
  family_kind,
  launcher_title,
  launcher_description,
  launcher_category,
  generated_launcher_route_path,
  legacy_launcher_route_path,
  source_surface_route_path,
  sort_order,
  featured
) AS (
  VALUES
    (
      '8fe182de-7f28-4d60-bc27-1fb723f83904'::uuid,
      'async-activity-drawer',
      'async-activity-drawer',
      'Async Activity Drawer',
      'component',
      'Async Activity Drawer Canonical Renderings',
      'Persistence-backed launcher for the governed async activity drawer states.',
      'shell',
      '/design-system/canonical-renderings/async-activity-drawer',
      '/design-system/canonicals/async-activity-drawer',
      '/design-system/components/async-activity-drawer',
      65,
      FALSE
    )
)
INSERT INTO design_system_canonical_families (
  design_system_canonical_family_id,
  family_key,
  normalized_family_key,
  display_label,
  family_kind,
  launcher_title,
  launcher_description,
  launcher_category,
  generated_launcher_route_path,
  generated_root_route_path,
  legacy_launcher_route_path,
  source_surface_route_path,
  status,
  sort_order,
  featured,
  created_at,
  updated_at
)
SELECT
  family_rows.design_system_canonical_family_id,
  family_rows.family_key,
  family_rows.normalized_family_key,
  family_rows.display_label,
  family_rows.family_kind,
  family_rows.launcher_title,
  family_rows.launcher_description,
  family_rows.launcher_category,
  family_rows.generated_launcher_route_path,
  '/design-system/canonical-renderings',
  family_rows.legacy_launcher_route_path,
  family_rows.source_surface_route_path,
  'live',
  family_rows.sort_order,
  family_rows.featured,
  NOW(),
  NOW()
FROM family_rows
ON CONFLICT (normalized_family_key)
DO UPDATE SET
  display_label = EXCLUDED.display_label,
  family_kind = EXCLUDED.family_kind,
  launcher_title = EXCLUDED.launcher_title,
  launcher_description = EXCLUDED.launcher_description,
  launcher_category = EXCLUDED.launcher_category,
  generated_launcher_route_path = EXCLUDED.generated_launcher_route_path,
  generated_root_route_path = EXCLUDED.generated_root_route_path,
  legacy_launcher_route_path = EXCLUDED.legacy_launcher_route_path,
  source_surface_route_path = EXCLUDED.source_surface_route_path,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  featured = EXCLUDED.featured,
  updated_at = NOW();

WITH reference_rows (
  reference_id,
  display_label,
  description,
  render_route_path,
  legacy_render_route_path,
  viewport,
  width,
  height,
  theme,
  direction,
  zoom,
  state_variant_key,
  specimen_payload,
  sort_order,
  featured
) AS (
  VALUES
    (
      'AADR-001',
      'Mixed shell queue',
      'Shows running, waiting, retryable error, and completed report states together.',
      '/design-system/canonical-renderings/async-activity-drawer/AADR-001',
      '/design-system/components/async-activity-drawer/AADR-001',
      'Desktop shell drawer',
      1120,
      760,
      'normal',
      'ltr',
      0,
      'mixed-queue',
      '{"states":["running","waiting","error","complete"]}'::jsonb,
      10,
      TRUE
    ),
    (
      'AADR-002',
      'Running job',
      'Confirms active progress presentation and running status semantics.',
      '/design-system/canonical-renderings/async-activity-drawer/AADR-002',
      '/design-system/components/async-activity-drawer/AADR-002',
      'Desktop shell drawer',
      1120,
      760,
      'normal',
      'ltr',
      0,
      'running',
      '{"states":["running"]}'::jsonb,
      20,
      FALSE
    ),
    (
      'AADR-003',
      'Waiting job',
      'Confirms queued work remains visible without implying completion.',
      '/design-system/canonical-renderings/async-activity-drawer/AADR-003',
      '/design-system/components/async-activity-drawer/AADR-003',
      'Desktop shell drawer',
      1120,
      760,
      'normal',
      'ltr',
      0,
      'waiting',
      '{"states":["waiting"]}'::jsonb,
      30,
      FALSE
    ),
    (
      'AADR-004',
      'Retryable error',
      'Confirms stopped progress, error detail, and retry action.',
      '/design-system/canonical-renderings/async-activity-drawer/AADR-004',
      '/design-system/components/async-activity-drawer/AADR-004',
      'Desktop shell drawer',
      1120,
      760,
      'normal',
      'ltr',
      0,
      'retryable-error',
      '{"states":["error"],"retry":true}'::jsonb,
      40,
      TRUE
    ),
    (
      'AADR-005',
      'Complete with report',
      'Confirms successful and failed result counts plus optional CSV report download.',
      '/design-system/canonical-renderings/async-activity-drawer/AADR-005',
      '/design-system/components/async-activity-drawer/AADR-005',
      'Desktop shell drawer',
      1120,
      760,
      'normal',
      'ltr',
      0,
      'complete-report',
      '{"states":["complete"],"report":true}'::jsonb,
      50,
      TRUE
    )
),
async_activity_drawer_family AS (
  SELECT design_system_canonical_family_id
  FROM design_system_canonical_families
  WHERE normalized_family_key = 'async-activity-drawer'
)
INSERT INTO design_system_canonical_references (
  design_system_canonical_reference_id,
  design_system_canonical_family_id,
  reference_id,
  normalized_reference_id,
  display_label,
  description,
  render_route_path,
  legacy_render_route_path,
  viewport,
  width,
  height,
  theme,
  direction,
  zoom,
  locale_fixture,
  label_density_fixture,
  state_variant_key,
  specimen_payload,
  status,
  sort_order,
  featured,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  async_activity_drawer_family.design_system_canonical_family_id,
  reference_rows.reference_id,
  lower(reference_rows.reference_id),
  reference_rows.display_label,
  reference_rows.description,
  reference_rows.render_route_path,
  reference_rows.legacy_render_route_path,
  reference_rows.viewport,
  reference_rows.width,
  reference_rows.height,
  reference_rows.theme,
  reference_rows.direction,
  reference_rows.zoom,
  NULL,
  NULL,
  reference_rows.state_variant_key,
  reference_rows.specimen_payload,
  'live',
  reference_rows.sort_order,
  reference_rows.featured,
  NOW(),
  NOW()
FROM reference_rows
CROSS JOIN async_activity_drawer_family
ON CONFLICT (design_system_canonical_family_id, normalized_reference_id)
DO UPDATE SET
  display_label = EXCLUDED.display_label,
  description = EXCLUDED.description,
  render_route_path = EXCLUDED.render_route_path,
  legacy_render_route_path = EXCLUDED.legacy_render_route_path,
  viewport = EXCLUDED.viewport,
  width = EXCLUDED.width,
  height = EXCLUDED.height,
  theme = EXCLUDED.theme,
  direction = EXCLUDED.direction,
  zoom = EXCLUDED.zoom,
  locale_fixture = EXCLUDED.locale_fixture,
  label_density_fixture = EXCLUDED.label_density_fixture,
  state_variant_key = EXCLUDED.state_variant_key,
  specimen_payload = EXCLUDED.specimen_payload,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  featured = EXCLUDED.featured,
  updated_at = NOW();
