INSERT INTO design_system_canonical_families (
  design_system_canonical_family_id,
  family_key,
  normalized_family_key,
  display_label,
  family_kind,
  launcher_title,
  launcher_description,
  launcher_category,
  generated_launcher_route_path,
  generated_root_route_path,
  legacy_launcher_route_path,
  source_surface_route_path,
  status,
  sort_order,
  featured,
  created_at,
  updated_at
)
VALUES (
  '8fe182de-7f28-4d60-bc27-1fb723f83004'::uuid,
  'hierarchy-tree',
  'hierarchy-tree',
  'Hierarchy Tree',
  'pattern',
  'Hierarchy Tree Canonical Renderings',
  'Persistence-backed launcher for the signed-off hierarchy-tree canonical renderings.',
  'data-display',
  '/design-system/canonical-renderings/hierarchy-tree',
  '/design-system/canonical-renderings',
  '/design-system/canonicals/hierarchy-tree',
  '/design-system/patterns/hierarchy-tree',
  'live',
  95,
  FALSE,
  NOW(),
  NOW()
)
ON CONFLICT (normalized_family_key)
DO UPDATE SET
  display_label = EXCLUDED.display_label,
  family_kind = EXCLUDED.family_kind,
  launcher_title = EXCLUDED.launcher_title,
  launcher_description = EXCLUDED.launcher_description,
  launcher_category = EXCLUDED.launcher_category,
  generated_launcher_route_path = EXCLUDED.generated_launcher_route_path,
  generated_root_route_path = EXCLUDED.generated_root_route_path,
  legacy_launcher_route_path = EXCLUDED.legacy_launcher_route_path,
  source_surface_route_path = EXCLUDED.source_surface_route_path,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  featured = EXCLUDED.featured,
  updated_at = NOW();

WITH reference_rows (
  reference_id,
  display_label,
  state_variant_key,
  width,
  theme,
  direction,
  zoom,
  featured
) AS (
  VALUES
    ('HTR-001', 'Desktop baseline with hierarchy drawer open and tree rows rendered', 'baseline', 1220, 'normal', 'ltr', 0, FALSE),
    ('HTR-002', 'Protected-root scaffold with collapsed non-root branches', 'protected-root-scaffold', 1220, 'normal', 'ltr', 0, FALSE),
    ('HTR-003', 'Expanded branch baseline with parent and child rows visible', 'expanded-branch', 1220, 'normal', 'ltr', 0, FALSE),
    ('HTR-004', 'Deep nesting with compressed indentation', 'deep-nesting', 1220, 'normal', 'ltr', 0, TRUE),
    ('HTR-005', 'Diverged current and selected state', 'diverged-selection', 1220, 'normal', 'ltr', 0, TRUE),
    ('HTR-006', 'Current and selected aligned on the same row', 'aligned-selection', 1220, 'normal', 'ltr', 0, FALSE),
    ('HTR-007', 'Inline rename active', 'inline-rename', 1220, 'normal', 'ltr', 0, TRUE),
    ('HTR-008', 'New child creation inline under an existing parent', 'add-child-inline', 1220, 'normal', 'ltr', 0, FALSE),
    ('HTR-009', 'New sibling creation inline beside an existing row', 'add-sibling-inline', 1220, 'normal', 'ltr', 0, FALSE),
    ('HTR-010', 'Row menu open with structural actions visible', 'row-menu-open', 1220, 'normal', 'ltr', 0, FALSE),
    ('HTR-011', 'Desktop drag state with visible drop target affordance', 'drag-target', 1220, 'normal', 'ltr', 0, TRUE),
    ('HTR-012', 'Menu-driven move actions without drag', 'menu-move', 1220, 'normal', 'ltr', 0, FALSE),
    ('HTR-013', 'Post-move result with destination parent expanded', 'post-move', 1220, 'normal', 'ltr', 0, FALSE),
    ('HTR-014', 'Delete-decision dialog', 'delete-dialog', 1220, 'normal', 'ltr', 0, TRUE),
    ('HTR-015', 'Delete subtree outcome', 'delete-subtree', 1220, 'normal', 'ltr', 0, FALSE),
    ('HTR-016', 'Delete with move-children outcome', 'delete-move-children', 1220, 'normal', 'ltr', 0, TRUE),
    ('HTR-017', 'Delete with orphan-children outcome', 'delete-orphan-children', 1220, 'normal', 'ltr', 0, FALSE),
    ('HTR-018', 'Desktop hierarchy drawer at minimum practical width', 'resized-narrow', 980, 'normal', 'ltr', 0, FALSE),
    ('HTR-019', 'Desktop wider resized drawer', 'resized-wide', 1440, 'normal', 'ltr', 0, TRUE),
    ('HTR-020', 'Desktop hierarchy plus display-settings side-by-side', 'paired-display-drawer', 1440, 'normal', 'ltr', 0, FALSE),
    ('HTR-021', 'Mobile full-screen hierarchy drawer', 'mobile-fullscreen', 390, 'normal', 'ltr', 0, TRUE),
    ('HTR-022', 'Mobile row-menu structural-edit state', 'mobile-row-menu', 390, 'normal', 'ltr', 0, TRUE),
    ('HTR-023', 'Mobile delete-decision overlay on top of the full-screen drawer', 'mobile-delete-dialog', 390, 'normal', 'ltr', 0, FALSE),
    ('HTR-024', 'RTL mirrored drawer docking', 'rtl-docking', 1220, 'normal', 'rtl', 0, TRUE),
    ('HTR-025', 'RTL deep nesting with mirrored scan order', 'rtl-deep-nesting', 1220, 'normal', 'rtl', 0, FALSE),
    ('HTR-026', 'Dark-theme readability review', 'dark-readability', 1220, 'dark', 'ltr', 0, TRUE),
    ('HTR-027', 'Magnified hierarchy review with row pressure', 'magnified-review', 1220, 'normal', 'ltr', 100, FALSE),
    ('HTR-028', 'Keyboard focus-visible review', 'focus-visible', 1220, 'normal', 'ltr', 0, TRUE),
    ('HTR-029', 'Assistive-technology semantics review state', 'semantics-review', 1220, 'normal', 'ltr', 0, FALSE),
    ('HTR-030', 'Desktop long-title overflow review', 'long-title-overflow', 1220, 'normal', 'ltr', 0, TRUE),
    ('HTR-031', 'Deep-nesting plus long-title overflow review', 'deep-long-title-overflow', 1220, 'normal', 'ltr', 0, FALSE),
    ('HTR-032', 'RTL long-title overflow review', 'rtl-long-title-overflow', 1220, 'normal', 'rtl', 0, FALSE),
    ('HTR-033', 'Inline rename with long-title editing review', 'long-title-rename', 1220, 'normal', 'ltr', 0, TRUE),
    ('HTR-034', 'Changed-state density review across multiple rows', 'changed-density', 1220, 'normal', 'ltr', 0, FALSE)
),
canonical_family AS (
  SELECT design_system_canonical_family_id
  FROM design_system_canonical_families
  WHERE normalized_family_key = 'hierarchy-tree'
)
INSERT INTO design_system_canonical_references (
  design_system_canonical_reference_id,
  design_system_canonical_family_id,
  reference_id,
  normalized_reference_id,
  display_label,
  description,
  render_route_path,
  legacy_render_route_path,
  viewport,
  width,
  height,
  theme,
  direction,
  zoom,
  locale_fixture,
  label_density_fixture,
  state_variant_key,
  specimen_payload,
  status,
  sort_order,
  featured,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  canonical_family.design_system_canonical_family_id,
  reference_rows.reference_id,
  lower(reference_rows.reference_id),
  reference_rows.display_label,
  'Generated hierarchy-tree canonical rendering for ' || reference_rows.state_variant_key || '.',
  '/design-system/canonical-renderings/hierarchy-tree/' || reference_rows.reference_id,
  '/design-system/patterns/hierarchy-tree/render?ref=' || reference_rows.reference_id || '&state=' || reference_rows.state_variant_key || '&width=' || reference_rows.width || '&theme=' || reference_rows.theme || '&dir=' || reference_rows.direction || '&zoom=' || reference_rows.zoom || '&accent=%23635bff',
  CASE
    WHEN reference_rows.width = 390 THEN 'Mobile full-screen hierarchy drawer'
    WHEN reference_rows.width >= 1440 THEN 'Wide desktop hierarchy drawer'
    ELSE 'Desktop hierarchy drawer'
  END,
  reference_rows.width,
  NULL,
  reference_rows.theme,
  reference_rows.direction,
  reference_rows.zoom,
  NULL,
  NULL,
  reference_rows.state_variant_key,
  jsonb_build_object('state', reference_rows.state_variant_key, 'accent', '#635bff'),
  'live',
  row_number() OVER (ORDER BY reference_rows.reference_id) * 10,
  reference_rows.featured,
  NOW(),
  NOW()
FROM reference_rows
CROSS JOIN canonical_family
ON CONFLICT (design_system_canonical_family_id, normalized_reference_id)
DO UPDATE SET
  display_label = EXCLUDED.display_label,
  description = EXCLUDED.description,
  render_route_path = EXCLUDED.render_route_path,
  legacy_render_route_path = EXCLUDED.legacy_render_route_path,
  viewport = EXCLUDED.viewport,
  width = EXCLUDED.width,
  height = EXCLUDED.height,
  theme = EXCLUDED.theme,
  direction = EXCLUDED.direction,
  zoom = EXCLUDED.zoom,
  locale_fixture = EXCLUDED.locale_fixture,
  label_density_fixture = EXCLUDED.label_density_fixture,
  state_variant_key = EXCLUDED.state_variant_key,
  specimen_payload = EXCLUDED.specimen_payload,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  featured = EXCLUDED.featured,
  updated_at = NOW();
