INSERT INTO design_system_canonical_families (
  design_system_canonical_family_id,
  family_key,
  normalized_family_key,
  display_label,
  family_kind,
  launcher_title,
  launcher_description,
  launcher_category,
  generated_launcher_route_path,
  generated_root_route_path,
  legacy_launcher_route_path,
  source_surface_route_path,
  status,
  sort_order,
  featured,
  created_at,
  updated_at
)
VALUES (
  '7e71c141-3b7d-45ed-9c6a-df837c955401',
  'floating-tab-header',
  'floating-tab-header',
  'Floating Tab Header',
  'component',
  'Floating Tab Header Canonical Renderings',
  'Persistence-backed launcher for the floating-tab-header canonical renderings.',
  'navigation',
  '/design-system/canonical-renderings/floating-tab-header',
  '/design-system/canonical-renderings',
  '/design-system/components/floating-tab-header',
  '/design-system/components/floating-tab-header',
  'live',
  63,
  FALSE,
  NOW(),
  NOW()
)
ON CONFLICT (normalized_family_key)
DO UPDATE SET
  display_label = EXCLUDED.display_label,
  family_kind = EXCLUDED.family_kind,
  launcher_title = EXCLUDED.launcher_title,
  launcher_description = EXCLUDED.launcher_description,
  launcher_category = EXCLUDED.launcher_category,
  generated_launcher_route_path = EXCLUDED.generated_launcher_route_path,
  generated_root_route_path = EXCLUDED.generated_root_route_path,
  legacy_launcher_route_path = EXCLUDED.legacy_launcher_route_path,
  source_surface_route_path = EXCLUDED.source_surface_route_path,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  featured = EXCLUDED.featured,
  updated_at = NOW();

WITH floating_tab_header_family AS (
  SELECT design_system_canonical_family_id
  FROM design_system_canonical_families
  WHERE normalized_family_key = 'floating-tab-header'
),
reference_rows (
  reference_id,
  display_label,
  description,
  render_route_path,
  legacy_render_route_path,
  viewport,
  width,
  theme,
  direction,
  zoom,
  state_variant_key,
  specimen_payload,
  sort_order,
  featured
) AS (
  VALUES
    ('FTH-R-001', 'Roomy five-tab horizontal baseline', 'Five cards fill the rail without empty trailing space.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-001', '/design-system/components/floating-tab-header?ref=FTH-R-001&tabs=5&layout=horizontal&subTabs=off&attention=off&expandable=off&categorySwitch=on&theme=normal&dir=ltr&zoom=0', 'Desktop full-width rail', 1440, 'normal', 'ltr', 0, 'five-tab-baseline', '{"query":"tabs=5&layout=horizontal&subTabs=off&attention=off&expandable=off&categorySwitch=on&theme=normal&dir=ltr&zoom=0"}'::jsonb, 10, TRUE),
    ('FTH-R-002', 'Crowded ten-tab compact baseline', 'Ten tabs use compact cards without hidden-count summaries.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-002', '/design-system/components/floating-tab-header?ref=FTH-R-002&tabs=10&layout=horizontal&subTabs=off&attention=off&expandable=off&categorySwitch=on&theme=normal&dir=ltr&zoom=0', 'Desktop single-row crowded rail', 1440, 'normal', 'ltr', 0, 'ten-tab-compact', '{"query":"tabs=10&layout=horizontal&subTabs=off&attention=off&expandable=off&categorySwitch=on&theme=normal&dir=ltr&zoom=0"}'::jsonb, 20, TRUE),
    ('FTH-R-003', 'Over-limit start window', 'Right-side hidden count and paging affordance are visible without a native scrollbar.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-003', '/design-system/components/floating-tab-header?ref=FTH-R-003&tabs=12&layout=horizontal&subTabs=off&attention=off&expandable=off&categorySwitch=on&theme=normal&dir=ltr&zoom=0', 'Desktop over-limit start', 1440, 'normal', 'ltr', 0, 'overflow-start', '{"query":"tabs=12&layout=horizontal&subTabs=off&attention=off&expandable=off&categorySwitch=on&theme=normal&dir=ltr&zoom=0"}'::jsonb, 30, TRUE),
    ('FTH-R-004', 'Over-limit middle window', 'Left and right hidden-count summaries are both present with side-specific counts.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-004', '/design-system/components/floating-tab-header?ref=FTH-R-004&tabs=12&layout=horizontal&subTabs=off&attention=off&expandable=off&categorySwitch=on&theme=normal&dir=ltr&zoom=0&windowStart=1', 'Desktop over-limit middle', 1440, 'normal', 'ltr', 0, 'overflow-middle', '{"query":"tabs=12&layout=horizontal&subTabs=off&attention=off&expandable=off&categorySwitch=on&theme=normal&dir=ltr&zoom=0&windowStart=1"}'::jsonb, 40, TRUE),
    ('FTH-R-005', 'Over-limit end window', 'Left-only hidden count remains visible and the right arrow is disabled.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-005', '/design-system/components/floating-tab-header?ref=FTH-R-005&tabs=12&layout=horizontal&subTabs=off&attention=off&expandable=off&categorySwitch=on&theme=normal&dir=ltr&zoom=0&windowStart=3', 'Desktop over-limit end', 1440, 'normal', 'ltr', 0, 'overflow-end', '{"query":"tabs=12&layout=horizontal&subTabs=off&attention=off&expandable=off&categorySwitch=on&theme=normal&dir=ltr&zoom=0&windowStart=3"}'::jsonb, 50, TRUE),
    ('FTH-R-006', 'Double-row slot limit', 'Double-row packing keeps five slots per row and caps the row count at two.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-006', '/design-system/components/floating-tab-header?ref=FTH-R-006&tabs=12&layout=horizontal&rowPacking=double&subTabs=off&attention=off&expandable=off&categorySwitch=on&theme=normal&dir=ltr&zoom=0', 'Desktop double-row rail', 1440, 'normal', 'ltr', 0, 'double-row-limit', '{"query":"tabs=12&layout=horizontal&rowPacking=double&subTabs=off&attention=off&expandable=off&categorySwitch=on&theme=normal&dir=ltr&zoom=0"}'::jsonb, 60, TRUE),
    ('FTH-R-007', 'Horizontal full interaction pressure', 'Subtabs, attention states, control column, arrows, and hidden counts coexist.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-007', '/design-system/components/floating-tab-header?ref=FTH-R-007&tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=on&theme=normal&dir=ltr&zoom=0', 'Desktop full interaction pressure', 1440, 'normal', 'ltr', 0, 'horizontal-pressure', '{"query":"tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=on&theme=normal&dir=ltr&zoom=0"}'::jsonb, 70, TRUE),
    ('FTH-R-008', 'Category drawer open', 'Category drawer is single-select and stays attached to the control column.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-008', '/design-system/components/floating-tab-header?ref=FTH-R-008&tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=on&category=priority&theme=normal&dir=ltr&zoom=0&drawer=open', 'Desktop category drawer open', 1440, 'normal', 'ltr', 0, 'category-drawer-open', '{"query":"tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=on&category=priority&theme=normal&dir=ltr&zoom=0&drawer=open"}'::jsonb, 80, TRUE),
    ('FTH-R-009', 'Collapsed content', 'Collapse hides only the content panel while the header remains available.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-009', '/design-system/components/floating-tab-header?ref=FTH-R-009&tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&collapsed=true&categorySwitch=on&theme=normal&dir=ltr&zoom=0', 'Desktop collapsed content', 1440, 'normal', 'ltr', 0, 'collapsed-content', '{"query":"tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&collapsed=true&categorySwitch=on&theme=normal&dir=ltr&zoom=0"}'::jsonb, 90, TRUE),
    ('FTH-R-010', 'Optional controls off', 'Rail uses the full width when both optional controls are disabled.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-010', '/design-system/components/floating-tab-header?ref=FTH-R-010&tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=off&categorySwitch=off&theme=normal&dir=ltr&zoom=0', 'Desktop optional controls off', 1440, 'normal', 'ltr', 0, 'controls-off', '{"query":"tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=off&categorySwitch=off&theme=normal&dir=ltr&zoom=0"}'::jsonb, 100, FALSE),
    ('FTH-R-011', 'Roomy attention plus subtabs', 'Attention labels stay internal and subtab attention state remains visible.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-011', '/design-system/components/floating-tab-header?ref=FTH-R-011&tabs=5&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=on&theme=normal&dir=ltr&zoom=0', 'Desktop roomy attention', 1440, 'normal', 'ltr', 0, 'roomy-attention', '{"query":"tabs=5&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=on&theme=normal&dir=ltr&zoom=0"}'::jsonb, 110, FALSE),
    ('FTH-R-012', 'Mobile horizontal paging', 'Arrow buttons match card height and scrollbars remain hidden.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-012', '/design-system/components/floating-tab-header?ref=FTH-R-012&tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=on&theme=normal&dir=ltr&zoom=0', 'Mobile horizontal paging', 390, 'normal', 'ltr', 0, 'mobile-horizontal-paging', '{"query":"tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=on&theme=normal&dir=ltr&zoom=0"}'::jsonb, 120, TRUE),
    ('FTH-R-013', 'Vertical long-list attention', 'Vertical tab list scrolls independently while the controls stay grouped.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-013', '/design-system/components/floating-tab-header?ref=FTH-R-013&tabs=12&layout=vertical&attention=on&expandable=on&categorySwitch=on&theme=normal&dir=ltr&zoom=0', 'Mobile vertical long list', 420, 'normal', 'ltr', 0, 'vertical-attention', '{"query":"tabs=12&layout=vertical&attention=on&expandable=on&categorySwitch=on&theme=normal&dir=ltr&zoom=0"}'::jsonb, 130, TRUE),
    ('FTH-R-014', 'Dark theme', 'Dark theme keeps attention, counters, and controls readable.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-014', '/design-system/components/floating-tab-header?ref=FTH-R-014&tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=on&theme=dark&dir=ltr&zoom=0', 'Desktop dark theme', 1440, 'dark', 'ltr', 0, 'dark-theme', '{"query":"tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=on&theme=dark&dir=ltr&zoom=0"}'::jsonb, 140, FALSE),
    ('FTH-R-015', 'Desert theme', 'Desert theme applies through tokens without local color drift.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-015', '/design-system/components/floating-tab-header?ref=FTH-R-015&tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=on&theme=desert&dir=ltr&zoom=0', 'Desktop desert theme', 1440, 'desert', 'ltr', 0, 'desert-theme', '{"query":"tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=on&theme=desert&dir=ltr&zoom=0"}'::jsonb, 150, FALSE),
    ('FTH-R-016', 'RTL horizontal', 'Control column, arrows, summaries, and drawer anchoring mirror.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-016', '/design-system/components/floating-tab-header?ref=FTH-R-016&tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=on&theme=normal&dir=rtl&zoom=0', 'Desktop RTL horizontal', 1440, 'normal', 'rtl', 0, 'rtl-horizontal', '{"query":"tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=on&theme=normal&dir=rtl&zoom=0"}'::jsonb, 160, FALSE),
    ('FTH-R-017', 'Magnified horizontal', 'Magnification keeps text contained without overlapping hidden counts.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-017', '/design-system/components/floating-tab-header?ref=FTH-R-017&tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=on&theme=normal&dir=ltr&zoom=100', 'Tablet magnified horizontal', 1024, 'normal', 'ltr', 100, 'magnified-horizontal', '{"query":"tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=on&theme=normal&dir=ltr&zoom=100"}'::jsonb, 170, FALSE),
    ('FTH-R-018', 'Magnified vertical', 'Magnified vertical attention labels remain internal to each card.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-018', '/design-system/components/floating-tab-header?ref=FTH-R-018&tabs=12&layout=vertical&attention=on&expandable=on&categorySwitch=on&theme=normal&dir=ltr&zoom=100', 'Mobile magnified vertical', 420, 'normal', 'ltr', 100, 'magnified-vertical', '{"query":"tabs=12&layout=vertical&attention=on&expandable=on&categorySwitch=on&theme=normal&dir=ltr&zoom=100"}'::jsonb, 180, FALSE),
    ('FTH-R-019', 'Mobile end paging', 'Left-only summary and disabled right arrow remain visible on a narrow lane.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-019', '/design-system/components/floating-tab-header?ref=FTH-R-019&tabs=12&layout=horizontal&subTabs=off&attention=off&expandable=off&categorySwitch=on&theme=normal&dir=ltr&zoom=0&windowStart=3', 'Mobile end paging', 390, 'normal', 'ltr', 0, 'mobile-end-paging', '{"query":"tabs=12&layout=horizontal&subTabs=off&attention=off&expandable=off&categorySwitch=on&theme=normal&dir=ltr&zoom=0&windowStart=3"}'::jsonb, 190, FALSE),
    ('FTH-R-020', 'Tooltip and focus review', 'Truncated labels use the shared tooltip affordance and unclipped focus styling.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-020', '/design-system/components/floating-tab-header?ref=FTH-R-020&tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=on&theme=normal&dir=ltr&zoom=0&focus=truncated', 'Narrow desktop tooltip focus review', 760, 'normal', 'ltr', 0, 'tooltip-focus', '{"query":"tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=on&theme=normal&dir=ltr&zoom=0&focus=truncated"}'::jsonb, 200, TRUE),
    ('FTH-R-021', 'RTL roomy five-tab baseline', 'Five-card fill rule holds in RTL.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-021', '/design-system/components/floating-tab-header?ref=FTH-R-021&tabs=5&layout=horizontal&subTabs=off&attention=off&expandable=off&categorySwitch=on&theme=normal&dir=rtl&zoom=0', 'Desktop RTL five-tab baseline', 1440, 'normal', 'rtl', 0, 'rtl-five-tab', '{"query":"tabs=5&layout=horizontal&subTabs=off&attention=off&expandable=off&categorySwitch=on&theme=normal&dir=rtl&zoom=0"}'::jsonb, 210, FALSE),
    ('FTH-R-022', 'Category switch off with expand on', 'Expand button occupies the right control column alone.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-022', '/design-system/components/floating-tab-header?ref=FTH-R-022&tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=off&theme=normal&dir=ltr&zoom=0', 'Desktop category switch off', 1440, 'normal', 'ltr', 0, 'category-off-expand-on', '{"query":"tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=off&theme=normal&dir=ltr&zoom=0"}'::jsonb, 220, FALSE),
    ('FTH-R-023', 'Owner category selected', 'Owner category changes labels and counts without changing layout anatomy.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-023', '/design-system/components/floating-tab-header?ref=FTH-R-023&tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=on&category=owner&theme=normal&dir=ltr&zoom=0', 'Desktop owner category selected', 1440, 'normal', 'ltr', 0, 'owner-category', '{"query":"tabs=12&layout=horizontal&subTabs=on&attention=on&expandable=on&categorySwitch=on&category=owner&theme=normal&dir=ltr&zoom=0"}'::jsonb, 230, FALSE),
    ('FTH-R-024', 'Vertical attention hover and clipping review', 'Attention label and hover/focus treatment do not compete with adjacent cards.', '/design-system/canonical-renderings/floating-tab-header/FTH-R-024', '/design-system/components/floating-tab-header?ref=FTH-R-024&tabs=12&layout=vertical&attention=on&expandable=on&categorySwitch=on&theme=normal&dir=ltr&zoom=0&hover=attention', 'Mobile vertical hover clipping review', 420, 'normal', 'ltr', 0, 'vertical-attention-hover', '{"query":"tabs=12&layout=vertical&attention=on&expandable=on&categorySwitch=on&theme=normal&dir=ltr&zoom=0&hover=attention"}'::jsonb, 240, TRUE)
)
INSERT INTO design_system_canonical_references (
  design_system_canonical_reference_id,
  design_system_canonical_family_id,
  reference_id,
  normalized_reference_id,
  display_label,
  description,
  render_route_path,
  legacy_render_route_path,
  viewport,
  width,
  height,
  theme,
  direction,
  zoom,
  locale_fixture,
  label_density_fixture,
  state_variant_key,
  specimen_payload,
  status,
  sort_order,
  featured,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  floating_tab_header_family.design_system_canonical_family_id,
  reference_rows.reference_id,
  lower(reference_rows.reference_id),
  reference_rows.display_label,
  reference_rows.description,
  reference_rows.render_route_path,
  reference_rows.legacy_render_route_path,
  reference_rows.viewport,
  reference_rows.width,
  NULL,
  reference_rows.theme,
  reference_rows.direction,
  reference_rows.zoom,
  NULL,
  NULL,
  reference_rows.state_variant_key,
  reference_rows.specimen_payload,
  'live',
  reference_rows.sort_order,
  reference_rows.featured,
  NOW(),
  NOW()
FROM reference_rows
CROSS JOIN floating_tab_header_family
ON CONFLICT (design_system_canonical_family_id, normalized_reference_id)
DO UPDATE SET
  display_label = EXCLUDED.display_label,
  description = EXCLUDED.description,
  render_route_path = EXCLUDED.render_route_path,
  legacy_render_route_path = EXCLUDED.legacy_render_route_path,
  viewport = EXCLUDED.viewport,
  width = EXCLUDED.width,
  height = EXCLUDED.height,
  theme = EXCLUDED.theme,
  direction = EXCLUDED.direction,
  zoom = EXCLUDED.zoom,
  locale_fixture = EXCLUDED.locale_fixture,
  label_density_fixture = EXCLUDED.label_density_fixture,
  state_variant_key = EXCLUDED.state_variant_key,
  specimen_payload = EXCLUDED.specimen_payload,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  featured = EXCLUDED.featured,
  updated_at = NOW();
