INSERT INTO design_system_canonical_families (
  design_system_canonical_family_id,
  family_key,
  normalized_family_key,
  display_label,
  family_kind,
  launcher_title,
  launcher_description,
  launcher_category,
  generated_launcher_route_path,
  generated_root_route_path,
  legacy_launcher_route_path,
  source_surface_route_path,
  status,
  sort_order,
  featured,
  created_at,
  updated_at
)
VALUES (
  '37e9fa39-8153-4d81-8aaf-d70c8cc51051',
  'chat-workspace-shell',
  'chat-workspace-shell',
  'Chat Workspace Shell',
  'component',
  'Chat Workspace Shell Canonical Renderings',
  'Persistence-backed launcher for the expandable chat workspace shell canonical renderings.',
  'shell',
  '/design-system/canonical-renderings/chat-workspace-shell',
  '/design-system/canonical-renderings',
  '/design-system/patterns/chat-workspace',
  '/design-system/components/chat-workspace-shell',
  'live',
  64,
  FALSE,
  NOW(),
  NOW()
)
ON CONFLICT (normalized_family_key)
DO UPDATE SET
  display_label = EXCLUDED.display_label,
  family_kind = EXCLUDED.family_kind,
  launcher_title = EXCLUDED.launcher_title,
  launcher_description = EXCLUDED.launcher_description,
  launcher_category = EXCLUDED.launcher_category,
  generated_launcher_route_path = EXCLUDED.generated_launcher_route_path,
  generated_root_route_path = EXCLUDED.generated_root_route_path,
  legacy_launcher_route_path = EXCLUDED.legacy_launcher_route_path,
  source_surface_route_path = EXCLUDED.source_surface_route_path,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  featured = EXCLUDED.featured,
  updated_at = NOW();

WITH chat_workspace_shell_family AS (
  SELECT design_system_canonical_family_id
  FROM design_system_canonical_families
  WHERE normalized_family_key = 'chat-workspace-shell'
),
reference_rows (
  reference_id,
  display_label,
  description,
  render_route_path,
  legacy_render_route_path,
  viewport,
  width,
  theme,
  direction,
  zoom,
  state_variant_key,
  specimen_payload,
  sort_order,
  featured
) AS (
  VALUES
    ('CWS-R-001', 'Expansion disabled chat-only default', 'Proves the default component posture has no expansion unless a consuming page opts in.', '/design-system/canonical-renderings/chat-workspace-shell/CWS-R-001', '/design-system/components/chat-workspace-shell?ref=CWS-R-001&state=default&width=896', 'desktop', 896, 'normal', 'ltr', 0, 'default', '{"state":"default","viewportLabel":"desktop"}'::jsonb, 10, TRUE),
    ('CWS-R-002', 'Collapsed right-docked chat', 'Chat remains right docked with the secondary chat selector and full-height tool rail.', '/design-system/canonical-renderings/chat-workspace-shell/CWS-R-002', '/design-system/components/chat-workspace-shell?ref=CWS-R-002&state=collapsed&width=896', 'desktop', 896, 'normal', 'ltr', 0, 'collapsed', '{"state":"collapsed","viewportLabel":"desktop"}'::jsonb, 20, TRUE),
    ('CWS-R-003', 'Collapsed conversation index open', 'The conversation drawer opens left of chat and stays open until the chat selector is pressed again.', '/design-system/canonical-renderings/chat-workspace-shell/CWS-R-003', '/design-system/components/chat-workspace-shell?ref=CWS-R-003&state=index-open&width=1180', 'desktop', 1180, 'normal', 'ltr', 0, 'index-open', '{"state":"index-open","viewportLabel":"desktop"}'::jsonb, 30, TRUE),
    ('CWS-R-004', 'Expanded workspace with index', 'Toolbar, conversation index, scoped entity list, chat pane, and right rail render together.', '/design-system/canonical-renderings/chat-workspace-shell/CWS-R-004', '/design-system/components/chat-workspace-shell?ref=CWS-R-004&state=expanded-index&width=1932', 'desktop', 1932, 'normal', 'ltr', 0, 'expanded-index', '{"state":"expanded-index","viewportLabel":"desktop"}'::jsonb, 40, TRUE),
    ('CWS-R-005', 'Expanded workspace without index', 'Hiding the index gives the list pane the recovered space while chat width stays stable.', '/design-system/canonical-renderings/chat-workspace-shell/CWS-R-005', '/design-system/components/chat-workspace-shell?ref=CWS-R-005&state=expanded-no-index&width=1932', 'desktop', 1932, 'normal', 'ltr', 0, 'expanded-no-index', '{"state":"expanded-no-index","viewportLabel":"desktop"}'::jsonb, 50, TRUE),
    ('CWS-R-006', 'Discovery chat-session entity', 'Entity switching keeps the Discovery layer and exposes the Chat Session status set.', '/design-system/canonical-renderings/chat-workspace-shell/CWS-R-006', '/design-system/components/chat-workspace-shell?ref=CWS-R-006&state=discovery-chat-session&width=1932', 'desktop', 1932, 'normal', 'ltr', 0, 'discovery-chat-session', '{"state":"discovery-chat-session","viewportLabel":"desktop"}'::jsonb, 60, TRUE),
    ('CWS-R-007', 'Design architecture questions default', 'Design opens Product Discovery history and Architecture Questions by default.', '/design-system/canonical-renderings/chat-workspace-shell/CWS-R-007', '/design-system/components/chat-workspace-shell?ref=CWS-R-007&state=design-default&width=1932', 'desktop', 1932, 'normal', 'ltr', 0, 'design-default', '{"state":"design-default","viewportLabel":"desktop"}'::jsonb, 70, TRUE),
    ('CWS-R-008', 'Delivery stories default', 'Delivery opens Epics history and Stories in the floating status bar by default.', '/design-system/canonical-renderings/chat-workspace-shell/CWS-R-008', '/design-system/components/chat-workspace-shell?ref=CWS-R-008&state=delivery-default&width=1932', 'desktop', 1932, 'normal', 'ltr', 0, 'delivery-default', '{"state":"delivery-default","viewportLabel":"desktop"}'::jsonb, 80, TRUE),
    ('CWS-R-009', 'New chat active', 'Starting a chat removes the generated artifact block and keeps the composer at the bottom.', '/design-system/canonical-renderings/chat-workspace-shell/CWS-R-009', '/design-system/components/chat-workspace-shell?ref=CWS-R-009&state=new-chat&width=896', 'desktop', 896, 'normal', 'ltr', 0, 'new-chat', '{"state":"new-chat","viewportLabel":"desktop"}'::jsonb, 90, FALSE),
    ('CWS-R-010', 'Dense question statuses', 'Seven question statuses fit without card wobble or duplicate labels.', '/design-system/canonical-renderings/chat-workspace-shell/CWS-R-010', '/design-system/components/chat-workspace-shell?ref=CWS-R-010&state=dense-questions&width=1932', 'desktop', 1932, 'normal', 'ltr', 0, 'dense-questions', '{"state":"dense-questions","viewportLabel":"desktop"}'::jsonb, 100, FALSE),
    ('CWS-R-011', 'Status drop preview', 'Shows the subtle status drop affordance while row cards keep their governed size.', '/design-system/canonical-renderings/chat-workspace-shell/CWS-R-011', '/design-system/components/chat-workspace-shell?ref=CWS-R-011&state=status-drop&width=1932', 'desktop', 1932, 'normal', 'ltr', 0, 'status-drop', '{"state":"status-drop","viewportLabel":"desktop"}'::jsonb, 110, FALSE),
    ('CWS-R-012', 'Row reorder preview', 'Shows the list reorder insertion indicator using the established list behavior visuals.', '/design-system/canonical-renderings/chat-workspace-shell/CWS-R-012', '/design-system/components/chat-workspace-shell?ref=CWS-R-012&state=row-reorder&width=1932', 'desktop', 1932, 'normal', 'ltr', 0, 'row-reorder', '{"state":"row-reorder","viewportLabel":"desktop"}'::jsonb, 120, FALSE),
    ('CWS-R-013', 'Row detail drawer open', 'A selected list row gives one-third width to the list and two-thirds to the full-height drawer.', '/design-system/canonical-renderings/chat-workspace-shell/CWS-R-013', '/design-system/components/chat-workspace-shell?ref=CWS-R-013&state=row-drawer&width=1932', 'desktop', 1932, 'normal', 'ltr', 0, 'row-drawer', '{"state":"row-drawer","viewportLabel":"desktop"}'::jsonb, 130, TRUE),
    ('CWS-R-014', 'Optional expansion disabled', 'Optional expansion controls disappear while the chat surface remains usable.', '/design-system/canonical-renderings/chat-workspace-shell/CWS-R-014', '/design-system/components/chat-workspace-shell?ref=CWS-R-014&state=optional-off&width=896', 'desktop', 896, 'normal', 'ltr', 0, 'optional-off', '{"state":"optional-off","viewportLabel":"desktop"}'::jsonb, 140, FALSE),
    ('CWS-R-015', 'Empty scoped entity list', 'The list panel can show an empty scoped result without inflating row cards.', '/design-system/canonical-renderings/chat-workspace-shell/CWS-R-015', '/design-system/components/chat-workspace-shell?ref=CWS-R-015&state=empty-list&width=1932', 'desktop', 1932, 'normal', 'ltr', 0, 'empty-list', '{"state":"empty-list","viewportLabel":"desktop"}'::jsonb, 150, FALSE),
    ('CWS-R-016', 'Loading and error resolver states', 'Resolver feedback stays in the list region without moving the shell chrome.', '/design-system/canonical-renderings/chat-workspace-shell/CWS-R-016', '/design-system/components/chat-workspace-shell?ref=CWS-R-016&state=loading-error&width=1932', 'desktop', 1932, 'normal', 'ltr', 0, 'loading-error', '{"state":"loading-error","viewportLabel":"desktop"}'::jsonb, 160, FALSE),
    ('CWS-R-017', 'Unavailable scope', 'A denied or unavailable layer/entity/chat scope is visible without leaking rows.', '/design-system/canonical-renderings/chat-workspace-shell/CWS-R-017', '/design-system/components/chat-workspace-shell?ref=CWS-R-017&state=denied&width=1932', 'desktop', 1932, 'normal', 'ltr', 0, 'denied', '{"state":"denied","viewportLabel":"desktop"}'::jsonb, 170, FALSE),
    ('CWS-R-018', 'Tooltip and menu containment', 'Selectors and tooltips stay inside the component bounds and do not clip behind rails.', '/design-system/canonical-renderings/chat-workspace-shell/CWS-R-018', '/design-system/components/chat-workspace-shell?ref=CWS-R-018&state=tooltips&width=1180', 'desktop', 1180, 'normal', 'ltr', 0, 'tooltips', '{"state":"tooltips","viewportLabel":"desktop"}'::jsonb, 180, FALSE),
    ('CWS-R-019', 'Dark RTL magnified stress', 'Dark theme, RTL, and magnification stay scoped to the canonical specimen.', '/design-system/canonical-renderings/chat-workspace-shell/CWS-R-019', '/design-system/components/chat-workspace-shell?ref=CWS-R-019&state=dark-rtl&width=1180&theme=dark&dir=rtl&zoom=100', 'tablet', 1180, 'dark', 'rtl', 100, 'dark-rtl', '{"state":"dark-rtl","viewportLabel":"tablet"}'::jsonb, 190, TRUE),
    ('CWS-R-020', 'Mobile stacked shell', 'The component stacks for narrow review without desktop-only leftover columns.', '/design-system/canonical-renderings/chat-workspace-shell/CWS-R-020', '/design-system/components/chat-workspace-shell?ref=CWS-R-020&state=mobile&width=430', 'mobile', 430, 'normal', 'ltr', 0, 'mobile', '{"state":"mobile","viewportLabel":"mobile"}'::jsonb, 200, TRUE)
)
INSERT INTO design_system_canonical_references (
  design_system_canonical_reference_id,
  design_system_canonical_family_id,
  reference_id,
  normalized_reference_id,
  display_label,
  description,
  render_route_path,
  legacy_render_route_path,
  viewport,
  width,
  height,
  theme,
  direction,
  zoom,
  locale_fixture,
  label_density_fixture,
  state_variant_key,
  specimen_payload,
  status,
  sort_order,
  featured,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  chat_workspace_shell_family.design_system_canonical_family_id,
  reference_rows.reference_id,
  lower(reference_rows.reference_id),
  reference_rows.display_label,
  reference_rows.description,
  reference_rows.render_route_path,
  reference_rows.legacy_render_route_path,
  reference_rows.viewport,
  reference_rows.width,
  NULL,
  reference_rows.theme,
  reference_rows.direction,
  reference_rows.zoom,
  NULL,
  NULL,
  reference_rows.state_variant_key,
  reference_rows.specimen_payload,
  'live',
  reference_rows.sort_order,
  reference_rows.featured,
  NOW(),
  NOW()
FROM reference_rows
CROSS JOIN chat_workspace_shell_family
ON CONFLICT (design_system_canonical_family_id, normalized_reference_id)
DO UPDATE SET
  display_label = EXCLUDED.display_label,
  description = EXCLUDED.description,
  render_route_path = EXCLUDED.render_route_path,
  legacy_render_route_path = EXCLUDED.legacy_render_route_path,
  viewport = EXCLUDED.viewport,
  width = EXCLUDED.width,
  height = EXCLUDED.height,
  theme = EXCLUDED.theme,
  direction = EXCLUDED.direction,
  zoom = EXCLUDED.zoom,
  locale_fixture = EXCLUDED.locale_fixture,
  label_density_fixture = EXCLUDED.label_density_fixture,
  state_variant_key = EXCLUDED.state_variant_key,
  specimen_payload = EXCLUDED.specimen_payload,
  status = EXCLUDED.status,
  sort_order = EXCLUDED.sort_order,
  featured = EXCLUDED.featured,
  updated_at = NOW();
